### PR TITLE
change topicArns to map safe for concurrent access

### PR DESCRIPTION
**Pull request by nenikola**
# Description

Changed native map to xsync.MapOf which is safe for concurrent access

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3430 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this PR. Can you please replace the usage of the xsync package with Go's sync.Map? It has the same methods. https://pkg.go.dev/golang.org/x/sync/syncmap

**Comment by nenikola** [comment]
> Thanks for this PR. Can you please replace the usage of the xsync package with Go's sync.Map? It has the same methods. https://pkg.go.dev/golang.org/x/sync/syncmap

@yaron2 sure, I opted for xsync just because I saw it being used in [topicsLocker](https://github.com/dapr/components-contrib/blob/7fd5524c5842293c0e6d1d2427b56dbd7dddc100/pubsub/aws/snssqs/topics_locker.go#L20-L22).

Also, I saw `subscriptions` and `queues` are also of type regular map and seems like both could potentially face similar concurrent write issue. Would it make sense to change those to `sync.Map` too?

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
In this file we were doing synchronization using a mutex. For example, calls to `getOrCreateTopic` are wrapped around a lock:

https://github.com/dapr/components-contrib/blob/95a0a1339e2791f5d8cbdc071ba85062aa5be531/pubsub/aws/snssqs/snssqs.go#L762-L763

Rather than changing `topicArns`, it may make more sense to just ensure that wherever the access to the map was happening that wasn't wrapped in a log (and was causing the panic), uses the lock instead

**Comment by nenikola** [comment]
@ItalyPaleAle so I did something similar to what is done in the `Subscribe`  method by locking the topic when invoking `getOrCreateTopic` but would it make more sense for the method `getOrCreateTopic` to do the locking itself instead of its caller doing so?

The way it is now, caller of `getOrCreateTopic` needs to know that `getOrCreateTopic` method does unsafe map write, which shouldn't be the caller's concern per my understanding.

**Review by ItalyPaleAle — DISMISSED** [review]

**Comment by nenikola** [comment]
@ItalyPaleAle sounds good, let me add comment and then merge the changes. Thanks!

**Review by ItalyPaleAle — APPROVED** [review]
Thank you for this contribution and for fixing the issue!

**Comment by marcduiker** [comment]
@holopin-bot @nenikola Thank you Nikola!

**Pull request merged**
