### PR TITLE
upgrade/pulsar: upgrade pulsar from v0.1.0 to master

### PR DESCRIPTION
**Pull request by 1046102779**
panic 1: https://github.com/apache/pulsar-client-go/commit/b6841513379ea9ca503d1e350c5f93198fc2b03f

panic 2: https://github.com/apache/pulsar-client-go/commit/baaf68d89bc82ab83b714c0327ea51d58d9bd37f

panic 3: https://github.com/apache/pulsar-client-go/commit/29414db801a747672e6c0de62d0498d664e70d41

### CODE REVIEW

**Comment by daixiang0** [comment]
Could we use a latest release/bugfix version?

**Comment by 1046102779** [comment]
> Could we use a latest release/bugfix version?

No, at v0.6.0 if pulsar server return error, the logic server will be panic.

**Comment by daixiang0** [comment]
v0.6.1?

**Comment by 1046102779** [comment]
> How about v0.6.1?

image

**Review by daixiang0 — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
