### PR TITLE
Add contexts to input bindings

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
# Description

Adds support for contexts in input bindings.

This is the last part of the "shutdown sequence fix": it allows shutting down input bindings before output ones.

## Corresponding PR in dapr/dapr

https://github.com/dapr/dapr/pull/4846

## Pending actions

This PR is marked as "draft" until the following things are done. Note that for most PRs listed below from components-contrib, I've already merged the commits in this branch (so please do not squash those PRs before merging them!):

- [X] Open corresponding PR in dapr/dapr
- [x] Update certification tests with new APIs
- [x] https://github.com/dapr/components-contrib/pull/1820
- [x] https://github.com/dapr/components-contrib/pull/1821
- [x] https://github.com/dapr/components-contrib/pull/1822
- [x] https://github.com/dapr/components-contrib/pull/1823
- [x] https://github.com/dapr/components-contrib/pull/1824
- [x] https://github.com/dapr/components-contrib/pull/1825
- [x] https://github.com/dapr/components-contrib/pull/1826
- [x] https://github.com/dapr/components-contrib/pull/1827
- [x] https://github.com/dapr/components-contrib/pull/1828
- [x] https://github.com/dapr/components-contrib/pull/1829
- [x] https://github.com/dapr/components-contrib/pull/1830
- [x] https://github.com/dapr/components-contrib/pull/1837

### CODE REVIEW

**Review by daixiang0 — APPROVED** [review]

**Comment by daixiang0** [comment]
@ItalyPaleAle please fix conflicts.

**Comment by ItalyPaleAle** [comment]
> @ItalyPaleAle please fix conflicts.

Done

**Comment by ItalyPaleAle** [comment]
Please merge #1820 before merging this!

**Comment by berndverst** [comment]
You may need to run `make modtidy-all` again.

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
Thanks for this massive contribution.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
