### PR TITLE
Fix context used in kafka consume

### PR DESCRIPTION
**Pull request by jjcollinge**
Signed-off-by: Joni Collinge <jonathancollinge@live.com>

# Description

Use the consume context in the backoff retry of consume as the context parameter will be cancelled and not renewed.

Without this change the subscription does not recover once the context has been refreshed and no more messages are consumed.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
Looks like the Kafka conformance tests are failing, can you PTAL?

**Comment by yaron2** [comment]
> Looks like the Kafka conformance tests are failing, can you PTAL?

They still need fixing from an earlier PR. Some tests need to be removed as they checked for non conformant behavior where messages were still expected to be delivered after the subscription was cancelled

**Comment by jjcollinge** [comment]
@yaron2 I ended up removing the stop subscribers test. It looked to me that the test didn't have much value once we removed the logic to receive messages after the subscribe contexts had been cancelled. Let me know if you want me to reinstate it.

**Comment by ItalyPaleAle** [comment]
> @yaron2 I ended up removing the stop subscribers test. It looked to me that the test didn't have much value once we removed the logic to receive messages after the subscribe contexts had been cancelled. Let me know if you want me to reinstate it.

Wait please don't remove the entire test. There's a reason for that test, we want to make sure that context cancellation works!

**Comment by berndverst** [comment]
This PR should be made against main branch and then cherry picked.

In contrib we do not merge release back to main.

Can you change the base branch @jjcollinge

**Comment by berndverst** [comment]
@yaron2 advised this is not going to be merged for 1.13. So I will update your base branch for that reason also.

**Pull request closed without merging**
