### PR TITLE
ci: runs checkout first and bump setup-go to v5

### PR DESCRIPTION
**Pull request by mikeee**
# Description

#3319 introduced a setup step referencing a `go.mod` file to retrieve the go version. The repo needs to be checked out prior.
This should fix the automatic releases after tag

Also lint fixes for: #3436

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_N/A_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by berndverst — APPROVED** [review]
This is a good change to allow different go versions in different branches.

**Review by berndverst — CHANGES_REQUESTED** [review]
Ironically this breaks unit tests - can you take a look?

**Comment by mikeee** [comment]
> Ironically this breaks unit tests - can you take a look?

@berndverst Just had a quick look, the workflow that is failing isn't modified in any way by this PR. Is it perhaps more a flaky log assertion/comparison that a rerun could yield a successful test?

**Comment by mikeee** [comment]
Just triggered with an empty commit and appears to be passing 👌

**Comment by mikeee** [comment]
Latest commit introduces a lot of changes to resolve the linting issues

**Comment by mikeee** [comment]
Appears usurped, closing

**Pull request closed without merging**
