### PR TITLE
Run conformance tests for PRs, whenever that is possible

### PR DESCRIPTION
**Pull request by tcnghia**
# Description

Run conformance tests not requiring secrets automatically for pull requests.

## Issue reference

Please reference the issue this PR will close: N/A

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by tcnghia** [comment]
Sample run for PR: https://github.com/tcnghia/components-contrib/actions/runs/548821191
Sample run for Cron: https://github.com/tcnghia/components-contrib/actions/runs/548822115

**Comment by artursouza** [comment]
No, please. This can open arbitrary code to use our credentials in Azure and other cloud providers.

**Review by artursouza — CHANGES_REQUESTED** [review]
No, please.

**Comment by tcnghia** [comment]
> No, please. This can open arbitrary code to use our credentials in Azure and other cloud providers.

Pull requests don't have access to secrets, and also, we don't run anything requiring secrets in pull requests workflow.

Plus, I can run pull requests workflow even if I am not checking this PR in. You can see that in the workflows being executed for this PR itself.

**Comment by tcnghia** [comment]
@artursouza @mukundansundar please see the workflow scheduled by this PR here https://github.com/dapr/components-contrib/actions/runs/548839442 . We can't stop PRs from running this workflow.

**Comment by artursouza** [comment]
OK, got it. Good to know that secrets are not accessible from PRs.

**Comment by tcnghia** [comment]
Thanks @artursouza . Can you please also help merge?

**Pull request merged**
