### PR TITLE
Adding GetDel support for Redis Bindings

### PR DESCRIPTION
**Pull request by Vishal07051999**
# Description

Get Del Support for Redis Bindings

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/2661

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
As discussed on the issue, it is unclear whether we want to accept this feature. You opened a PR immediately after opening an issue - that is a risky move.

We will have to decide first whether we want to add this feature.

Now from a PR perspective, this PR would also need a test covering this new operation in `tests/certification/binding/redis`

**Review by berndverst — CHANGES_REQUESTED** [review]
Please provide business / architecture background on the issue to explain the need for this.

If we decide to proceed, then I suggest that we do not make this a new operation, instead we add a new metadata property for the `Get` operation `delete: true`. Only if the Get operation is invoked and the delete metadata property is set and true, then under the hood you would invoke the `GetDel` function. Does that make sense?

Having too many operations is not good for users or maintainers, and we do not want to be just a SDK passthrough tool. We can choose an opinionated approach here :)

Oh and by the way as I mentioned in another comment, you also must update the certification tests at `tests/certification/binding/redis`

**Comment by Vishal07051999** [comment]
> Please provide business / architecture background on the issue to explain the need for this.
> 
> If we decide to proceed, then I suggest that we do not make this a new operation, instead we add a new metadata property for the `Get` operation `delete: true`. Only if the Get operation is invoked and the delete metadata property is set and true, then under the hood you would invoke the `GetDel` function. Does that make sense?
> 
> Having too many operations is not good for users or maintainers, and we do not want to be just a SDK passthrough tool. We can choose an opinionated approach here :)
> 
> Oh and by the way as I mentioned in another comment, you also must update the certification tests at `tests/certification/binding/redis`

Updated Certification Tests.

Also, agree with the point of delete being a MetaData Parameter instead of a separate operation. Under the hood, it will use `Redis GetDel Operation when delete flag is 'true' in metadata`.

**Comment by Vishal07051999** [comment]
Lint Issues fixed.

**Comment by yaron2** [comment]
> Lint Issues fixed.

One more linter issue: https://github.com/dapr/components-contrib/actions/runs/4410063633/jobs/7727120068.

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
I fixed the linter error for you to get this merged.

**Comment by Vishal07051999** [comment]
Thanks @yaron2 .

**Pull request merged**
