### PR TITLE
secretstores: support more format of azure key vault

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

# Description

Check whether the URI match DNS suffix, if not, use Azure Cloud DNS suffix by default.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #918

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
ping @pkedy

**Comment by CodeMonkeyLeet** [comment]
Code change looks good. @daixiang0 per the PR checklist, can you also file an issue for dapr/docs and update the https://docs.dapr.io/reference/components-reference/supported-secret-stores/azure-keyvault/ to describe the updated behavior for `vaultName`?

**Comment by daixiang0** [comment]
@CodeMonkeyLeet done.

**Review by pkedy — APPROVED** [review]
LGTM

**Comment by daixiang0** [comment]
@pkedy hi, is there anything I can do to make it merged?

**Comment by yaron2** [comment]
Thanks for your contribution @daixiang0

**Pull request merged**
