### PR TITLE
Query StateStore API implementation for PostgreSQL StateStore

### PR DESCRIPTION
**Pull request by r-c-correa**
# Description

This PR introduces a Query State for PostgreSQL Statestore component. The code is implemented following the example of the MongoDB Query State.

## Issue reference

Please reference the issue this PR will close: #1456

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation: dapr/docs/issues/2159

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this PR @r-c-correa.

cc @dmitsh @artursouza

**Comment by yaron2** [comment]
@dmitsh can you please review this?

**Comment by dmitsh** [comment]
LGTM
@yaron2 @artursouza , is conformance test required for this component?

**Comment by r-c-correa** [comment]
Hi @dmitsh, this component extend PostgreSQL by adding support for Query. I didn't change anything related to MQTT (which is where the "Stable Components Certification Tests" failed) 😃

**Comment by dmitsh** [comment]
> Hi @dmitsh, this component extend PostgreSQL by adding support for Query. I didn't change anything related to MQTT (which is where the "Stable Components Certification Tests" failed) 😃

I'm aware that your PR does not touch MQTT :) 
BTW, the MQTT certification test have passed.

My question was - whether we need to add conformance test for PostgreSQL Query API.

**Comment by r-c-correa** [comment]
Hi @dmitsh, I just added the conformance test for PostgreSQL Query API, I had to make a small adjustment in the tests due to the JSON format that is stored in PostgreSQL versus MongoDB, this adjustment will eliminate future possibilities of minor divergences between technologies in the JSON format, as shown below:
pg-error

Any suggestions or questions just let me know, thanks 😃

**Review by dmitsh — APPROVED** [review]

**Comment by dmitsh** [comment]
LGTM, please rebase the branch

**Review by yaron2 — APPROVED** [review]
LGTM.

Great work @r-c-correa

**Pull request merged**
