### PR TITLE
specify exact Go version

### LINKED ISSUE #3545: toolchain not available
## Actual Behavior

```
# go mod tidy
go: downloading go1.23 (darwin/amd64)
go: download go1.23 for darwin/amd64: toolchain not available
```

Root cause refer to https://github.com/golang/go/issues/62278

### PR DESCRIPTION
**Pull request by daixiang0**
# Description

Fix #3545

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3545

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by JoshVanL — APPROVED** [review]

**Comment by yaron2** [comment]
Needs go mod tidy

**Comment by elena-kolevska** [comment]
Looks like this has been addressed in the meantime. Can we close?

**Comment by berndverst** [comment]
We should have specified it like so:

```
go 1.23
toolchain go1.23.0
```

Otherwise our CI may use the pinned minor version of GO only. But we want it to always use the latest available!

**Comment by berndverst** [comment]
This PR seems no longer applicable

**Pull request closed without merging**
