### PR TITLE
extend envelop to include a subject field

### PR DESCRIPTION
**Pull request by Haishi2016**
This extention is to allow carrying correlation ID in cloud event envelop.

### CODE REVIEW

**Comment by LMWF** [comment]
Does the proto need an update too?

**Comment by Haishi2016** [comment]
> Does the proto need an update too?

This is not a protobuf type

**Comment by yaron2** [comment]
@youngbupark is GH drunk again?

**Comment by Haishi2016** [comment]
> @youngbupark is GH drunk again?

No, my bad, didn't update test cases

**Pull request merged**
