### PR TITLE
Add priority parameters to RabbitMQ queue and message

### PR DESCRIPTION
**Pull request by kzmake**
# Description

- Add max priority param to RabbitMQ binding to allow creation of priority queues
- Added priority parameter to publish message with priority 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #582 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/
    * repo: https://github.com/dapr/docs/issues/1101

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks for this PR @kzmake! did you get a chance to test these changes to make sure we have no regressions with either pub/sub and bindings for RabbitMQ?

**Comment by kzmake** [comment]
Hi @yaron2 , thank you for merging 'master' into this branch.
I tested `rabbitmq_integration_test` and tried to check the regression.
The tests added in this pr and everything else passed the test, but only `TestExclusiveQueue` doesn't work on master branch or this branch.

```bash
$ docker run -d --hostname rabbit --name test-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
$ export DAPR_TEST_RABBITMQ_HOST=amqp://guest:guest@localhost:5672
$ go test -tags=integration_test --run "TestExclusiveQueue" github.com/dapr/components-contrib/bindings/rabbitmq -v
=== RUN   TestExclusiveQueue
    rabbitmq_integration_test.go:231:
                Error Trace:    rabbitmq_integration_test.go:231
                Error:          "Exception (405) Reason: \"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue '3f81e75f-8e07-4975-8cb4-7a50b40261f5' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.\"" does not contain "404"
                Test:           TestExclusiveQueue
--- FAIL: TestExclusiveQueue (0.08s)
```

Please tell me what to do 🙏

**Comment by yaron2** [comment]
> Hi @yaron2 , thank you for merging 'master' into this branch.
> I tested `rabbitmq_integration_test` and tried to check the regression.
> The tests added in this pr and everything else passed the test, but only `TestExclusiveQueue` doesn't work on master branch or this branch.
> 
> ```shell
> $ docker run -d --hostname rabbit --name test-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
> $ export DAPR_TEST_RABBITMQ_HOST=amqp://guest:guest@localhost:5672
> $ go test -tags=integration_test --run "TestExclusiveQueue" github.com/dapr/components-contrib/bindings/rabbitmq -v
> === RUN   TestExclusiveQueue
>     rabbitmq_integration_test.go:231:
>                 Error Trace:    rabbitmq_integration_test.go:231
>                 Error:          "Exception (405) Reason: \"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue '3f81e75f-8e07-4975-8cb4-7a50b40261f5' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.\"" does not contain "404"
>                 Test:           TestExclusiveQueue
> --- FAIL: TestExclusiveQueue (0.08s)
> ```
> 
> Please tell me what to do 🙏

This test passes for master branch on my local machine and in our CI too (as you can see below, "All checks have passed") so I assume this might be something local.

**Comment by yaron2** [comment]
> > Hi @yaron2 , thank you for merging 'master' into this branch.
> > I tested `rabbitmq_integration_test` and tried to check the regression.
> > The tests added in this pr and everything else passed the test, but only `TestExclusiveQueue` doesn't work on master branch or this branch.
> > ```shell
> > $ docker run -d --hostname rabbit --name test-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
> > $ export DAPR_TEST_RABBITMQ_HOST=amqp://guest:guest@localhost:5672
> > $ go test -tags=integration_test --run "TestExclusiveQueue" github.com/dapr/components-contrib/bindings/rabbitmq -v
> > === RUN   TestExclusiveQueue
> >     rabbitmq_integration_test.go:231:
> >                 Error Trace:    rabbitmq_integration_test.go:231
> >                 Error:          "Exception (405) Reason: \"RESOURCE_LOCKED - cannot obtain exclusive access to locked queue '3f81e75f-8e07-4975-8cb4-7a50b40261f5' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.\"" does not contain "404"
> >                 Test:           TestExclusiveQueue
> > --- FAIL: TestExclusiveQueue (0.08s)
> > ```
> > 
> > 
> > Please tell me what to do 🙏
> 
> This test passes for master branch on my local machine and in our CI too (as you can see below, "All checks have passed") so I assume this might be something local.

Actually hold on, there are some other issues with the integration tests file.. need to look into that.

**Comment by kzmake** [comment]
@yaron2 Thanks! The test still fails, but I've confirmed that this pr is working as expected.

**Comment by kzmake** [comment]
There was a problem with an existing integration test.
I have confirmed that there is no regression with the following changes.

May I include that commit in this PR?

https://github.com/kzmake/components-contrib/compare/feature/rabbitmq-priority-queue...kzmake:feature/rabbitmq-priority-queue-with-fix-integration-test

**Comment by yaron2** [comment]
> There was a problem with an existing integration test.
> I have confirmed that there is no regression with the following changes.
> 
> May I include that commit in this PR?
> 
> [kzmake/components-contrib@feature/rabbitmq-priority-queue...kzmake:feature/rabbitmq-priority-queue-with-fix-integration-test](https://github.com/kzmake/components-contrib/compare/feature/rabbitmq-priority-queue...kzmake:feature/rabbitmq-priority-queue-with-fix-integration-test)

Yes, please.

**Comment by kzmake** [comment]
I've just completed!
The Exclusive Queue remained because r.connection was open. 
Fixed an exclusive queue integration test with this commit: https://github.com/dapr/components-contrib/pull/606/commits/09ed91c2a80637077ef35477a56bbed647ceaae6

**Comment by yaron2** [comment]
hey @kzmake generally the PR looks good!

I'm thinking maybe we should keep this for the binding only and remove from pub/sub as it's a more abstracted layer that shouldn't offer priority.

Also, did you get to test the changes with an actual RabbitMQ running to check for regressions?

**Review by yaron2 — APPROVED** [review]

**Comment by kzmake** [comment]
@yaron2 Thanks, I got it! I reverted the pub/sub component to a previous commit.

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
Congratulations and thanks for this PR @kzmake!
 
Can you please open a docs issue to update the binding spec? https://github.com/dapr/docs/blob/5724cfb26c95b53ef55cb5c8615433fc4cba9c4b/daprdocs/content/en/operations/components/setup-bindings/supported-bindings/rabbitmq.md

Make sure you open the PR against the 1.0.0-rc.3 branch.

**Comment by kzmake** [comment]
@yaron2 Thanks! I’ll get right on it.

**Pull request merged**
