### PR TITLE
bugfixes: visibility timeout, dlq queue attributes

### PR DESCRIPTION
**Pull request by amimimor**
Signed-off-by: Amit Mor <amit.mor@hotmail.com>

# Description

bugfixes
1. reset visibility timeout to zero so other consumer can immediately consume retried but failed messages
2. not setting/rewritting SQS attributes when DLQ is set and also disableEntityManagement 

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1445 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Please add tests to ensure fix.

**Comment by amimimor** [comment]
> Please add tests to ensure fix.

Thanks for your feedback.

Testing this component is currently done (semi-)manually over `localstack` and later over a live AWS environment. However, `localstack` is not as enforcing as a real AWS environment in many aspects and thus provides basic SNS/SQS functionality. 

Testing manually over a real environment takes time and some of the component features are complicated to test (like resetting a message visibility timeout so that other consumers can consume the messages that the consumer pulled and failed to process)

I think that by their nature, these bugs can be covered by heavily investing in mocking AWS services and tests in the spirit of certification tests but on a live AWS environment. Unit testing just doesn't cover these kind of bugs so until mocks and certification tests are in place, your suggestions, as valuable as they are, are currently unrealistic as my time is limited

**Comment by daixiang0** [comment]
@amimimor got it, let's create an issue to track it :)

**Comment by amimimor** [comment]
> @amimimor got it, let's create an issue to track it :)

Will do. Thanks!

**Review by berndverst — APPROVED** [review]

**Pull request merged**
