### PR TITLE
Add pubsub nsq

### PR DESCRIPTION
**Pull request by LiPL2017**
# Description

A pubsub that allows publish / subscribe from NSQ.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by pkedy — CHANGES_REQUESTED** [review]
Small changes around configuration requested. Awesome to see the addition of NSQ!

**Comment by pkedy** [comment]
@LiPL2017 Also take a look at the linter issues.

**Comment by yaron2** [comment]
@LiPL2017 can you please resolve the conflicts?

**Comment by LiPL2017** [comment]
> @LiPL2017 can you please resolve the conflicts?

Please check it.

**Comment by yaron2** [comment]
@LiPL2017 there's a linter issue (formatting) on one of the files:  Error: File is not `gofumpt`-ed (gofumpt). Look at the "Files Changed" to see which.

**Comment by daixiang0** [comment]
ping @LiPL2017

**Comment by yaron2** [comment]
@LiPL2017 why did you close this PR?

**Comment by LiPL2017** [comment]
> @LiPL2017 why did you close this PR?

I'm so sorry. Because of my poor english, i don't know what to do about this pr. Maybe someone else will provide a better solution.

**Comment by ibice** [comment]
I'd love to pick up @LiPL2017's work to support nsq. Is it ok if I create a new PR using this code?

**Pull request closed without merging**
