### PR TITLE
Add Event Hubs conformance tests to GitHub workflow

### PR DESCRIPTION
**Pull request by CodeMonkeyLeet**
# Description

- Add the EventHubs bindings and pubsub conformance tests to the automated conformance.yml workflow
- Update conformance test setup for EventHubs to allow the EventHubs pubsub and bindings tests to run concurrently in the workflow by separating the targeted EventHubs and checkpoint storage containers.

> ⚠ This PR requires updating the Dapr Azure test environment before it can be merged. 

##  Issue reference

This PR will also serve as a case study for addressing #1001 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
@CodeMonkeyLeet are you still working on this?

This will be helpful as we are trying to GA Event Hubs for Pubsub

#951

**Comment by CodeMonkeyLeet** [comment]
> @CodeMonkeyLeet are you still working on this?

Yes. Note that the contents of this PR are not likely to change much except for updates from master, but it cannot be merged until a PR for #1001 is available to deploy the Eventhubs resources required by this workflow. 

Also note that the pieces to [automate Azure resource deployment](https://github.com/dapr/components-contrib/blob/master/.github/infrastructure/conformance/azure/README.md) used in [conformance tests](https://github.com/dapr/components-contrib/blob/master/tests/conformance/README.md) locally is already available.

**Comment by yaron2** [comment]
Please remove the tests for Azure Event Hubs, as we'll be removing it in 1.5 or 1.6 after deprecating in 1.4.
The fact of the matter is that Azure Event Hubs does not allow for multiple apps to subscribe to different topics using the same pub/sub component, which is a basic and fundamental requirement.

**Comment by CodeMonkeyLeet** [comment]
> Please remove the tests for Azure Event Hubs, as we'll be removing it in 1.5 or 1.6 after deprecating in 1.4.
> The fact of the matter is that Azure Event Hubs does not allow for multiple apps to subscribe to different topics using the same pub/sub component, which is a basic and fundamental requirement.
> 
> /cc @artursouza

@yaron2 To be clear, are you suggesting that both the Event Hubs _pubsub_ component and the Event Hubs _bindings_ component will be removed? From the Discord comments, I was only expecting that the pubsub component would be deprecated. If we're dropping the pubsub component, I can simplify the test so I don't need to configure multiple EventHubs and checkpoint storages (essentially just drop commit 993e4983b1aca40c751d5ab0e7b8151521f600f5), but Event Hubs bindings stills needs a conformance test.

**Comment by berndverst** [comment]
There are too many issues to resolve here and the complexity and infra requirements are simply too much to ever certify any possible approach as GA.

This component needs to be deprecated.

**Comment by artursouza** [comment]
> > Please remove the tests for Azure Event Hubs, as we'll be removing it in 1.5 or 1.6 after deprecating in 1.4.
> > The fact of the matter is that Azure Event Hubs does not allow for multiple apps to subscribe to different topics using the same pub/sub component, which is a basic and fundamental requirement.
> > /cc @artursouza
> 
> @yaron2 To be clear, are you suggesting that both the Event Hubs _pubsub_ component and the Event Hubs _bindings_ component will be removed? From the Discord comments, I was only expecting that the pubsub component would be deprecated. If we're dropping the pubsub component, I can simplify the test so I don't need to configure multiple EventHubs and checkpoint storages (essentially just drop commit [993e498](https://github.com/dapr/components-contrib/commit/993e4983b1aca40c751d5ab0e7b8151521f600f5)), but Event Hubs bindings stills needs a conformance test.


My understanding is that Azure Event Hub will still be supported in bindings.

**Comment by yaron2** [comment]
> > > Please remove the tests for Azure Event Hubs, as we'll be removing it in 1.5 or 1.6 after deprecating in 1.4.
> > > The fact of the matter is that Azure Event Hubs does not allow for multiple apps to subscribe to different topics using the same pub/sub component, which is a basic and fundamental requirement.
> > > /cc @artursouza
> > 
> > 
> > @yaron2 To be clear, are you suggesting that both the Event Hubs _pubsub_ component and the Event Hubs _bindings_ component will be removed? From the Discord comments, I was only expecting that the pubsub component would be deprecated. If we're dropping the pubsub component, I can simplify the test so I don't need to configure multiple EventHubs and checkpoint storages (essentially just drop commit [993e498](https://github.com/dapr/components-contrib/commit/993e4983b1aca40c751d5ab0e7b8151521f600f5)), but Event Hubs bindings stills needs a conformance test.
> 
> My understanding is that Azure Event Hub will still be supported in bindings.

That was my intention - there is no issue with the Event Hubs binding.

**Comment by CodeMonkeyLeet** [comment]
Closing this PR to split out removal of EventHubs pubsub tests (#1095) from adding EventHubs binding conformance test to conformance.yml (TBD)

**Pull request closed without merging**
