### PR TITLE
Fix Kafka consumer

### PR DESCRIPTION
**Pull request by yaron2**
Fixes https://github.com/dapr/components-contrib/issues/3263.

The way the Kafka component was handling subscription topics was not inline with how Sarama should be correctly used. Until this change, for every new subscription added, the consumer group was closed and started again which in many cases could (and did as reported by users) lead to a cluster-wide outage, as that action involved a rebalance of Kafka partitions. Depending on the number of topics, messages and consumers, Dapr processes would take sometimes minutes to load and in the worst case causing a bottleneck in the Kafka brokers.

This PR fixes that by cancelling and recreating the context for the `Consume` function every time a subscription is added instead of closing down the entire consumer group. This is the correct way of doing that according to Sarama committers and users.
In addition, the PR further optimizes the logic by using a single goroutine to consume topics instead of N goroutines as the number of topics. This is also aligned with proper Sarama usage.

This fix has been tested in a user's live environment. After applying this fix, the following was observed:

1. Dapr sidecar init time decreased from +12s to less than 300ms
2. Kafka cluster outage stopped with all messages successfully processed

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
LGTM, please cherry-pick into release-1.12 when merged

**Comment by yaron2** [comment]
> LGTM, please cherry-pick into release-1.12 when merged

Done here: https://github.com/dapr/components-contrib/pull/3297.

The file structure is different so couldn't cherry-pick.

**Comment by olitomlinson** [comment]
Can confirm a big noticeable decrease in time taken to init. My local repro with 5 subscribers, this is now down from 15s to 3s. Which is really positive!

I will try to validate on a real cluster tomorrow.

Thanks so much!!

**Comment by ParrySMS** [comment]
Thanks so much!!   yaron2, you are th true hero

**Pull request merged**
