### PR TITLE
[wip] graphql binding variable support

### PR DESCRIPTION
**Pull request by serpentfabric**
# Description

attempt to idiomatically add support for graphql variables in the bindingrequest's metadata to help prevent injection attacks as outlined in https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#injection-prevention

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2517

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#3165

### CODE REVIEW

**Comment by mikocot** [comment]
shouldn't required checks run automatically already?

**Comment by berndverst** [comment]
> shouldn't required checks run automatically already?

No. I disabled that for folks who are not part of our Dapr Github org. Infrequent contributors were exhausting our CI runners causing huge pain points for the core contributors.

**Comment by berndverst** [comment]
Locally run

```
make test
make lint
```

There are more tests for components that are Beta, but for Alpha components this is all.

**Comment by berndverst** [comment]
I would like to see the following unit test:

- Set up a Mock HTTP server (one we can use to verify the request)
- Initialize the GraphQL binding using the URL to the Mock HTTP server
- Create test metadata and call the invoke method using this metadata - specifying variables using the `variable:` syntax and headers using the `header:` syntax.
- Assert that the HTTP server was called with a POST request and the expected JSON body containing the variables and headers from the test metadata.

**Review by berndverst — CHANGES_REQUESTED** [review]
I would like to see the following unit test:

Set up a Mock HTTP server (one we can use to verify the request)
Initialize the GraphQL binding using the URL to the Mock HTTP server
Create test metadata and call the invoke method using this metadata - specifying variables using the variable: syntax and headers using the header: syntax.
Assert that the HTTP server was called with a POST request and the expected JSON body containing the variables and headers from the test metadata.

This resource should be helpful: https://clavinjune.dev/en/blogs/mocking-http-call-in-golang-a-better-way/

**Pull request closed without merging**
