### PR TITLE
Bump NATS dependencies

### PR DESCRIPTION
**Pull request by Jarema**
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

# Description

Since version 2.7.4, there were a lot of improvements, features and bug fixes for NATS Jetstream.
This PR bumps dependencies to be able to leverage those changes.

## Issue reference

If you need an Issue for manual dependency bumps, let me know. I will create one.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
Unfortunately this will just miss our release 1.9.0. It will go into 1.10.0 to be released in January.

**Comment by Jarema** [comment]
@berndverst Shame, though I'll use that time to think how to add new NATS features to DAPR bindings and issue rellevant issues and PRs, so January release could leverage those.

**Review by berndverst — CHANGES_REQUESTED** [review]
Please run "make modtidy-all" from the root of this repo and commit the changes to those go.mod and go.sum files also.

**Comment by berndverst** [comment]
> @berndverst Shame, though I'll use that time to think how to add new NATS features to DAPR bindings and issue rellevant issues and PRs, so January release could leverage those.

Yes sadly you missed it by a few days. The code freeze was last week (you can see the release planning issue in the dapr/dapr repo). We cut our release branches end of last week and then just create some RCs to validate behavior and performance.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
