### PR TITLE
[pubsub/jetstream]: allow tls client authentication

### LINKED ISSUE #1923: [Jetstream] Allow TLS Client Authentication
Looking at the docs, and the configuration struct for Jetstream, it doesn't seem like TLS Client Authentication can be used.

https://github.com/dapr/components-contrib/blob/e639685e83b3a2ad1a73fc89a4370b6d11ed9d17/pubsub/jetstream/metadata.go#L24-L36

I wonder if it is a trivial addition?

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
# Description

- Configure the NATS client for TLS Client Authentication if a key pair is supplied.

## Issue reference

- Closes #1923

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#2697

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thanks @NickLarsenNZ for this contribution!

For the CA cert, do you think it would be possible to use the new feature in 1.8 to add the cert to the Dapr container rather than adding something specific to this component? https://docs.dapr.io/operations/configuration/install-certificates/

**Comment by NickLarsenNZ** [comment]
@ItalyPaleAle, regarding the CA cert, yeah I guess most people will run it from a container so probably good enough to just do it as per your suggestion. I'll come back to remove this from here and the docs tomorrow.

As for v1.8, do you mean this feature doesn't have to wait until 1.9? I just went with what the docs hinted towards (see dapr/docs#2697).

**Comment by yaron2** [comment]
> @ItalyPaleAle, regarding the CA cert, yeah I guess most people will run it from a container so probably good enough to just do it as per your suggestion. I'll come back to remove this from here and the docs tomorrow.
> 
> As for v1.8, do you mean this feature doesn't have to wait until 1.9? I just went with what the docs hinted towards (see [dapr/docs#2697](https://github.com/dapr/docs/issues/2697)).

To be clear, the PR will go into 1.9.

**Comment by ItalyPaleAle** [comment]
@NickLarsenNZ 

> regarding the CA cert, yeah I guess most people will run it from a container so probably good enough to just do it as per your suggestion. I'll come back to remove this from here and the docs tomorrow.

Well, the solution works in non-containerized methods too. In that case, the sidecar (daprd) is a process on the operating system, and it should be able to pick up certs from the OS' trust store. So to add a new root CA, you'd add it to your OS' trust store (for example on Mac you'd add it to the Keychain, and on Windows you use mmc.exe to add it to the trust store).

Adding a cert to the root trust store in the OS has always been supported by Dapr. What we added in 1.8 was a way to make it possible to do that with a Docker container (in Kubernetes or as a standalone container or using Docker Compose) that doesn't require building custom containers.

The only reason why I brought this up is that given how we've been trying to standardize adding root CA certs through the "standard" way (of adding them to the OS trust store), I would prefer not to create a duplicate way to do that which is component-specific. Because next thing you know, every component would have to be updated to add a component-specific way to add a custom CA.... and that's something else we'll have to maintain 🙃

> As for v1.8, do you mean this feature doesn't have to wait until 1.9

No, as @yaron2  confirmed this feature will definitely have to wait for 1.9.

I mentioned 1.8 because that's when we shipped support for adding root CA certs in Docker too.

**Review by mukundansundar — DISMISSED** [review]
LGTM

**Comment by NickLarsenNZ** [comment]
@yaron2 @ItalyPaleAle @mukundansundar I've removed the CA section, and updated the docs. Should be good to go.

**Review by ItalyPaleAle — APPROVED** [review]
:shipit: thanks for the PR :)

**Review by mukundansundar — APPROVED** [review]
lgtm. Thanks for the contribution !!

**Review by berndverst — APPROVED** [review]

**Comment by mukundansundar** [comment]
@NickLarsenNZ Can you fix the linter error that we are seeing?

**Comment by ItalyPaleAle** [comment]
@mukundansundar the linter error seems to be due to timeouts and not @NickLarsenNZ 's fault. Hopefully #1931 can be merged to fix this

**Comment by gehhilfe** [comment]
Thank you, @NickLarsenNZ wanted to add the same, but you were faster!

**Pull request merged**
