### PR TITLE
Support and use Go 1.22

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Adds support for Go 1.22 and uses Go 1.22.

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
@berndverst some tests are failing, including build/lint

**Comment by berndverst** [comment]
I'll fix this up and merge this by EOW

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @berndverst as a maintainer you also get a badge :)

**Pull request merged**
