### PR TITLE
WIP: Add Redis StateStore Conformance Tests

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description
This PR adds an initial state store conformance test for the redis component. The junit report doesn't have enough precision for some of the operation times.

```
$: go test -v ./tests/... 2&>1 | go-junit-report

<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
        <testsuite tests="7" failures="0" time="0.000" name="github.com/dapr/components-contrib/tests/conformance/state">
                <properties>
                        <property name="go.version" value="go1.14.2"></property>
                </properties>
                <testcase classname="state" name="TestRedis" time="0.020"></testcase>
                <testcase classname="state" name="TestRedis/init" time="0.000"></testcase>
                <testcase classname="state" name="TestRedis/set" time="0.000"></testcase>
                <testcase classname="state" name="TestRedis/get" time="0.000"></testcase>
                <testcase classname="state" name="TestRedis/delete" time="0.000"></testcase>
                <testcase classname="state" name="TestRedis/bulkset" time="0.010"></testcase>
                <testcase classname="state" name="TestRedis/bulkdelete" time="0.000"></testcase>
        </testsuite>
</testsuites>
```

Let's try to agree on what a conformant state store implementation includes:
- Acceptable perf per operation
- Required operations
- Acceptable operation inputs/outputs

Additionally, how do we want to invoke these tests, something like:
`make run-conformance-tests` which defaults to running all
`make run-conformance-tests TEST=TestRedis` runs just the redis test

Also, where do we plan to publish the results?

When I initially added more statestores to the test set, `mongodb`, `cassandra` and `zookeeper` failed due to bugs/inconsistencies.

## Issue reference
Please reference the issue this PR will close: #204 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by youngbupark** [comment]
Thanks for your contribution! :)

I have some comments:

* Test report - can we generate junit report format report ? I think we can leverage https://github.com/jstemmer/go-junit-report

* Please do not use python code. I would not use the multiple languages if possible. 

* Please do not include test result. Test result will be in the separate repo.

* Could you please split the PR and expand the test coverage iteratively ? For the first iteration, I would target only one state store, such as redis. Then I would focus on designing test sets with maintainers. Once we have complete test sets which we all agree, it is easy to test the other components and expand the test coverage.

**Comment by jjcollinge** [comment]
@youngbupark thanks for the feedback - all good points. I've reverted the changes to just redis tests and backed out the custom reporting (not sure why I didn't think of junit in the first place!).

**Comment by youngbupark** [comment]
Thanks @jjcollinge for this work. 

@amanbha @yaron2 Can you please give your feedbacks on this ? This is the initial commit for redis state store conformance tests. Even if this PR includes redis test, the test codes will be generic and will be used for the other state stores.

cc/ @mchmarny @msfussell

**Comment by jjcollinge** [comment]
Just for reference and to help us position the acceptable performance constraints, this was the report I generated when I had more statestores in the test set. This was just ran on my machine under a non controlled environment.
```
State Stores
------------
init:
  etcd: 1151μs
  cassandra: 17818μs
  consul: 80μs
  aerospike: 11485μs
  memcached: 1388μs
  hazelcast: 6526μs
  mongodb: 69μs
  redis: 2337μs
get:
  etcd: 895μs
  cassandra: 3638μs
  consul: 1011μs
  aerospike: 3603μs
  memcached: 579μs
  hazelcast: 705μs
  mongodb: 666μs
  redis: 679μs
set:
  etcd: 1326μs
  cassandra: 2807μs
  consul: 1642μs
  aerospike: 2242μs
  memcached: 794μs
  hazelcast: 800μs
  mongodb: 6020μs
  redis: 781μs
delete:
  etcd: 683μs
  cassandra: 57965μs
  consul: 1025μs
  aerospike: 719μs
  memcached: 747μs
  hazelcast: 750μs
  mongodb: 2106μs
  redis: 715μs
bulkset:
  etcd: 10438μs
  cassandra: 17745μs
  consul: 8490μs
  aerospike: 6391μs
  memcached: 6710μs
  hazelcast: 7323μs
  mongodb: 21096μs
  redis: 6072μs
bulkdelete:
  etcd: 10273μs
  cassandra: 16579μs
  consul: 8989μs
  aerospike: 5620μs
  memcached: 5458μs
  hazelcast: 6429μs
  mongodb: 20429μs
  redis: 6096μs
```

**Comment by jjcollinge** [comment]
@yaron2 do you think this is worth including for 0.9?  When I added support for most of the state providers it raised a number of bugs/issues across them. Some I’ve seen have been fixed since such as Mongo but there were others. Unfortunately, I didn’t raise them separately at the time. Happy to chat with a broader team to decide what should be included and implement it.

**Comment by yaron2** [comment]
> @yaron2 do you think this is worth including for 0.9? When I added support for most of the state providers it raised a number of bugs/issues across them. Some I’ve seen have been fixed since such as Mongo but there were others. Unfortunately, I didn’t raise them separately at the time. Happy to chat with a broader team to decide what should be included and implement it.

We reviewed this test suite, I think it's great. I like how this focuses on the interfaces and has a very clean structure to it.

Re: bugs in other state stores, it'd really help if you could raise these issues :)

As conformance tests are one of our top priorities right now, it'd be great to get your help with those. I believe most tests will look very similar to this one.

**Comment by mukundansundar** [comment]
@jjcollinge can this PR be closed since it has been integrated with a different PR https://github.com/dapr/components-contrib/pull/586

**Comment by jjcollinge** [comment]
@mukundansundar yes of course - sorry I didn't get around to helping you any more with the conformance tests!

**Pull request closed without merging**
