### PR TITLE
graphql binding variable support

### PR DESCRIPTION
**Pull request by serpentfabric**
# Description
previous pr: #2522; rebased against master so couldn't re-open previous pr

attempt to idiomatically add support for graphql variables in the bindingrequest's metadata to help prevent injection attacks as outlined in https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#injection-prevention

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2517

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#3165

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]
LGTM

**Comment by ItalyPaleAle** [comment]
LGTM thanks for this contribution! Please don't forget to update the Dapr docs too

**Comment by serpentfabric** [comment]
fyi: we had to add one more commit because the rebase against 1.11 had a bug with the binding init

**Review by ItalyPaleAle — DISMISSED** [review]

**Comment by serpentfabric** [comment]
> LGTM thanks for this contribution! Please don't forget to update the Dapr docs too

dapr/docs#3285

**Comment by serpentfabric** [comment]
sorry we missed it earlier but we had to make one more commit to appease the linter.

**Comment by ItalyPaleAle** [comment]
> one more commit to appease the linter

Isn't that always the case 🙃

Thanks for fixing the linter issues

**Pull request merged**
