### PR TITLE
Add Redis binding certification tests

### PR DESCRIPTION
**Pull request by yash-nisar**
Closes https://github.com/dapr/components-contrib/issues/1939

Signed-off-by: Yash Nisar <yashnisar@microsoft.com>

# Description
Add Redis binding certification tests

## Issue reference
https://github.com/dapr/components-contrib/issues/1939
We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/1939

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by berndverst — CHANGES_REQUESTED** [review]
What about the many metadata option documented here? https://docs.dapr.io/reference/components-reference/supported-bindings/redis/#spec-metadata-fields

See the redis state store certification test for inspiration on how to do some of these tests.

**Comment by berndverst** [comment]
Add `replace github.com/dapr/dapr => github.com/1046102779/dapr v1.5.2-0.20220829014128-56ac94bfadd1AA` to your `go.mod` and run `go mod tidy`

**Comment by yash-nisar** [comment]
> What about the many metadata option documented here? https://docs.dapr.io/reference/components-reference/supported-bindings/redis/#spec-metadata-fields
> 
> See the redis state store certification test for inspiration on how to do some of these tests.

1. I looked at the state store example, that also doesn't have most of the listed options there. That's mainly because most of them are timeouts/pool/connection related which can't be tested. So I tried to cover all the possible cases but if you think I've missed any, let me know and I will try to cover it
2. I spent a lot of time trying to figure out the cluster mode but I landed on the same error as https://github.com/dapr/components-contrib/issues/1909 so I guess we have no choice but to wait until that issue is fixed

**Comment by yash-nisar** [comment]
> Add `replace github.com/dapr/dapr => github.com/1046102779/dapr v1.5.2-0.20220829014128-56ac94bfadd1AA` to your `go.mod` and run `go mod tidy`

Done. The current test failures (i.e. cassandra certification) are unrelated to my changes.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
