### PR TITLE
The subscribeRequest and PublishRequest both need Metadata.

### PR DESCRIPTION
**Pull request by cvictory**
# Description

The subscribeRequest and PublishRequest both need Metadata.

## Issue reference

https://github.com/dapr/dapr/issues/2495

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by jjcollinge** [comment]
Related: https://github.com/dapr/dapr/issues/2379

**Comment by cvictory** [comment]
> Related: [dapr/dapr#2379](https://github.com/dapr/dapr/issues/2379)

ok. I will close pr. 
thanks.

**Comment by yaron2** [comment]
Wait, don't close just yet. This PR adds metadata to the Publisher quest, which wasn't covered by the related PR. Is that correct @jjcollinge?

**Comment by jjcollinge** [comment]
@yaron2 yes we still need this work to add `PublishRequest` - I've only updated `SubscriptionRequest`  in [my pr](https://github.com/dapr/dapr/pull/2464/files). This PR can extend that one.

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by yaron2** [comment]
Thanks for your contribution @cvictory

**Pull request merged**
