### PR TITLE
Implements getLabelFromMetadata Fixing #2062

### PR DESCRIPTION
**Pull request by cmendible**
# Description

Current implementation only returns values for a key when the label == `*`

This PR fixes such behavior by implementing `getLabelFromMetadata` function,

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_2062_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by pravinpushkar — DISMISSED** [review]
With this change get a single key seems to work fine.

**Review by ItalyPaleAle — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
@cmendible please make a docs PR to document the request metadata option for the label.

**Comment by cmendible** [comment]
> @cmendible please make a docs PR to document the request metadata option for the label.

Would a metadata or label section in this following page work? 

https://github.com/dapr/docs/blob/v1.9/daprdocs/content/en/reference/components-reference/supported-configuration-stores/azure-appconfig-configuration-store.md 

or a metadata section in the api docs?

https://github.com/dapr/docs/blob/v1.9/daprdocs/content/en/reference/api/configuration_api.md

cc @berndverst

**Comment by berndverst** [comment]
> https://github.com/dapr/docs/blob/v1.9/daprdocs/content/en/reference/components-reference/supported-configuration-stores/azure-appconfig-configuration-store.md

I think that would be the right place. Probably needs a new section for per request metadata (as opposed to component metadata).

**Pull request merged**
