### PR TITLE
aws sqs: Use implicit creds and region by default, explicit if specified

### PR DESCRIPTION
**Pull request by trondhindenes**
# Description
This PR adjusts the sqs binding so that it supports implicit credentials and region config. I've described the problem in more detail in #339. Once this PR is merged, all components using aws services should be updated to similar logic. Once the docs repo support separating between optional and required config variables, we can indicate that access key/secret and region are optional but not required.

The functionality of this PR can be tested by sending environment vars into dapr stand-alone instead of configuring the region, access key id and secret access key variables, or by using a local aws profile if configured:

`AWS_PROFILE=myprofile dapr run ...`

or

`AWS_ACCESS_KEY_ID=123 AWS_SECRET_ACCESS_KEY=abc AWS_REGION=eu-west-1 dapr run ...`

## Issue reference

#_339_ (is this the correct format? Maybe fix the PR template?)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:
* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@trondhindenes thanks, this is great!

in order to not duplicate the logic here, can you move it to a new dir at the root of the repo so that all AWS components can reference it from there?

`authentication/aws/aws.go`

The `getClient` method could become `GetClient(accessKey, secretKey, region string)`

**Comment by trondhindenes** [comment]
Good idea. I will certainly try! Not a go dev but ill give it an honest try.

**Comment by trondhindenes** [comment]
@yaron2 I think I've done that now :-)

**Comment by yaron2** [comment]
So the linter is failing because in Go you shouldn't use an underscore in a package name.

Can you restructure like this?

`/authentication/aws/aws.go`.

And then the package name in `aws.go` is `aws`.

Inside the SQS code, you can create an alias: `aws_auth github.com/dapr-components-contrib/authentication/aws`

**Comment by trondhindenes** [comment]
oh nice. Will try that. Again, I'm a total golang newb so I appreciate the pointers :-)

**Comment by yaron2** [comment]
Alright, we are almost done. Seems like your IDE does not do `goimports`.

Open your terminal, and run `goimports bindings/aws/sqs/sqs.go`

Take the formatted output and replace it in `sqs.go`.

**Comment by trondhindenes** [comment]
yup, I think I have the build nailed down now. Thanks for the patience :-)

**Comment by trondhindenes** [comment]
thanks! I'd be happy to PR the docs change but as mentioned I think there's a need for a "standard way" of separating required from optional parameters, now that access key/secret id/region are optional in some situations.

**Pull request merged**
