### PR TITLE
Add bulk get in state store  - Plan B

### PR DESCRIPTION
**Pull request by skyao**
# Description

Add BulkGet method on state store.

This Pr is for Plan B:

- Adding BulkGet method on state store which will return (bool, response, error)

- Dapr will calls BulkGet method first

    * if store supports BulkGet, it will return true with resposne list
    * if store doesn't support BulkGet, it will return false with nil response; dapr need to fallback to call get method one by one

## Issue reference

https://github.com/dapr/dapr/issues/2368

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@skyao there are lint errors, they appear in the `Files Changed` tab.

**Comment by skyao** [comment]
@yaron2 Please help to review this. We are planning to use dapr state api (including bulk get/save/delete) to integrate with our internal k-v store now. I need to make bulk get/save/delete work.

**Comment by yaron2** [comment]
> @yaron2 Please help to review this. We are planning to use dapr state api (including bulk get/save/delete) to integrate with our internal k-v store now. I need to make bulk get/save/delete work.

Sure thing, it will get reviewed in the coming days.

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
