### PR TITLE
pin latest dapr/dapr in cert tests

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

pin latest dapr/dapr in cert tests

### CODE REVIEW

**Comment by berndverst** [comment]
Currently one of the certification tests fail. This is due to a change in dapr/dapr that passes through all headers.

@halspang is working on a PR to sanitize the gRPC protocol headers causing problems. Once that PR is merged in dapr/dapr I will update this PR to update the cert tests.

**Comment by berndverst** [comment]
Conformance: https://github.com/dapr/components-contrib/actions/runs/3103255309
Certification: https://github.com/dapr/components-contrib/actions/runs/3103255298

**Review by mukundansundar — APPROVED** [review]
Lgtm

**Pull request merged**
