### PR TITLE
Implement new bindings component for Huawei OBS

### PR DESCRIPTION
**Pull request by jasonlica**
# Description

Huawei OBS is implemented as an output bindings component into the Dapr. This can be a counterpart to the existing AWS S3 bindings component.

[Object Storage Service (OBS)](https://www.huaweicloud.com/intl/en-us/product/obs.html) provides stable, secure, efficient, and easy-to-use cloud storage that lets you store virtually any volume of unstructured data in any format and access it from anywhere using REST APIs.

See [Huawei OBS User Guide](https://support.huaweicloud.com/intl/en-us/productdesc-obs/en-us_topic_0045853681.html?utm_source=cce_Growth_map&utm_medium=display&utm_campaign=help_center&utm_content=Growth_map) for reference.

I will provide the documentation for this component usage later and will raise a PR for that when the PR for this component is being approved.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1718

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#2436

### CODE REVIEW

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
We need to check why the FOSSA license check is failing before we can merge this PR. I did see that the upstream library is Apache 2.0 so it should not be a concern.

**Comment by berndverst** [comment]
@jasonlica please open the documentation PR for this component and link that PR here. We will only merge this PR after the documentation PR has been opened. Thanks!

**Comment by berndverst** [comment]
@jasonlica can you please also address the conflict in the `go.mod`?

**Comment by jasonlica** [comment]
> @jasonlica can you please also address the conflict in the `go.mod`?

@berndverst resolved the conflict. please review, thanks.

**Review by berndverst — APPROVED** [review]

**Comment by jasonlica** [comment]
> > @jasonlica please open the documentation PR for this component and link that PR here. We will only merge this PR after the documentation PR has been opened. Thanks!
> 
> @berndverst sure, I will create the documentation PR for this component. thanks.

@berndverst I have created documentation for this component and linked the PR in the above description. thanks.

**Comment by berndverst** [comment]
Thanks for your contribution @jasonlica

**Comment by jasonlica** [comment]
> Thanks for your contribution @jasonlica

@berndverst it is our pleasure! thanks to the community.

**Pull request merged**
