### PR TITLE
Fix bulk get from gcp secret store

### PR DESCRIPTION
**Pull request by pravinpushkar**
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/5320

### CODE REVIEW

**Comment by pravinpushkar** [comment]
Changes are not tested yet. I have test it with gcp resource

**Comment by pravinpushkar** [comment]
> Changes are not tested yet. I have test it with gcp resource

I have verified the changes.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
Approved

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
@ItalyPaleAle this doesn't get automerged because at the time the PR was opened there was another workflow that failed (Fossa). I find that the APIs "mergeable" state doesn't update correctly when a workflow is removed.

**Comment by berndverst** [comment]
@ItalyPaleAle ha, and suddenly it worked :)

**Pull request merged**
