### PR TITLE
Introduce oracle database state store component

### PR DESCRIPTION
**Pull request by lucasjellema**
# Description

This PR introduces a State Store component backed by Oracle Database (including OCI Autonomous Database service). The code is implemented following the example of the PostgreSQL state store component - with Oracle Database specific SQL and connection method & driver.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1444

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation / Created issue in the https://github.com/dapr/docs/issues/2109

### CODE REVIEW

**Comment by lucasjellema** [comment]
I seem to be stuck at the go.sum check in CI. I do not know how to get a go.sum file that is acceptable to the CI process.

I have cloned the master branch, ran `go mod tidy` then `make go.mod check-diff`. This already shows differences. 

I have then updated the go.mod on the master branch with the changes required for the new component, ran `go mod tidy` again can copied the resulting go.sum and go.mod to my branch. After running tests and linting I have pushed the change. However, this still does not result in an accepted go.sum. 

Does anyone have suggestions as to how to resolve this?

**Comment by daixiang0** [comment]
@lucasjellema try remove `go.sum` then run `go mod tidy`, and make sure your Go version is same as CI's.

**Comment by lucasjellema** [comment]
I have become so much entangled in the go.sum file issues that I have decided to create a brand new, fresh PR (#1454 ) and close this one off

**Comment by lucasjellema** [comment]
> @lucasjellema try remove `go.sum` then run `go mod tidy`, and make sure your Go version is same as CI's.

Thanks, will do. I am on 1.17.5 and I noticed CI is (now) on 1.17.6. Was that a recent change (that I should have been aware of)?

**Comment by lucasjellema** [comment]
> > @lucasjellema try remove `go.sum` then run `go mod tidy`, and make sure your Go version is same as CI's.
> 
> Thanks, will do. I am on 1.17.5 and I noticed CI is (now) on 1.17.6. Was that a recent change (that I should have been aware of)?

Unfortunately, I can see no difference in the results and the check is still failing - even on files I have not touched (such as /tests/certification/state/sqlserver/go.sum and /tests/certification/secretstores/azure/keyvault/go.sum). I really do not have a good handle on what is going on.

**Pull request closed without merging**
