### PR TITLE
Refactors all state store to standardize metadata parsing

### PR DESCRIPTION
**Pull request by berndverst**
# Description

This relates to the larger theme of #2014 which is about defining component metadata.

Standardizes all state store component metadata definitions. Now all component metadata is obtained via the helper method `metadata.DecodeMetadata(input interface{}, result interface{}) error`

Additionally, this decoding function was updated to properly handle string arrays, and additionally to use our `isTruthy` function by default when converting from string to `bool` or `*bool`.

The state store interface now has a function `GetComponentMetadata() map[string]string` which returns a map of metadata fields with their respective types. This honors the `mapstructure` tag overrides.

Under the hood the following internal helper function is used to traverse a struct to list struct fields and tags:
`metadata.GetMetadataInfoFromStructType(t reflect.Type, metadataMap *map[string]string) error`

Please note:
For metadata parsing to work correctly all struct fields must be exported!

### CODE REVIEW

**Comment by berndverst** [comment]
Let's see whether I broke any conformance or certification tests... This is my first run :)

**Comment by berndverst** [comment]
Ah.. because I modified the interface it seems I need to update certification tests!

**Comment by berndverst** [comment]
FYI Re ran the eventhubs bindings test above

**Review by artursouza — APPROVED** [review]

**Comment by berndverst** [comment]
In a few cases I added new metadata, such as the ability to set the tableName instead of the default `dapr`. This needs to be documented. (Postgres is an example)

**Pull request merged**
