### PR TITLE
Update couchbaselabs/jsonx for meeting compliance

### PR DESCRIPTION
**Pull request by shubham1172**
Signed-off-by: Shubham Sharma <shubhash@microsoft.com>

# Description

Earlier couchbase/gocb.v1 depended on couchbaselabs/jsonx@v1.0.0 which did not have a license. This PR upgrades to couchbaselabs/jsonx@v1.0.1 which has an Apache license.

## Issue reference

Please reference the issue this PR will close: #1480

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* (NA) Created/updated tests
* (NA) Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Please update conflicting files.

**Comment by shubham1172** [comment]
@daixiang0, done!

**Review by mukundansundar — APPROVED** [review]
LGTM

**Pull request merged**
