### PR TITLE
remove etcd state store to prepare to update grpc to new version

### PR DESCRIPTION
**Pull request by skyao**
# Description

Remove etcd state store temporarily to prepare to update grpc to new version.

## Issue reference

https://github.com/dapr/dapr/issues/2101

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@skyao the EventHubs pub/sub component is now fixed.

Also, please run `go mod tidy` (make sure you are using Go 1.14+) and push the changes.

**Comment by skyao** [comment]
> @skyao the EventHubs pub/sub component is now fixed.
> 
> Also, please run `go mod tidy` (make sure you are using Go 1.14+) and push the changes.

Done.

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by skyao** [comment]
@yaron2 please help to merge. Other PR are blocked by this.

**Review by youngbupark — APPROVED** [review]

**Comment by yaron2** [comment]
@skyao thanks, this is merged.

**Pull request merged**
