### PR TITLE
Update amqp091-go to fix memory issues

### PR DESCRIPTION
**Pull request by arturotrenard**
… consumption problems have been resolved. And break the package.

# Description

This update is important because from version v1.7.0 to v1.8.1 memory consumption problems have been resolved. And break the package.

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thanks for this! https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work

Can you please fix the DCO issue?

**Comment by ItalyPaleAle** [comment]
Also, as you re-submit this, please also run `make modtidy-all` in the tree

**Comment by ItalyPaleAle** [comment]
> Thanks for this! https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work
> 
> Can you please fix the DCO issue?

DCO is still failing so I can't merge this sadly :( Please re-do this and when you make a commit, use the `-s` flag. Such as `git commit -s`

**Comment by arturotrenard** [comment]
> > Thanks for this! https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work
> > Can you please fix the DCO issue?
> 
> DCO is still failing so I can't merge this sadly :( Please re-do this and when you make a commit, use the `-s` flag. Such as `git commit -s`

**Comment by arturotrenard** [comment]
> > Thanks for this! https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work
> > Can you please fix the DCO issue?
> 
> DCO is still failing so I can't merge this sadly :( Please re-do this and when you make a commit, use the `-s` flag. Such as `git commit -s`

I should already

**Comment by ItalyPaleAle** [comment]
> > > Thanks for this! https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work
> > > Can you please fix the DCO issue?
> > 
> > 
> > DCO is still failing so I can't merge this sadly :( Please re-do this and when you make a commit, use the `-s` flag. Such as `git commit -s`
> 
> I should already

It still appears as failing. You can see here: https://github.com/dapr/components-contrib/pull/2927/checks?check_run_id=14450199282

**Comment by berndverst** [comment]
You need to run `make modtidy-all` and commit all the modified `go.sum` and `go.mod` files.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by berndverst** [comment]
By the way, the the replace directive you removed was actually used. This was an indirect dependency which was unlicensed, and therefore had to be force replaced with a licensed version. Otherwise our project cannot be released as Apache 2.0

**Pull request merged**
