### PR TITLE
Fix GCP storage bucket binding authentication issue

### PR DESCRIPTION
**Pull request by shubham1172**
# Description

Fixed a typo in JSON tag that was causing authentication to fail.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3012

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
Thanks @shubham1172 !

I think this should be cherry-picked into 1.12 too? @berndverst

**Comment by shubham1172** [comment]
> @shubham1172 the cert tests for GCP comps are still failing

Pubsub and State tests seem to be failing, however should be track that separately? This PR solves the GCP storage bucket binding issue.

**Review by yaron2 — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
> > @shubham1172 the cert tests for GCP comps are still failing
> 
> Pubsub and State tests seem to be failing, however should be track that separately @ItalyPaleAle? This PR solves the GCP storage bucket binding issue.

Ok, will you be looking into that? We'll need it for 1.12 I suppose

**Comment by shubham1172** [comment]
> > > @shubham1172 the cert tests for GCP comps are still failing
> > 
> > 
> > Pubsub and State tests seem to be failing, however should be track that separately @ItalyPaleAle? This PR solves the GCP storage bucket binding issue.
> 
> Ok, will you be looking into that? We'll need it for 1.12 I suppose

Sure, I can do that!

**Comment by shubham1172** [comment]
@ItalyPaleAle FYI created this to track certification tests failure https://github.com/dapr/components-contrib/issues/3129

**Comment by berndverst** [comment]
The cert test failure is independent - I think credentials have expired or something. It's oauth issues in the GCP components.

**Pull request merged**
