### PR TITLE
mDNS round robin

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description
Support multiple app instances for a single standalone app id and support round robin load balancing across them.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #514 
## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by jjcollinge** [comment]
@yaron2 be interested to get your thoughts on this implementation. I've tested it load balancing across 3 instances of an app running on the same host. As it's DNS based load balancing rather than HTTP, we don't immediately remove an instance when it dies - we have to wait for the record to expire and then it'll be removed from the cache. As long as the client app handles retries and the TTL is set short enough then you should be able to handle it ok without issue - the alternative is to setup additional health probes on the TCP connections but not sure if that's needed yet. It's a basic round robin selection - no guarantees of linear iteration but best effort.

**Comment by jjcollinge** [comment]
Marked as ready for review - might require some further optimizations though. I could potentially move the refresh browse to use an aggregate channel that is triggered periodically by a timer but when a new app id is seen we could also push on to it to invoke a browse. This would help reduce the time the first address needs to serve all the traffic before we discovery the rest of the addresses on the next periodic refresh.

**Comment by yaron2** [comment]
> @yaron2 I marked this as ready for review - might require some further optimizations though. I could potentially move the refresh browse to use an aggregate channel that is triggered periodically by a timer but when a new app id is seen we could also push on to it to invoke a background browse. This would help reduce the time the first address needs to serve all the traffic before we discovery the rest of the addresses on the next periodic refresh.

This is a great PR, thanks for this. I will take you up on your suggestion here to reduce the the load on the first address. Otherwise LGTM

**Comment by jjcollinge** [comment]
Great, I'll update it tomorrow.

**Comment by yaron2** [comment]
> Great, I'll update it tomorrow.

Hey @jjcollinge can you update on status?

**Comment by jjcollinge** [comment]
Added a few small tweaks, moved the periodic refresh and on demand refresh into separate goroutines and added a test for multi instance resolution.
Below is an annotated log of the behavior with 3 instances.
```
-----> cache miss for nodeapp
time="2020-12-11T12:39:06.7823523Z" level=debug msg="no mDNS address found in cache, browsing network for app id nodeapp" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> browsing for first address for nodeapp
time="2020-12-11T12:39:06.782441Z" level=debug msg="Browsing for first mDNS address for app id nodeapp" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> first address response
time="2020-12-11T12:39:06.7831921Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7832855Z" level=debug msg="Adding IPv4 address 172.18.122.57:32933 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> second address response before context canceled (timing issue)
time="2020-12-11T12:39:06.7833477Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7833761Z" level=debug msg="Adding IPv4 address 172.18.122.57:39509 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> canceled context for first browse, returning first address
time="2020-12-11T12:39:06.783411Z" level=debug msg="mDNS browse for app id nodeapp canceled." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7833782Z" level=debug msg="Browsing for first mDNS address for app id nodeapp canceled." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> browsing in the background for additional addresses
time="2020-12-11T12:39:06.7835878Z" level=debug msg="Refreshing mDNS addresses for app id nodeapp." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> 3 addresses found and updated in the cache
time="2020-12-11T12:39:06.784582Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7846663Z" level=debug msg="Adding IPv4 address 172.18.122.57:39509 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7847201Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7847498Z" level=debug msg="Adding IPv4 address 172.18.122.57:33169 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.7849449Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:06.785008Z" level=debug msg="Adding IPv4 address 172.18.122.57:32933 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> background browse for nodeapp is complete
time="2020-12-11T12:39:09.783909Z" level=debug msg="mDNS browse for app id nodeapp timed out." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:09.7839255Z" level=debug msg="Refreshing mDNS addresses for app id nodeapp timed out." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> requests using cache instead of network (3 addresses)
time="2020-12-11T12:39:09.8743938Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:33169" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:10.8998285Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:32933" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:11.9073923Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:39509" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:12.9147956Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:33169" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
...
-----> periodic address refresh
time="2020-12-11T12:39:32.9066904Z" level=debug msg="Refreshing all mDNS addresses." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9076436Z" level=debug msg="0 IPv4 address(es) expired for app id nodeapp." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9078358Z" level=debug msg="Refreshing mDNS addresses for app id nodeapp." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9098287Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9100533Z" level=debug msg="Adding IPv4 address 172.18.122.57:39509 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9101868Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9102767Z" level=debug msg="Adding IPv4 address 172.18.122.57:32933 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9126753Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:32.9127463Z" level=debug msg="Adding IPv4 address 172.18.122.57:33169 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> requests using cache instead of network  (3 addresses)
time="2020-12-11T12:39:33.0905654Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:39509" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:34.0999252Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:33169" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:39:35.1060245Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:32933" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
...

-----> periodic address refresh
time="2020-12-11T12:40:38.9112973Z" level=debug msg="Refreshing all mDNS addresses." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> removing expired address
time="2020-12-11T12:40:38.9113967Z" level=debug msg="1 IPv4 address(es) expired for app id nodeapp." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:38.9114984Z" level=debug msg="Refreshing mDNS addresses for app id nodeapp." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:38.9115953Z" level=debug msg="Refreshing mDNS addresses for app id ." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:38.9125806Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:38.9127029Z" level=debug msg="Adding IPv4 address 172.18.122.57:32933 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:38.9127468Z" level=debug msg="mDNS response for app id nodeapp received." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:38.9127739Z" level=debug msg="Adding IPv4 address 172.18.122.57:39509 for app id nodeapp cache entry." app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge

-----> requests using cache instead of network  (2 addresses)
time="2020-12-11T12:40:42.5462129Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:32933" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:43.5562793Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:39509" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:44.5647068Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:32933" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:45.5748102Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:39509" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
time="2020-12-11T12:40:46.5920692Z" level=debug msg="found mDNS IPv4 address in cache: 172.18.122.57:32933" app_id=appid instance=DESKTOP-RD1N225 scope=dapr.contrib type=log ver=edge
```

**Review by yaron2 — APPROVED** [review]
This will be tested thoroughly. I'm confident to merge this now for local service invocations.

**Pull request merged**
