### PR TITLE
[Release-1.10 -- optional] Backport azure sdks to 1.10

### PR DESCRIPTION
**Pull request by berndverst**
Backport Stable Azure SDKs from release-1.11 to 1.10 without adding new features not present in 1.10.

cherry-pick 009548d
cherry-pick 7c005d134a1205b5d721ea54bf54193fae366094
cherry-pick 4b01912b0f19881d1e7bffad440fe96e85ece776
cherry-pick 8cc74c7
cherry-pick 3a616c5
cherry-pick a3b424e69b8317f194c51b27b9b665639a27bbb1
cherry-pick 04d1e71ce796333b24c2a89da43a9505188c2fe5
cherry-pick 8c7ae10

### CODE REVIEW

**Comment by berndverst** [comment]
See cockroachdb test in action runs.

**Comment by berndverst** [comment]
Linter failure does not appear real - in this branch `make lint` passes. This must be due to the workflow running out of master branch.

**Comment by DeepanshuA** [comment]
> Linter failure does not appear real - in this branch `make lint` passes. This must be due to the workflow running out of master branch.

I also checked out this branch locally. And, linter passes.
This latest run also passed: https://github.com/dapr/components-contrib/actions/runs/4991242936/jobs/8937469283

But, some certification tests failed in latest cert test run: https://github.com/dapr/components-contrib/actions/runs/4991242875/jobs/8937470423

Let me try to trigger Cert tests again, to verify if these are flaky or persistent failures.

**Comment by DeepanshuA** [comment]
> > Linter failure does not appear real - in this branch `make lint` passes. This must be due to the workflow running out of master branch.
> 
> I also checked out this branch locally. And, linter passes. This latest run also passed: https://github.com/dapr/components-contrib/actions/runs/4991242936/jobs/8937469283
> 
> But, some certification tests failed in latest cert test run: https://github.com/dapr/components-contrib/actions/runs/4991242875/jobs/8937470423
> 
> Let me try to trigger Cert tests again, to verify if these are flaky or persistent failures.

It seems some cert tests fail randomly, specifically eventhubs one.

**Comment by ItalyPaleAle** [comment]
> It seems some cert tests fail randomly, specifically eventhubs one.

Some tests can fail when there are parallel tests running at the same time. One day we should fix that  :)

**Pull request closed without merging**
