### PR TITLE
upgrade vmware-go-kcl to v1.5.0

### PR DESCRIPTION
**Pull request by taojwmware**
Signed-off-by: Tao Jiang <taoj@vmware.com>

# Description

_Please explain the changes you've made_
Upgrade vmware-go-kcl dependency to the latest v1.5.0.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1231

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by taojwmware** [comment]
The build failed on ci-lint:
```run golangci-lint
  Running [/home/runner/golangci-lint-1.31.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  Error: SA1019: ptypes.MarshalAny is deprecated: Call the anypb.New function instead.  (staticcheck)
  Error: SA1019: ptypes.MarshalAny is deprecated: Call the anypb.New function instead.  (staticcheck)
  Error: SA1019: ptypes.MarshalAny is deprecated: Call the anypb.New function instead.  (staticcheck)
  Error: SA1019: ptypes.UnmarshalAny is deprecated: Call the any.UnmarshalTo method instead.  (staticcheck)
  Error: SA1019: package github.com/golang/protobuf/ptypes is deprecated: Well-known types have specialized functionality directly injected into the generated packages for each message type. See the deprecation notice for each function for the suggested alternative.  (staticcheck)
  
  Error: issues found
  Ran golangci-lint in 233888ms
```
All of them come from:
```
./state/cloudstate/cloudstate_crdt.go:				a, _ := ptypes.MarshalAny(&resp)
./state/cloudstate/cloudstate_crdt.go:				a, _ := ptypes.MarshalAny(&e)
./state/cloudstate/cloudstate_crdt.go:				a, _ := ptypes.MarshalAny(&e)
./state/cloudstate/cloudstate_crdt.go:					err := ptypes.UnmarshalAny(vAny, &saveState)
```

**Comment by taojwmware** [comment]
The build failed on ci-lint:
```
run golangci-lint
  Running [/home/runner/golangci-lint-1.31.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  Error: SA1019: ptypes.MarshalAny is deprecated: Call the anypb.New function instead.  (staticcheck)
  Error: SA1019: ptypes.MarshalAny is deprecated: Call the anypb.New function instead.  (staticcheck)
  Error: SA1019: ptypes.MarshalAny is deprecated: Call the anypb.New function instead.  (staticcheck)
  Error: SA1019: ptypes.UnmarshalAny is deprecated: Call the any.UnmarshalTo method instead.  (staticcheck)
  Error: SA1019: package github.com/golang/protobuf/ptypes is deprecated: Well-known types have specialized functionality directly injected into the generated packages for each message type. See the deprecation notice for each function for the suggested alternative.  (staticcheck)
  
  Error: issues found
  Ran golangci-lint in 233888ms
```
It is caused by calling deprecated function in:
```
./state/cloudstate/cloudstate_crdt.go:				a, _ := ptypes.MarshalAny(&resp)
./state/cloudstate/cloudstate_crdt.go:				a, _ := ptypes.MarshalAny(&e)
./state/cloudstate/cloudstate_crdt.go:				a, _ := ptypes.MarshalAny(&e)
./state/cloudstate/cloudstate_crdt.go:					err := ptypes.UnmarshalAny(vAny, &saveState)
```

**Comment by taojwmware** [comment]
@daixiang0

**Review by CodeMonkeyLeet — COMMENTED** [review]
Given the update to `github.com/aws/aws-sdk-go` version, that's probably causing the linter to flag existing issues in components that are rebuilt.

It does also suggest that all AWS components should be retested, as there's not significant test automation for them.

**Comment by beiwei30** [comment]
@taojwmware would you mind to sync from the latest master branch and resolve the conflict? I have time to review your change in this week.

**Review by beiwei30 — APPROVED** [review]
LGTM

**Review by beiwei30 — CHANGES_REQUESTED** [review]
but the lint check fails, you may need to consider to downgrade `protobuf` to check if it passes CI.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
