### PR TITLE
Fix Azure KeyVault secretstore BulkGet URI parsing of the GetSecretsComplete response

### PR DESCRIPTION
**Pull request by tcnghia**
# Description
Fix Azure KeyVault secretstore BulkGet URI parsing of the GetSecretsComplete response to make it works with URI of form `{vaultURI}/secrets/{itemID}` in the GetSecretsComplete response.

## Issue reference

Please reference the issue this PR will close: #655 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by tcnghia** [comment]
/assign @mukundansundar @cmendible 

Please do not merge until code freeze is lifted. We will get this in after Milestone 3.

**Comment by tcnghia** [comment]
failing test seems unrelated, probably flakey

**Review by cmendible — CHANGES_REQUESTED** [review]
Instead of doing the double trim you can add in line 89 (before the loop) something like:

``` go
secretIDPrefix := fmt.Sprintf("%s%s", vaultURI, secretItemIDPrefix)
```

and then just:

``` go
secretName := strings.TrimPrefix(*secretItem.ID, secretIDPrefix)
```

**Comment by tcnghia** [comment]
> Instead of doing the double trim you can add in line 89 (before the loop) something like:
> 
> ```go
> secretIDPrefix := fmt.Sprintf("%s%s", vaultURI, secretItemIDPrefix)
> ```
> 
> and then just:
> 
> ```go
> secretName := strings.TrimPrefix(*secretItem.ID, secretIDPrefix)
> ```

I don't know enough about the history of Azure KeyVault API to know if this URL format has been always like this. If previously the BulkGet works, then probably at some point the URL format was different.

Do you know if there is official documentation regarding the current URL format? Otherwise, I think we may be best backward compatible with the previous format as well, which the doubly `TrimPrefix` will offer.

**Comment by cmendible** [comment]
> > Instead of doing the double trim you can add in line 89 (before the loop) something like:
> > 
> > ```go
> > secretIDPrefix := fmt.Sprintf("%s%s", vaultURI, secretItemIDPrefix)
> > ```
> > 
> > and then just:
> > 
> > ```go
> > secretName := strings.TrimPrefix(*secretItem.ID, secretIDPrefix)
> > ```
> 
> I don't know enough about the history of Azure KeyVault API to know if this URL format has been always like this. If previously the BulkGet works, then probably at some point the URL format was different.
> 
> Do you know if there is official documentation regarding the current URL format? Otherwise, I think we may be best backward compatible with the previous format as well, which the doubly `TrimPrefix` will offer.
> 
> 
> 
> 

The sufix is specified here: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#object-types

I made a mistake with a stash on my side that never made it to the repo so I'm positive that the current implementation didn't work 😟. The API hasn't changed.

**Comment by tcnghia** [comment]
> > > Instead of doing the double trim you can add in line 89 (before the loop) something like:
> > > ```go
> > > secretIDPrefix := fmt.Sprintf("%s%s", vaultURI, secretItemIDPrefix)
> > > ```
> > > 
> > > 
> > > and then just:
> > > ```go
> > > secretName := strings.TrimPrefix(*secretItem.ID, secretIDPrefix)
> > > ```
> > 
> > 
> > I don't know enough about the history of Azure KeyVault API to know if this URL format has been always like this. If previously the BulkGet works, then probably at some point the URL format was different.
> > Do you know if there is official documentation regarding the current URL format? Otherwise, I think we may be best backward compatible with the previous format as well, which the doubly `TrimPrefix` will offer.
> 
> The sufix is specified here: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates#object-types
> 
> I made a mistake with a stash on my side that never made it to the repo so I'm positive that the current implementation didn't work 😟. The API hasn't changed.

@cmendible Thanks. Addressed the feedback as suggested.

**Review by cmendible — APPROVED** [review]
LGTM

**Review by mukundansundar — APPROVED** [review]
lgtm

**Review by artursouza — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
