### PR TITLE
read record header as metadata if available in kafka

### PR DESCRIPTION
**Pull request by mukundansundar**
Signed-off-by: Mukundan Sundararajan <65565396+mukundansundar@users.noreply.github.com>

# Description

read the record headers if available and set it as metadata for the event in Kafka.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2016 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by mukundansundar** [comment]
I have locally verified this change. Now in the process of writing certification tests for the same.

**Comment by mukundansundar** [comment]
@berndverst @ItalyPaleAle @yaron2 I think we need to verify proper metadata processing on subscribe, so I am thinking of adding that assertion capability to the cert test framework. Any thoughts or issues on that?

**Comment by ItalyPaleAle** [comment]
I am not an expert on Kafka. @skyao ?

**Comment by berndverst** [comment]
> @berndverst @ItalyPaleAle @yaron2 I think we need to verify proper metadata processing on subscribe, so I am thinking of adding that assertion capability to the cert test framework. Any thoughts or issues on that?

Please find a Kafka expert to review this. @skyao or @pkedy or others.

**Comment by mukundansundar** [comment]
certification tests cannot be written for this change since certification tests depend on go-sdk gRPC event and the TopicEvent defined in go-sdk does not provide any way to access metadata for event. Additionally metadata is not completely propagated in gRPC also ... see https://github.com/dapr/dapr/issues/3642 for more discussion ...

**Comment by mukundansundar** [comment]
@dapr/approvers-components-contrib Please review PR.

**Comment by mukundansundar** [comment]
The test that is being expected is not related to this change.

**Review by berndverst — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Pull request merged**
