### PR TITLE
Update to Zeebe 1.3.3 and add missing tests

### PR DESCRIPTION
**Pull request by akkie**
# Description

This pull request updates the Zeebe client to version 1.3.3 and it also implements missing e2e tests.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by akkie** [comment]
Does anyone know why the build fails? Is there anything I can do to fix that?

**Comment by yaron2** [comment]
> Does anyone know why the build fails? Is there anything I can do to fix that?

This is the output, looks like the gcp secretmanager test fails:

```
FAIL: TestInit (0.00s)
    --- FAIL: TestInit/Init_with_Wrong_metadata (0.00s)
        secretmanager_test.go:32: 
            	Error Trace:	secretmanager_test.go:32
            	Error:      	Expected nil, but got: &errors.errorString{s:"failed to setup secretmanager client: google: could not parse key: private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: syntax error: truncated tag or length"}
            	Test:       	TestInit/Init_with_Wrong_metadata
FAIL
```

I would try to run this test locally and see why it fails.

**Comment by yaron2** [comment]
@akkie we now need to sign off our commits, please see here: https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md#how-to-add-sign-offs-retroactively.

**Comment by akkie** [comment]
@yaron2 I have signed off the commit. The issue with the failing test doesn't come from my code. Can it be the case that `go mod tidy` will pull some new components that will cause this issue? How can I avoid that?

**Comment by akkie** [comment]
Closed in favour of #1473

**Pull request closed without merging**
