### PR TITLE
deps: updates wazero to 1.0.0-pre.6

### PR DESCRIPTION
**Pull request by codefromthecrypt**
# Description

This updates [wazero](https://wazero.io/) to [1.0.0-pre.6](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.6).

Notably, v1.0.0-pre.6:
* improves module compilation and initialization performance

While not used yet here, if someone asks for filesystem writes, it is now possible due to these features.
* adds `writefs.NewDirFS` which lets you add new files.
  * `path_open` `O_CREAT` flags, `path_remove_directory` `path_rename` `path_unlink_file`
* adds `NewFilesystemLoggingListenerFactory` with dramatically improved logging.

This also includes changes described in [1.0.0-pre.5](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.5).

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [n/a] Created/updated tests
* [n/a] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
At this point, let us not open more PRs for more pre-release versions of this. I will merge this one, but no further wazero updates for this Dapr 1.10 release. Ideally let us wait for the actual 1.0.0+ release.

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
Unfortunately I have to revert this PR. Dapr/Dapr doesn't compile on Linux ARM (in dapr/dapr) because of this version of this dependency @codefromthecrypt

**Comment by codefromthecrypt** [comment]
@berndverst yeah this is one reason we've been doing updates as folks are trying to finish syscall support for wasi.

1.0.0-pre.7 sorted out 386, as we found out trivy was compiling linux/386. I'll try to figure out what dapr/dapr is compiling as I thought I also tried arm when fixing that. whatever it is, I'll add it to our pre-check workflow. Thanks for the feedback!

**Comment by berndverst** [comment]
@codefromthecrypt 

```
../../../go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-pre.6/internal/syscallfs/dirfs.go:92:9: cannot use atimeSec (variable of type int64) as type int32 in struct literal
```

```
../../../go/pkg/mod/github.com/tetratelabs/wazero@v1.0.0-pre.6/internal/platform/stat_linux.go:13:9: cannot use atime.Sec (variable of type int32) as type int64 in return statement
```

Those are the main error signatures.

**Comment by berndverst** [comment]
It fails when compiling with:
`CGO_ENABLED=0 GOOS=linux GOARCH=arm go build  -ldflags="-X`

**Comment by berndverst** [comment]
I will try `v1.0.0-pre.7`

**Pull request merged**
