### PR TITLE
Added vaultToken support

### PR DESCRIPTION
**Pull request by DarqueWarrior**
# Description

Adds support for vaultToken to hashicorp vault secret component. The original file based option is also still supported.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #794

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#1355

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
Please let me know what we need to get this one across the line. There are customers needing this change.

**Comment by Taction** [comment]
I'm also using vault, and agree with that. There is a suggestion: if `tokenMountPath` is set just load its value in the `Init` function(return err if encountered), and pass it to `v.vaultToken`. And the function `readVaultToken() (string, error)` can be moved now, instead just use `v.vaultToken`.

**Review by pkedy — APPROVED** [review]

**Comment by pkedy** [comment]
@DarqueWarrior I approved this PR before I saw there were conflicts. Please resolve those. Also, @Taction has a great suggestion, but since it is beyond the scope of this PR, I'll leave it to you to decide. Just know that if you make the change, I now have context on this PR to be able to approve it quickly.

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
@DarqueWarrior Please, resolve conflicts.

**Review by pkedy — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Pull request merged**
