### PR TITLE
Implement a new state store component for the Huawei DCS

### PR DESCRIPTION
**Pull request by jasonlica**
# Description

The Huawei DCS is implemented as a dapr state store component, and it wraps the existing Redis state store implementation.

The [Distributed Caching Service (DCS)](https://www.huaweicloud.com/en-us/product/dcs.html) is a Huawei's cloud version of Redis. It is an online, distributed, in-memory cache service compatible with Redis on Huawei Cloud infrastructure, which is reliable, scalable, usable out of the box, and easy to manage, meeting your requirements for high read/write performance and fast data access.

See [Huawei DCS User Guide](https://support.huaweicloud.com/en-us/productdesc-dcs/dcs-pd-200713001.html) for reference.

I will provide the documentation for this component usage later (similar to the [setup-redis.md](https://github.com/dapr/docs/blob/v1.6/daprdocs/content/en/reference/components-reference/supported-state-stores/setup-redis.md)) and will raise a PR for that when the PR for this component is being approved.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_1596_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
I will raise a PR for the documentation and will add an issue number here later.

### CODE REVIEW

**Comment by jasonlica** [comment]
Hi, I noticed that one of the checks failed in the CI, which says the "top level comment should end in a period". But, since this is the first time contribution to the Dapr, I am not sure what is the next step? should I fix this? I didn't get this kind of complaint when I run `make lint` in my local env.

**Comment by yaron2** [comment]
> Hi, I noticed that one of the checks failed in the CI, which says the "top level comment should end in a period". But, since this is the first time contribution to the Dapr, I am not sure what is the next step? should I fix this? I didn't get this kind of complaint when I run `make lint` in my local env.

Yes, you should do as the PR linter instructs. Thanks for your contribution!

**Comment by jasonlica** [comment]
> Yes, you should do as the PR linter instructs. Thanks for your contribution!

I am not able to reproduce these linting errors when I run `make lint` locally (in windows env). Could you please give me some guidance on how to spot those linting errors as It would help me to ensure no linting errors before I push any code changes in the future? thanks.

**Comment by jasonlica** [comment]
> > Yes, you should do as the PR linter instructs. Thanks for your contribution!
> 
> I am not able to reproduce these linting errors when I run `make lint` locally (in windows env). Could you please give me some guidance on how to spot those linting errors as It would help me to ensure no linting errors before I push any code changes in the future? thanks.
> 
> **Update**: @yaron2 I don't even get any linting errors (specifically for this component) on linux env.

Just to give you some information about my linux environment, following is the **ubuntu** dev machine where I did a quick test and checked for linting errors:
`Linux karthick-dev 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jasonlica** [comment]
> > > > Yes, you should do as the PR linter instructs. Thanks for your contribution!
> > > 
> > > 
> > > I am not able to reproduce these linting errors when I run `make lint` locally (in windows env). Could you please give me some guidance on how to spot those linting errors as It would help me to ensure no linting errors before I push any code changes in the future? thanks.
> > > **Update**: @yaron2 I don't even get any linting errors (specifically for this component) on linux env.
> > 
> > 
> > Just to give you some information about my linux environment, following is the **ubuntu** dev machine where I did a quick test and checked for linting errors: `Linux karthick-dev 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
> 
> Are you using golint 1.31.0?

No, following are the go and golint versions which I am using in both platforms:
| Env | Go | Golint |
| ------ | ------ | ------ |
| Linux (Ubuntu | go version go1.18 linux/amd64 | golangci-lint has version 1.45.2 built from 8bdc4d3f on 2022-03-24T11:51:26Z |
| Windows | go version go1.17.2 windows/amd64 | golangci-lint has version 1.43.0 built from 861262b7 on 2021-11-03T11:57:46Z |

**Comment by daixiang0** [comment]
Golangci-lint is not backward compatible, so you need to use the same version, then will get the same result.

**Comment by jasonlica** [comment]
> Golangci-lint is not backward compatible, so you need to use the same version, then will get the same result.

Pushed the changes with the fix for those linting errors (identified after I have downgraded the golint versrion to 1.31.0). Hope it should get through the failed check now.

**Comment by yaron2** [comment]
@jasonlica lint passes! however there's a couple of tests failing.

**Comment by jasonlica** [comment]
> @jasonlica lint passes! however there's a couple of tests failing.

Yes, those two tests cases (related to [TestInit](https://github.com/jasonlica/components-contrib/blob/9d673cf3071792b7e21ea590dd9ee80135366a57/state/huawei/dcs/dcs_test.go#L75)) are expected to fail when there is no redis instance setup in the environment.

I was taking the Redis state store as a reference for this component implementation, but I don't see any test cases written for the _Init()_ in the `redis_test.go`. Also, it seems to be bit complicated to mock the actual _Init()_ for unit testing. However, to keep the test coverage high,  I added those test cases which use the local redis instance for testing purpose.

Not sure whether it is really important to give a solution at this stage (ie., to mock _Init()_ to keep the test cases passed), otherwise, I will probably comment out those two test cases for the time being.

**Comment by berndverst** [comment]
Why is this PR and new component even necessary? If Huawei DCS is just Redis, can't we just update the Redis component if that is even necessary?

Also Huawei can just document which Huawai DCS settings correspond to which Redis settings. This really seems unnecessary to me because all this is does is mapping different metadata keys to existing redis options.

FYI @yaron2 @artursouza

**Comment by berndverst** [comment]
This PR is identical to the way the Redis component behaves except that it maps:

"dcsHost" to "redisHost" and "dcsPassword" to "redisPassword"

That does not warrant a new component. This can just be explained in documentation...

**Comment by yaron2** [comment]
Ping @jasonlica

**Comment by jasonlica** [comment]
Hey, @yaron2 @daixiang0 @daixiang,  

Since all checks have passed, could you guys help approve and merge it.  Thx

**Comment by yaron2** [comment]
@jasonlica please see the comment from maintainer @berndverst above.

**Comment by berndverst** [comment]
> Hey, @yaron2 @daixiang0 @DaiXiang,
> 
> Since all checks have passed, could you guys help approve and merge it. Thx

Please address my questions and concerns as mentioned before. https://github.com/dapr/components-contrib/pull/1628#issuecomment-1093393481

I'm one of the 3 maintainers of Component Contrib and I currently am against merging this PR as there is no technical justification for this component.

**Comment by jasonlica** [comment]
@berndverst @yaron2 

Thanks for your comments. 

Redis is a caching server which is not a Cloud Services.  It doesn't come with multi-tenant/instance etc. cloud related concept. It didn't have a way of specifying as cloud instance, and the cloud service specific attributes.  When a cloud console (e.g. Huawei DCS) is used, there are no way of differentiating between the Huawei DCS service instance and tenant. 

Even though in current commit, we don't actually use  instanceName, instanceId, projectId properties, when it comes to real business scenarios, those Huawei DCS specific  properties  (i.e. instancdID, project ID, vpcID etc)will be required.

Thanks for your understanding.

**Comment by yaron2** [comment]
> @berndverst @yaron2
> 
> Thanks for your comments.
> 
> Redis is a caching server which is not a Cloud Services. It doesn't come with multi-tenant/instance etc. cloud related concept. It didn't have a way of specifying as cloud instance, and the cloud service specific attributes. When a cloud console (e.g. Huawei DCS) is used, there are no way of differentiating between the Huawei DCS service instance and tenant.
> 
> Even though in current commit, we don't actually use instanceName, instanceId, projectId properties, when it comes to real business scenarios, those Huawei DCS specific properties (i.e. instancdID, project ID, vpcID etc)will be required.
> 
> Thanks for your understanding.

Thanks for the explanation. Why not include the usage for these specific properties in the current commit? It would make perfect sense to accept this PR.

**Comment by jasonlica** [comment]
> > @berndverst @yaron2
> > Thanks for your comments.
> > Redis is a caching server which is not a Cloud Services. It doesn't come with multi-tenant/instance etc. cloud related concept. It didn't have a way of specifying as cloud instance, and the cloud service specific attributes. When a cloud console (e.g. Huawei DCS) is used, there are no way of differentiating between the Huawei DCS service instance and tenant.
> > Even though in current commit, we don't actually use instanceName, instanceId, projectId properties, when it comes to real business scenarios, those Huawei DCS specific properties (i.e. instancdID, project ID, vpcID etc)will be required.
> > Thanks for your understanding.
> 
> Thanks for the explanation. Why not include the usage for these specific properties in the current commit? It would make perfect sense to accept this PR.

Thanks @yaron2 .  

As Dapr docs is stored in another independent rep, we are planning to push another PR (like other Dapr components) to dapr/docs repo to explain and illustrate the usage Huawei DCS (especially for those Huawei Cloud specific DCS properties). 

Let me know if you still have any  other quesitons. Thanks for your help. 

Dapr Docs Repo:  https://github.com/dapr/docs
Dapr Docs Website: https://docs.dapr.io/reference/components-reference/supported-state-stores/

**Comment by berndverst** [comment]
@jasonlica I still don't understand.

The optional metadata fields are never used. The existing redis state store component you are calling unmarshals the metadata into a struct which has specific metadata fields it supports - your fields like `VPCId` are not supported there. So the Redis component isn't using this information or passing it on to Redis when creating a Redis client.

Similarly in your PR you never use the `dcsMetadata` struct at all after parsing the component metadata.

This means the DCS specific fields are never used anywhere and this component doesn't add any new functionality which does not exist in the existing Redis component.

If your goal is for your Redis Cache server to receive requests with the additional metadata field this PR does not currently do that.

@yaron2 please also take a look. Until the optional DCS fields are actually passed to Redis (they aren't in this PR) I do not think we should be merging this PR and adding this component.

@jasonlica once you update your PR to also send the optional DCS metadata fields I am happy to review again and approve this PR at this time. Currently this major aspect of your PR is completely missing.

**Comment by jasonlica** [comment]
Thx @berndverst . will update PR to reflect DCS specifc metadata usage. (currently on vacation)

**Comment by jasonlica** [comment]
@berndverst , @yaron2 , I understand your concerns where we have those Huawei DCS specific metadata fields which are kept unused other than those `dcsHost` and `dcsPassword` which are mapped to the respective Redis host and password fields. And, those metadata fields are just loaded into the DCS component even though they are not required for establishing a connection.

We have been evaluating number of use cases within Huawei which are very specific in nature and they require DCS specific attributes, such as, `instanceId`, `projectId`, etc. For example, query for the Huawei DCS instance once an application is deployed with a dapr sidecar and a DCS state store component into the Huawei Cloud's (K8s) env. And, in this particular scenario, we will be able to make use of the Dapr CRD endpoint to retrieve those DCS component metadata fields via the following URL exposed in the KubeApi server:

```
root@dapr-test-01313:~# kubectl get components
NAME         AGE
dcsstore     18h
statestore   20h
root@dapr-test-01313:~#
```

`apis/dapr.io/v1alpha1/namespaces/default/components/dcsstore`

Even though, it is completely possible to leverage the native Dapr Redis component for connecting to the Huawei DCS, we wouldn't be able to use it for the special use cases like above. Besides, we will have more flexibility if we have our own DCS component with its specific attributes as we continue to evaluate potential business use cases within Huawei. We will continue to evolve the DCS component in the future as we find more use cases in Huawei, and this component contribution could be a great beginning for that.

By the way, even though this is our first Huawei component contribution to the community, we will soon contributing a Dapr bindings component for the [Huawei OBS](https://www.huaweicloud.com/intl/en-us/product/obs.html).

**Comment by jasonlica** [comment]
> > @berndverst , @yaron2 , I understand your concerns where we have those Huawei DCS specific metadata fields which are kept unused other than those `dcsHost` and `dcsPassword` which are mapped to the respective Redis host and password fields. And, those metadata fields are just loaded into the DCS component even though they are not required for establishing a connection.
> > We have been evaluating number of use cases within Huawei which are very specific in nature and they require DCS specific attributes, such as, `instanceId`, `projectId`, etc. For example, query for the Huawei DCS instance once an application is deployed with a dapr sidecar and a DCS state store component into the Huawei Cloud's (K8s) env. And, in this particular scenario, we will be able to make use of the Dapr CRD endpoint to retrieve those DCS component metadata fields via the following URL exposed in the KubeApi server:
> > ```
> > root@dapr-test-01313:~# kubectl get components
> > NAME         AGE
> > dcsstore     18h
> > statestore   20h
> > root@dapr-test-01313:~#
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `apis/dapr.io/v1alpha1/namespaces/default/components/dcsstore`
> > Even though, it is completely possible to leverage the native Dapr Redis component for connecting to the Huawei DCS, we wouldn't be able to use it for the special use cases like above. Besides, we will have more flexibility if we have our own DCS component with its specific attributes as we continue to evaluate potential business use cases within Huawei. We will continue to evolve the DCS component in the future as we find more use cases in Huawei, and this component contribution could be a great beginning for that.
> > By the way, even though this is our first Huawei component contribution to the community, we will soon contributing a Dapr bindings component for the [Huawei OBS](https://www.huaweicloud.com/intl/en-us/product/obs.html).
> 
> Thanks for the explanation @jasonlica, and we appreciate the effort and contributions Huawei are making to Dapr. It's very problematic for us as maintainers who need to ensure constant testing, maintenance, compliance and certification for components to accept non-functional changes to a component.
> 
> For the use case you specified, please know that you can use your own custom metadata on any Dapr component today without any issues..
> 
> If you put a `dcsHost` metadata property on the existing Redis component, you would still be able to get it's value with mentioned `kubectl` command.

Thanks @yaron2 for the information. I will close this PR and the respective proposal #1596.

**Pull request closed without merging**
