### PR TITLE
Remove required checks from SES metadata

### LINKED ISSUE #2698: AWS SES components require secretKey and accessKey
## Expected Behavior

When I create a component like this: 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ses
spec:
  type: bindings.aws.ses
  version: v1
  metadata:
  - name: emailFrom
    value: "myacc@myemail.com"
```

From the documentation if I am using AWS IAM I should not add accessKey and secretKey. 

```
Important
When running the Dapr sidecar (daprd) with your application on EKS (AWS Kubernetes), if you’re using a node/pod that has already been attached to an IAM policy defining access to AWS resources, you must not provide AWS access-key, secret-key, and tokens in the definition of the component spec you’re using.
```

## Actual Behavior

At the moment I am receiving this error
```
[INIT_COMPONENT_FAILURE]: initialization error occurred for ses (bindings.aws.ses/v1): SES binding error: region, accessKey or secretKey fields are required in metadata"
```

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by cciobanu98**
# Description

I am not a GO developer, but from my understanding this should fix this issues, other components related to AWS does not have this check, only this one. If there it's a reason for this. I will decline this PR. 

## Issue reference

Should fix #2698 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
@robertojrojas  can you please take a look too?

**Comment by robertojrojas** [comment]
@ItalyPaleAle Code changes look good, but I'd like to try the changes locally. I won't have time until tomorrow or over the weekend.

**Comment by ItalyPaleAle** [comment]
Thanks, @robertojrojas ! Please approve this PR when you're able to confirm things work, and I'll merge following your approval :)

**Comment by berndverst** [comment]
Will wait for @robertojrojas to verify this.

**Comment by robertojrojas** [comment]
@ItalyPaleAle I just tested the code changes and it worked for me.  Just a reminder that the [Bindings AWS SES docs](https://github.com/dapr/docs/blob/v1.10/daprdocs/content/en/reference/components-reference/supported-bindings/ses.md) need to be updated to reflect the changes made.

**Comment by berndverst** [comment]
@cciobanu98 should complete this docs issue: https://github.com/dapr/docs/issues/3292

**Review by berndverst — APPROVED** [review]

**Comment by yaron2** [comment]
Thanks for this contribution @cciobanu98

**Pull request merged**
