### PR TITLE
update logger form nats-io's to dapr's

### PR DESCRIPTION
**Pull request by abserari**
# Description

update logger form nats-io's to dapr's

## Issue reference

https://github.com/dapr/components-contrib/issues/448
Please reference the issue this PR will close: #448 

## Checklist
don't need to change the doc and test.

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
Hey @abserari, please do the following:

1. Make sure you are using Go 1.15
2. Run `go mod tidy` and push the changes

**Comment by abserari** [comment]
```bash
ArideMacBook-Air:~ abser$ go version
go version go1.15.1 darwin/amd64
```

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
To pull this version into Dapr, run go get -u github.com/dapr/components-contrib@master

**Comment by abserari** [comment]
> To pull this version into Dapr, run go get -u github.com/dapr/components-contrib@master

Great！ I just need it

**Pull request merged**
