### PR TITLE
[WIP] Add memcached state store

### PR DESCRIPTION
**Pull request by daft300punk**
# Description
Adds memcached as state store

## Issue reference
https://github.com/dapr/components-contrib/issues/61

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
Can you run `go mod vendor` and push the changes?

**Comment by daft300punk** [comment]
> Can you run `go mod vendor` and push the changes?
Done.

Can someone point out where the corresponding documentation changes are to be made? I'll make a PR for it. Thanks.

**Comment by yaron2** [comment]
Are we good to merge?

**Comment by yaron2** [comment]
Add memcached to here:

https://github.com/dapr/components-contrib/blob/master/state/Readme.md

**Comment by daft300punk** [comment]
Yes, it can be merged if review is ok.

**Comment by yaron2** [comment]
Thanks for this!

**Pull request merged**
