### PR TITLE
deps: upgrade tidwall/gjson

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

# Description

Fix [CVE](https://deps.dev/advisory/GoVuln/GO-2021-0054).

## Issue reference

Please reference the issue this PR will close: #979

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by pkedy — DISMISSED** [review]
LGTM

**Comment by yaron2** [comment]
@daixiang0 please resolve the conflicts.

**Comment by daixiang0** [comment]
@yaron2 done.

**Review by artursouza — DISMISSED** [review]

**Comment by yaron2** [comment]
@daixiang0 please resolve conflicts and we can merge.

**Comment by daixiang0** [comment]
@yaron2 done.

**Review by yaron2 — APPROVED** [review]

**Pull request merged**
