### PR TITLE
Add Redis StateStore Certification Tests

### PR DESCRIPTION
**Pull request by DeepanshuA**
Signed-off-by: Deepanshu Agarwal <deepanshu.agarwal1984@gmail.com>

# Description

Adding Redis Certification test as per Test plan https://github.com/dapr/components-contrib/issues/1534#issuecomment-1094705065

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1534 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by berndverst — CHANGES_REQUESTED** [review]
You will also add your tests to the certification workflow here:
https://github.com/dapr/components-contrib/blob/master/.github/workflows/certification.yml#L55

And please note that this workflow will not actually run on this PR, so the fact that tests pass on this PR means nothing -- your certification tests are not being run.

A reviewer will need to manually run your PR to verify.

**Comment by skyao** [comment]
@DeepanshuA You can run the cert test on your forked repo like what I do as this page: 

https://github.com/skyao/components-contrib/actions/workflows/certification.yml

You can run it on your branch:

Screen Shot 2022-05-27 at 11 01 44

**Comment by skyao** [comment]
@DeepanshuA you need to update the workflow files in your PR to add your cert test case into the github action

This is also an example from my PR (yes, I'm adding cert test for kakfa bindings now):

Screen Shot 2022-05-27 at 11 04 16

https://github.com/dapr/components-contrib/pull/1758/files#diff-d519a9b910e45c00725de9beec3fbc97be24eaf1586c66943a17b7908b115f1c

**Comment by DeepanshuA** [comment]
thanks @berndverst  and @skyao, I was able to run successfully the redis certification test on my fork:

https://github.com/DeepanshuA/components-contrib/runs/6623705548?check_suite_focus=true

**Comment by artursouza** [comment]
@DeepanshuA , please, resolve conflicts.

**Comment by DeepanshuA** [comment]
> @DeepanshuA , please, resolve conflicts.

Hi @artursouza , I had resolved conflicts

**Review by berndverst — APPROVED** [review]

**Pull request merged**
