### PR TITLE
Implement E2E tests for the Zeebe binding

### PR DESCRIPTION
**Pull request by akkie**
# Description

This PR implements E2E tests for the Zeebe binding.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by akkie** [comment]
@pkedy Would be great if you could give some early feedback if this goes in the right direction.

**Comment by pkedy** [comment]
@akkie You've got some linter errors breaking the build but this look like its structured well. You've got a README and docker compose for running it which is great.

**Comment by akkie** [comment]
@pkedy Do you have a suggestion how I can resolve the issue regarding the global variables. 
```
`ZeebeVersion` is a global variable (gochecknoglobals)
```

I would like to share them between the tests.

**Comment by akkie** [comment]
I have created a getter for the environment variables to fix the global lint issue. I have also created a new entry in the makefile to run the tests from CI. I have not created a new workflow for E2E tests, because I'm not sure if each test should run separate or if it makes sense to create a shell script that runs all the E2E tests.

From my perspective the PR is finished and can be reviewed.

**Review by pkedy — APPROVED** [review]
LGTM! Thanks for doing this!

**Comment by yaron2** [comment]
@akkie please resolve conflicts and we can merge.

**Comment by akkie** [comment]
@yaron2 Done

**Pull request merged**
