### PR TITLE
Fix JetStream conformance tests

### PR DESCRIPTION
**Pull request by Jarema**
# Description

* Fixed conformance tests.
* Added JetStream Docker compose image

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
Fix DCO: https://docs.dapr.io/contributing/contributing-overview/#developer-certificate-of-origin-signing-your-work

To add your Signed-off-by line to every commit in this branch:

Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~2 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin fix-jetstream-conformance-tests

**Review by berndverst — CHANGES_REQUESTED** [review]
To automatically run the test you need one more line in the `conformance.yml`

You'll want to list `pubsub.jetstream` in the long list of tests to run (do the same thing as for `kubemq` pubsub)

**Comment by berndverst** [comment]
Is this something you will still work on at some point? Just checking :)

**Comment by Jarema** [comment]
Ah no, this has been superseeded by #2376 . 
I fixed the test in the other PR :)

**Pull request closed without merging**
