### PR TITLE
Update dapr/kit

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Migrates metadata decoding utils to dapr/kit, as well as IsTruthy

### CODE REVIEW

**Review by berndverst — APPROVED** [review]
Wish you had added the original authors of the migrated code as coauthors.

**Review by berndverst — CHANGES_REQUESTED** [review]
So I resolved a merge conflict here and made sure to keep latest dapr/dapr and latest go sdk. But that appears to not work with your PR.

**Comment by ItalyPaleAle** [comment]
This needs an updated Go SDK: https://github.com/dapr/go-sdk/pull/469

**Comment by ItalyPaleAle** [comment]
Should be fixed now

**Review by berndverst — APPROVED** [review]

**Pull request merged**
