### PR TITLE
feature/pulsar: add producer option disableBatching

### PR DESCRIPTION
**Pull request by 1046102779**
solved DCO.

https://github.com/dapr/components-contrib/pull/1397

### CODE REVIEW

**Comment by mukundansundar** [comment]
@1046102779 why is this same as #1397 ?

**Comment by mukundansundar** [comment]
can #1397 be closed since this is open?

**Comment by 1046102779** [comment]
> can #1397 be closed since this is open?

yes, thanks.

**Comment by mukundansundar** [comment]
@1046102779 Add a docs issue for this.

**Review by mukundansundar — DISMISSED** [review]
lgtm

**Comment by 1046102779** [comment]
> @1046102779 Add a docs issue for this.

ok.

**Review by daixiang0 — DISMISSED** [review]

**Review by artursouza — DISMISSED** [review]

**Review by msfussell — APPROVED** [review]

**Comment by daixiang0** [comment]
@1046102779 please fix CI issues.

**Comment by daixiang0** [comment]
@1046102779 please fix conflicts.

**Review by daixiang0 — COMMENTED** [review]
@1046102779 please fix conflicts.

LGTM overall.

**Comment by daixiang0** [comment]
@1046102779  please fix conflicts.

**Comment by 1046102779** [comment]
compile error: `Error: Process completed with exit code 2.`

how to solved it?

**Comment by mukundansundar** [comment]
@1046102779 Can you run `make modtidy-all`?

**Comment by 1046102779** [comment]
> @1046102779 Can you run `make modtidy-all`?

thanks. Use `make modtidy-all` command to solve this error.

**Review by daixiang0 — APPROVED** [review]

**Pull request merged**
