### PR TITLE
Re-enabling the failing GCP tests

### PR DESCRIPTION
**Pull request by elena-kolevska**
Re-enables the GCP tests that were disabled because they were failing.

This PR should be merged only after https://github.com/dapr/components-contrib/pull/3169 is merged into master.

### CODE REVIEW

**Comment by elena-kolevska** [comment]
Thanks for merging https://github.com/dapr/components-contrib/pull/3169 @ItalyPaleAle  🙏 . This one is now unblocked for merging too.

**Comment by ItalyPaleAle** [comment]
> This one is now unblocked for merging too.

It is not, or at least not yet. #3169 was merged into release-1.12 so it's not in the master branch yet.

**Comment by elena-kolevska** [comment]
Oh, indeed! :) Sorry, I mixed it up.

**Pull request merged**
