### PR TITLE
Add a New Log Storage component

### PR DESCRIPTION
**Pull request by RcXu**
# Description

This is a Log Storage component for a Multi Language System，such as Nodejs as GW and Java apply the services and so on. If need a middleware to format and store the info、debug or trace log across the different Language service, it's useful.
Now the component only supports the alicloud SLS. LogHub,LogShipper and ELK storage plat are in plain.

# Issues
https://github.com/dapr/docs/issues/2592

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thanks for the contribution @RcXu !

This is not just a new component, but a new building block. Normally, before we can introduce new building blocks, we strongly suggest having a discussion in https://github.com/dapr/dapr/ and review this with other maintainers and especially STC members. Has any discussion taken place already?

**Comment by berndverst** [comment]
A new building block cannot be created without discussion among the steering committee and maintainers.
Additionally the interface for the new building block must first be created in dapr/dapr.

Please rewrite this component as a Binding or State Store. If neither of those approaches work for you then this PR needs to be closed or abandoned.

As is, on behalf of @dapr/maintainers-components-contrib I **do not approve**.

**Review by berndverst — CHANGES_REQUESTED** [review]
This must be rewritten as a state store or binding, or this PR should be abandoned.

No log storage component exists today and PRs in contrib are not the right away to introduce a new building block component.

**Comment by RcXu** [comment]
> Thanks for the contribution @RcXu !
> 
> This is not just a new component, but a new building block. Normally, before we can introduce new building blocks, we strongly suggest having a discussion in https://github.com/dapr/dapr/ and review this with other maintainers and especially STC members. Has any discussion taken place already?

Thks very much, I get this, I willl choice a  way to rewrite this component .

**Comment by RcXu** [comment]
> A new building block cannot be created without discussion among the steering committee and maintainers. Additionally the interface for the new building block must first be created in dapr/dapr.
> 
> Please rewrite this component as a Binding or State Store. If neither of those approaches work for you then this PR needs to be closed or abandoned.
> 
> As is, on behalf of @dapr/maintainers-components-contrib I **do not approve**.

Thks very mush,I get it, I will rewrite it.

**Pull request closed without merging**
