### PR TITLE
bindings: support rabbitmq send any content types

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long <long0dai@foxmail.com>

# Description

Support rabbitmq binding send any content types.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1144

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#1798

### CODE REVIEW

**Comment by daixiang0** [comment]
@pkedy @artursouza kindly ask review.

**Review by CodeMonkeyLeet — APPROVED** [review]
LGTM.

Per the PR template, can you also make sure that you add an issue to dapr/docs to make sure that the use of the new `contentType` metadata is documented in https://docs.dapr.io/reference/components-reference/supported-bindings/rabbitmq/?

**Comment by daixiang0** [comment]
@CodeMonkeyLeet thanks for tip, added.

@artursouza @yaron2 please review again.

**Review by CodeMonkeyLeet — APPROVED** [review]
LGTM

**Review by artursouza — APPROVED** [review]

**Pull request merged**
