### PR TITLE
Recreate AEH Processor in the event of an error before retrying the processing operation

### PR DESCRIPTION
**Pull request by MattCosturos**
Recreate AEH Processor in the event of an error before retrying the processing operation

# Description

Moved the creation and setup of the Azure Event Hub Processor inside the main loop. 
The processor.run only returns a non-recoverable error. Therefore we must re-create new processor and setup the subscription.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3573 
## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
See failing tests

**Comment by MattCosturos** [comment]
Line 280, can I simply log the error and return nil?
or do we need to return that error out of the goroutine and back up the stack?

**Comment by yaron2** [comment]
@artursouza for last review

**Review by artursouza — APPROVED** [review]

**Comment by marcduiker** [comment]
@holopin-bot @MattCosturos Thank you!

**Pull request merged**
