### PR TITLE
feature(validation): add validation for dynamic metadata

### PR DESCRIPTION
**Pull request by 1046102779**
Signed-off-by: 1046102779 <seachen@tencent.com>

# Description

All components should strictly verify dynamic metadata. For unknown keys in yaml or metadata passed in from  dapr runtime api, errors should be intercepted to avoid unexpected result.

## Issue reference

Please reference the issue this PR will close: #_[[5040](https://github.com/dapr/dapr/issues/5040)]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
I think this is a good addition, but have you seen this issue? https://github.com/dapr/components-contrib/issues/2014 @berndverst  and I have been working on a new proposal for “component metadata” and I’m going to open the first PR today. That will also include some information about what metadata is required and what kind of fields are expected (strings, numbers, enums…)

The current proposal does NOT include runtime validation like your PR. However, I think perhaps your PR could be built on top of the “component metadata” to leverage the same data?

**Comment by 1046102779** [comment]
> I think this is a good addition, but have you seen this issue? #2014 @berndverst and I have been working on a new proposal for “component metadata” and I’m going to open the first PR today. That will also include some information about what metadata is required and what kind of fields are expected (strings, numbers, enums…)
> 
> The current proposal does NOT include runtime validation like your PR. However, I think perhaps your PR could be built on top of the “component metadata” to leverage the same data?

Thanks. @ItalyPaleAle .

 I will check if the current Issue or PR has similar content before apply an Issue or PR next time. This way I can also discuss directly on the issue.

**Comment by ItalyPaleAle** [comment]
If you have feedback on the design please provide it on that issue too!

**Comment by berndverst** [comment]
This kind of change should not have been made without a proposal issue being raised and discussed / approved by all maintainers first.

I will close this issue at this time because there is no approved proposal that this PR is based on.

**Pull request closed without merging**
