### PR TITLE
pubsub.snssqs: Support regions in other AWS partitions

### LINKED ISSUE #1907: aws sqs component can not support  China region such as cn-northwest-1
### I create  sqs component  and  set correct  sqs config info . 
when  I pub message  by the component  ,I hope it work well ,but the daprd output error message as below.

## Actual Behavior

image

## Steps to Reproduce the Problem

If I set  cn-northwest-1 to the region,   it will connect error，maybe cn-north-1 also have the same  problem。

I found  the source code   on buildARN  function   in snssqs.go  .  

### return fmt.Sprintf("arn:aws:%s:%s:%s:%s", serviceName, s.metadata.Region, s.metadata.accountID, entityName)

 If region is  cn-*,the arn  should start with   arn:aws-cn 

### return fmt.Sprintf("arn:**aws-cn**:%s:%s:%s:%s", serviceName, s.metadata.Region, s.metadata.accountID, entityName)

image
snssqs.go 
image

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by clareliguori**
Fixes #1907

Signed-off-by: Clare Liguori <liguori@amazon.com>

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by yaron2 — APPROVED** [review]

**Review by mukundansundar — COMMENTED** [review]
@clareliguori Please add docs for this change ...

**Comment by berndverst** [comment]
Will only merge once a docs PR has been created.

**Comment by clareliguori** [comment]
@mukundansundar @berndverst I don't think a docs update is needed here. This doesn't change the component format, it just determines the partition ID based on the current metadata.

**Comment by yaron2** [comment]
@clareliguori is correct, this PR doesn't introduce any changes to metadata or the existing format.

**Comment by berndverst** [comment]
Sounds good. I was going off of @mukundansundar 's review. Agreed and understood that no docs are required.

**Pull request merged**
