### PR TITLE
Add appId to consul default checks

### PR DESCRIPTION
**Pull request by alberthuang24**
fix https://github.com/dapr/components-contrib/issues/2489

Signed-off-by: AlbertHuang r.albert.huang@gmail.com

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
Is this a breaking change?

**Comment by berndverst** [comment]
@alberthuang24 can you please merge the latest dapr/components-contrib@master into this PR?

**Comment by ItalyPaleAle** [comment]
I am still not a fan of this approach. How about just changing Consul to de-register the service (if present) before registering a new one? https://pkg.go.dev/github.com/hashicorp/consul/api@v1.19.0#Agent.ServiceDeregister

**Comment by berndverst** [comment]
> I am still not a fan of this approach. How about just changing Consul to de-register the service (if present) before registering a new one? https://pkg.go.dev/github.com/hashicorp/consul/api@v1.19.0#Agent.ServiceDeregister

That does sound better.

**Comment by ItalyPaleAle** [comment]
I've done a bunch of work on this and looks like the solution of un-registering the service wouldn't work either, because that removes all instances of the service.

I now agree with @alberthuang24 this may be the best approach to fix the issue.

**Comment by alberthuang24** [comment]
> @alberthuang24 can you please merge the latest dapr/components-contrib@master into this PR?

I rebase the latest master branch and will continue to resolve https://github.com/dapr/dapr/pull/5868 when this PR is merged

**Comment by alberthuang24** [comment]
@ItalyPaleAle Hi, Can this PR be merged?

**Comment by ItalyPaleAle** [comment]
@alberthuang24 please see the comments here: https://github.com/dapr/dapr/pull/5868

We're asking for a small change, then we can merge this and the PR in dapr/dapr

**Pull request closed without merging**
