### PR TITLE
ci: enable godot

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

# Description

Enable godot linter.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
ping @yaron2

**Comment by daixiang0** [comment]
ping @pkedy @artursouza

**Review by artursouza — APPROVED** [review]

**Comment by CodeMonkeyLeet** [comment]
@daixiang0 Can this PR be closed as being superseded by #1102?

**Comment by daixiang0** [comment]
@CodeMonkeyLeet go ahead!

**Pull request closed without merging**
