### PR TITLE
Create component metadata for pubsub.redis

### PR DESCRIPTION
**Pull request by MregXN**
Signed-off-by: MregXN <mregxn@gmail.com>

# Description

Create component metadata for pubsub.redis

## Issue reference

Please reference the issue [#2580](https://github.com/dapr/components-contrib/issues/2580) and [#2014](https://github.com/dapr/components-contrib/issues/2014).

### CODE REVIEW

**Comment by berndverst** [comment]
Thanks for doing this.

Please also double check that all of these options are included:
https://github.com/dapr/components-contrib/blob/master/internal/component/redis/settings.go#L24
https://github.com/dapr/components-contrib/blob/master/pubsub/redis/metadata.go#L20

**Comment by MregXN** [comment]
> Thanks for doing this.
> 
> Please also double check that all of these options are included. The Dapr documentation (docs.dapr.io) might be missing some options. https://github.com/dapr/components-contrib/blob/master/internal/component/redis/settings.go#L24 https://github.com/dapr/components-contrib/blob/master/pubsub/redis/metadata.go#L20

Hi Bernd, the options in those files have been included in current commit. Thanks for reminding.

**Review by berndverst — APPROVED** [review]

**Comment by yaron2** [comment]
@MregXN why did you close this PR?

**Comment by MregXN** [comment]
> @MregXN why did you close this PR?

Fork repo is deleted by mistake and recovery is in progress.  Sorry for confusing.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
