### PR TITLE
Merge changes from release-1.9 into master [DO NOT SQUASH]

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Merges back changes made in release-1.9 into master, and fixes merge conflicts in Service Bus

**Please do not squash**

### CODE REVIEW

**Comment by berndverst** [comment]
`Error: s.activeMessagesChan undefined (type *Subscription has no field or method activeMessagesChan) (typecheck)`

**Comment by ItalyPaleAle** [comment]
Should be fixed now

**Comment by berndverst** [comment]
> Should be fixed now

@ItalyPaleAle DCO

**Comment by ItalyPaleAle** [comment]
@berndverst DCO fails because it's a merge PR. Nothing I can do there or I'd overwrite history.

Please don't squash this!

**Review by berndverst — APPROVED** [review]

**Pull request merged**
