### PR TITLE
Use message's retain property to cover meta's

### PR DESCRIPTION
**Pull request by SpikeWong**
Signed-off-by: spike <hello@spike.wiki>

# Description

MQTT pubsub to offer metadata for retained messages

## Issue reference
#2317 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by SpikeWong** [comment]
Do I need create a mock mqtt server/client to assert the published retain property

**Comment by DeepanshuA** [comment]
LGTM. Will it be possible to add a UT for it?

**Comment by berndverst** [comment]
> Do I need create a mock mqtt server/client to assert the published retain property

Yes please do that, that would be ideal @SpikeWong.

**Review by berndverst — CHANGES_REQUESTED** [review]
Add unit test to verify the interaction between component metadata, request metadata etc

**Comment by SpikeWong** [comment]
> Add unit test to verify the interaction between component metadata, request metadata etc

finished

**Comment by berndverst** [comment]
LGTM - thanks!

Can you also update the documentation for MQTT in Dapr to explain this message / request metadata property "retain"? Otherwise nobody can find that we support his.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
