### PR TITLE
Fix lint failure for openai binding

### PR DESCRIPTION
**Pull request by shivam-51**
# Description

This PR fixes some linting errors that is causing https://github.com/dapr/dapr/pull/6678 to fail.
The OpenAI space is rapidly getting updates so errors like this can be expected.

## Issue reference

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/2716

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by shivam-51** [comment]
@ItalyPaleAle Can you take a look. This should fix the lining errors caused in dapr/dapr PR.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
> The OpenAI space is rapidly getting updates so errors like this can be expected.

Perhaps we should have waited for at least a versioned release. Looks like we are still using development builds.

**Comment by ItalyPaleAle** [comment]
This may be relevant too: https://github.com/Azure/azure-sdk-for-go/issues/21214

**Comment by shivam-51** [comment]
@ItalyPaleAle Any suggestions on how to fix the failing lint test?

**Comment by shivam-51** [comment]
@ItalyPaleAle Please have a look.

**Review by ItalyPaleAle — APPROVED** [review]
Thanks!

**Pull request merged**
