### PR TITLE
RabbitMQ Bindings: Support for mTLS and external authentication with SASL

### PR DESCRIPTION
**Pull request by abossard**
# Description

This is a port of #2515 to enable mTLS and External SASL based auth also in the Dapr bindings for RabbitMQ.

This is based on the EXTERNAL mechanism described here:
https://www.rabbitmq.com/access-control.html#mechanisms

## Issue reference
#2514 but this time for the bindings

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by abossard** [comment]
Please ignore until #2515 is merged.

**Comment by ItalyPaleAle** [comment]
@abossard now that #2515 has been merged, is this ready for review? Could you please address the merge conflicts?

**Comment by abossard** [comment]
I'll take a peek later today and complete it. Thanks for the patience.

**Comment by abossard** [comment]
Hi @berndverst thank, yeah again it was in the docker-compose.yaml a wrong path. Funnily enough it works with Docker Desktop on Mac, but not with Docker on Linux. Fixed and pushed it.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
