### PR TITLE
Add JetStream support

### PR DESCRIPTION
**Pull request by variadico**
# Description

This change adds support for [NATS JetStream](https://docs.nats.io/jetstream/jetstream) as a PubSub Component.

## Issue reference

Although the issue has been closed due to being stale, this PR would address issue #870.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

cc @wallyqs

### CODE REVIEW

**Comment by yaron2** [comment]
@daixiang0 @variadico we will add it. what do you think we should tell users on release notes regarding the other implementation? should we deprecate it now?

/cc @artursouza

**Comment by yaron2** [comment]
@variadico please open a corresponding documentation PR for this component in https://github.com/dapr/docs.

**Comment by variadico** [comment]
Dapr documentation PR: https://github.com/dapr/docs/pull/1751

---

> what do you think we should tell users on release notes regarding the other implementation? should we deprecate it now?

Yeah, I think it would make sense to tell users on the release notes that NATS Streaming has been deprecated and that new projects should use JetStream going forward. It might also be helpful to link to the NATS Streaming readme.

https://github.com/nats-io/nats-streaming-server/#warning--deprecation-notice-warning

**Review by artursouza — CHANGES_REQUESTED** [review]
Please, add conformance tests. I will take a look at this after that.

**Comment by variadico** [comment]
Oook. I think I added the conformance tests: https://github.com/dapr/components-contrib/pull/1101/commits/e1a192a6805e5fd80c74bb485c2260d2d112b363

**Comment by yaron2** [comment]
@variadico there's a minor lint issue:

```
Check failure on line 40 in tests/conformance/common.go

GitHub Actions
/ Build linux_amd64 binaries
tests/conformance/common.go#L40
File is not `gofmt`-ed with `-s` (gofmt)```

You can fix this with ```gofmt -s -w ./tests/conformance/common.go```

**Comment by variadico** [comment]
Whoops, sorry about that. Fixed lint.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
