### PR TITLE
Add conformance tests for Azure Keyvault Secret Store

### PR DESCRIPTION
**Pull request by tcnghia**
# Description

Add conformance tests for Azure Keyvault Secret Store.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #604 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by tcnghia** [comment]
A successful run is here https://github.com/tcnghia/components-contrib/actions/runs/532275420

**Comment by tcnghia** [comment]
BulkGet currently isn't enable due to https://github.com/dapr/components-contrib/issues/655

**Review by halspang — COMMENTED** [review]
Looks good to me. I noticed that the component mentions a password for the cert. Is there value in creating a password protected cert and ensuring that works as well?

https://github.com/dapr/components-contrib/blob/master/secretstores/azure/keyvault/keyvault.go#L23

**Comment by tcnghia** [comment]
> Looks good to me. I noticed that the component mentions a password for the cert. Is there value in creating a password protected cert and ensuring that works as well?
> 
> https://github.com/dapr/components-contrib/blob/master/secretstores/azure/keyvault/keyvault.go#L23

Since our cert is downloaded from KeyVault and cleaned up right away after done, I think we don't need to use a password like one that gets stored for a while (like on a dev laptop). If we add a password, it will need to be stored in the secret store anyway, which doesn't offer us more protection.

**Comment by halspang** [comment]
> > Looks good to me. I noticed that the component mentions a password for the cert. Is there value in creating a password protected cert and ensuring that works as well?
> > https://github.com/dapr/components-contrib/blob/master/secretstores/azure/keyvault/keyvault.go#L23
> 
> Since our cert is downloaded from KeyVault and cleaned up right away after done, I think we don't need to use a password like one that gets stored for a while (like on a dev laptop). If we add a password, it will need to be stored in the secret store anyway, which doesn't offer us more protection.

I'm not worried about the protection so much as if it works or not as a path for the component. Then again, we're getting dangerously close to testing the Azure sdk instead of the component, so I can go either way. Thoughts?

**Comment by tcnghia** [comment]
> > > Looks good to me. I noticed that the component mentions a password for the cert. Is there value in creating a password protected cert and ensuring that works as well?
> > > https://github.com/dapr/components-contrib/blob/master/secretstores/azure/keyvault/keyvault.go#L23
> > 
> > 
> > Since our cert is downloaded from KeyVault and cleaned up right away after done, I think we don't need to use a password like one that gets stored for a while (like on a dev laptop). If we add a password, it will need to be stored in the secret store anyway, which doesn't offer us more protection.
> 
> I'm not worried about the protection so much as if it works or not as a path for the component. Then again, we're getting dangerously close to testing the Azure sdk instead of the component, so I can go either way. Thoughts?

I see. You're correct. Since the password stuff is handled client side in the component, probably it's good to exercise that code path. I'll update the PR

**Comment by tcnghia** [comment]
> > > > Looks good to me. I noticed that the component mentions a password for the cert. Is there value in creating a password protected cert and ensuring that works as well?
> > > > https://github.com/dapr/components-contrib/blob/master/secretstores/azure/keyvault/keyvault.go#L23
> > > 
> > > 
> > > Since our cert is downloaded from KeyVault and cleaned up right away after done, I think we don't need to use a password like one that gets stored for a while (like on a dev laptop). If we add a password, it will need to be stored in the secret store anyway, which doesn't offer us more protection.
> > 
> > 
> > I'm not worried about the protection so much as if it works or not as a path for the component. Then again, we're getting dangerously close to testing the Azure sdk instead of the component, so I can go either way. Thoughts?
> 
> I see. You're correct. Since the password stuff is handled client side in the component, probably it's good to exercise that code path. I'll update the PR

So... the documented usecase does not use a password, since the certificate when provisioned using `az` tool doesn't allow specifying a password. I think the password option was for the cases where the users created their Service Principal and upload a self-signed cert that they generated themselves.

Also, looking at the code, we just pass the password (even if empty) to the library. So as far as our code is concerned, the same code path is exercised.

Given the two reasons above I think it is probably best to test the documented usecase, which is passworld-less cert.

@halspang WDYT

**Comment by halspang** [comment]
@tcnghia I think we should test the documented use case as well, so I'm fine with using the passwordless cert.

**Review by halspang — APPROVED** [review]

**Review by mukundansundar — COMMENTED** [review]
Are the secrets already manually created in the keyvault? Can you add the bulk get once #657 is closed?

**Comment by tcnghia** [comment]
> Are the secrets already manually created in the keyvault? Can you add the bulk get once #657 is closed?

Yes. Added BulkGet.

See successful run https://github.com/tcnghia/components-contrib/runs/1841070549?check_suite_focus=true

**Comment by tcnghia** [comment]
@mukundansundar it's ready for another look

**Comment by tcnghia** [comment]
Rebased. Successful run is here https://github.com/tcnghia/components-contrib/actions/runs/542048981 

@artursouza can you please help review? thanks

**Review by mukundansundar — APPROVED** [review]

**Comment by tcnghia** [comment]
@mukundansundar  can you please help merge? thanks

**Comment by mukundansundar** [comment]
> @mukundansundar can you please help merge? thanks

@tcnghia I do not have permissions.

cc @artursouza @yaron2

**Review by artursouza — APPROVED** [review]

**Pull request merged**
