### PR TITLE
Add get rocketmq group from env to support multi apps use the same component and difference group 

### PR DESCRIPTION
**Pull request by naah69**
# Description

Add get rocketmq group from env to support multi apps use the same component and difference group

## Issue reference

https://github.com/dapr/components-contrib/issues/2370

### CODE REVIEW

**Review by berndverst — CHANGES_REQUESTED** [review]
As a maintainer I will not accept any changes that read environment variables. This is not the correct way to accomplish what you want to do.

You can change the code such that when no consumer group is specified it uses the default value that is autogenerated (which is the same as the app ID). This metadata key will be `consumerID`.

Another option is something like this:
Instead, what you can do is something with this.
https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-namespace/#with-namespace-consumer-groups

**Comment by naah69** [comment]
> As a maintainer I will not accept any changes that read environment variables. This is not the correct way to accomplish what you want to do.
> 
> You can change the code such that when no consumer group is specified it uses the default value that is autogenerated (which is the same as the app ID). This metadata key will be `consumerID`.
> 
> Another option is something like this: Instead, what you can do is something with this. https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-namespace/#with-namespace-consumer-groups

The second way is a way to reslove my issue too,  i  will try it.
If it is not valid , i will try to develop the first idea.

**Comment by berndverst** [comment]
@naah69 I commented on the issue you filed with another solution -- using the local secret store (environment variables). This way you can use environment variables directly as the value of the properties in the RocketMQ component yaml. That may be better for you! Take a look!

I'll close this PR for now. Please open a new PR if you want to implement the default consumer group name (by taking the value from `metadata.properties['consumerID']`)

**Comment by naah69** [comment]
> @naah69 I commented on the issue you filed with another solution -- using the local secret store (environment variables). This way you can use environment variables directly as the value of the properties in the RocketMQ component yaml. That may be better for you! Take a look!
> 
> I'll close this PR for now. Please open a new PR if you want to implement the default consumer group name (by taking the value from `metadata.properties['consumerID']`)

thanks,my  issue had be resolved by the second way.

**Comment by naah69** [comment]
> @naah69 I commented on the issue you filed with another solution -- using the local secret store (environment variables). This way you can use environment variables directly as the value of the properties in the RocketMQ component yaml. That may be better for you! Take a look!
> 
> I'll close this PR for now. Please open a new PR if you want to implement the default consumer group name (by taking the value from `metadata.properties['consumerID']`)

I had a new issue ,where is the document that describe the all vairable that can be use in yaml

**Pull request closed without merging**
