### PR TITLE
add delete to blob storage binding

### PR DESCRIPTION
**Pull request by fabistb**
# Description
Adds the delete functionality to the azure blob binding.

## Issue reference
Please reference the issue this PR will close: #681

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/issues/1277

### CODE REVIEW

**Review by mukundansundar — COMMENTED** [review]
add a doc update for this in dapr/docs repo and the possible values for deleteSnapshotOptions. 

Add the delete test to the conformance test for azure bindings.

**Comment by fabistb** [comment]
@mukundansundar 
Created the issue in the docs repo and I will work on it.
https://github.com/dapr/docs/issues/1277

While enhancing the conformance test I faced a small problem.
In `.../tests/conformance/bindings.go` at the _DeleteOperation_ section it will invoke a GET after the DELETE if a CREATE has been performed and GET is configured. Unfortunately the GET operation of the azure blob binding will always respond with an error if a blob doesn't exist which will cause the test to fail.

A suggestion from your side how to deal with that?

**Comment by mukundansundar** [comment]
> @mukundansundar
> Created the issue in the docs repo and I will work on it.
> [dapr/docs#1277](https://github.com/dapr/docs/issues/1277)
> 
> While enhancing the conformance test I faced a small problem.
> In `.../tests/conformance/bindings.go` at the _DeleteOperation_ section it will invoke a GET after the DELETE if a CREATE has been performed and GET is configured. Unfortunately the GET operation of the azure blob binding will always respond with an error if a blob doesn't exist which will cause the test to fail.
> 
> A suggestion from your side how to deal with that?

@artursouza @pkedy 
For this part I am thinking the test for get after delete for bindings should be configurable and not really a necessity for conformance. What are your thoughts on this?

**Review by yaron2 — APPROVED** [review]
lgtm

**Comment by artursouza** [comment]
> > @mukundansundar
> > Created the issue in the docs repo and I will work on it.
> > [dapr/docs#1277](https://github.com/dapr/docs/issues/1277)
> > While enhancing the conformance test I faced a small problem.
> > In `.../tests/conformance/bindings.go` at the _DeleteOperation_ section it will invoke a GET after the DELETE if a CREATE has been performed and GET is configured. Unfortunately the GET operation of the azure blob binding will always respond with an error if a blob doesn't exist which will cause the test to fail.
> > A suggestion from your side how to deal with that?
> 
> @artursouza @pkedy
> For this part I am thinking the test for get after delete for bindings should be configurable and not really a necessity for conformance. What are your thoughts on this?

I think that having consistent behavior in the APIs is important. In this case, we must define what is the behavior to invoke GET when a resource does not exist: error or return nil? We have made changes to MongoDB state store for its behavior to be consistent with others in a similar scenario. Now, MongoDB will return nil when fetching an item that does not exist.

Long story short, change what needs to be changes to make components consistent and not relax the test.

**Comment by fabistb** [comment]
> > > @mukundansundar
> > > Created the issue in the docs repo and I will work on it.
> > > [dapr/docs#1277](https://github.com/dapr/docs/issues/1277)
> > > While enhancing the conformance test I faced a small problem.
> > > In `.../tests/conformance/bindings.go` at the _DeleteOperation_ section it will invoke a GET after the DELETE if a CREATE has been performed and GET is configured. Unfortunately the GET operation of the azure blob binding will always respond with an error if a blob doesn't exist which will cause the test to fail.
> > > A suggestion from your side how to deal with that?
> > 
> > 
> > @artursouza @pkedy
> > For this part I am thinking the test for get after delete for bindings should be configurable and not really a necessity for conformance. What are your thoughts on this?
> 
> I think that having consistent behavior in the APIs is important. In this case, we must define what is the behavior to invoke GET when a resource does not exist: error or return nil? We have made changes to MongoDB state store for its behavior to be consistent with others in a similar scenario. Now, MongoDB will return nil when fetching an item that does not exist.
> 
> Long story short, change what needs to be changed to make components consistent and not relax the test.

Thanks for the insights.
Just for my understanding. Would such a change qualify for an version of the binding?

**Comment by yaron2** [comment]
> > > > @mukundansundar
> > > > Created the issue in the docs repo and I will work on it.
> > > > [dapr/docs#1277](https://github.com/dapr/docs/issues/1277)
> > > > While enhancing the conformance test I faced a small problem.
> > > > In `.../tests/conformance/bindings.go` at the _DeleteOperation_ section it will invoke a GET after the DELETE if a CREATE has been performed and GET is configured. Unfortunately the GET operation of the azure blob binding will always respond with an error if a blob doesn't exist which will cause the test to fail.
> > > > A suggestion from your side how to deal with that?
> > > 
> > > 
> > > @artursouza @pkedy
> > > For this part I am thinking the test for get after delete for bindings should be configurable and not really a necessity for conformance. What are your thoughts on this?
> > 
> > 
> > I think that having consistent behavior in the APIs is important. In this case, we must define what is the behavior to invoke GET when a resource does not exist: error or return nil? We have made changes to MongoDB state store for its behavior to be consistent with others in a similar scenario. Now, MongoDB will return nil when fetching an item that does not exist.
> > Long story short, change what needs to be changed to make components consistent and not relax the test.
> 
> Thanks for the insights.
> Just for my understanding. Would such a change qualify for an version of the binding?

Just to be clear, binding operations are a per-binding concept and can have different return values. They're not adhering to a strict API and the operation should return whatever makes most sense for the binding first, and take consistency with similar operations for other bindings (if any) after. So all in all, conformance tests should not enforce consistency on *bindings operations*.

**Pull request merged**
