### PR TITLE
Upgrade deps of stable components to latest minor releases

### PR DESCRIPTION
**Pull request by berndverst**
Signed-off-by: Bernd Verst <4535280+berndverst@users.noreply.github.com>

# Description

This upgrade the dependencies of all stable components with certification tests to the latest tagged minor (and patch) releases. Azure components were previously updated and are not part of this PR.

Also updates RabbitMQ to use `PublishWithContext` instead of `Publish` which is now deprecated.
Migrates Postgres and CockroachDB state stores to `jackc/pgx` `v5`

### CODE REVIEW

**Comment by berndverst** [comment]
Figured this would be best to do at the beginning of a new release cycle :)

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by berndverst** [comment]
```bash
go get github.com/Shopify/sarama@v1.37.2
go: downloading github.com/Shopify/sarama v1.37.2
go: downloading github.com/eapache/go-resiliency v1.3.0
go: downloading github.com/jcmturner/gofork v1.7.6
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.3
go: downloading github.com/pierrec/lz4/v4 v4.1.17
go: downloading github.com/hashicorp/go-uuid v1.0.3
go: downloading github.com/Shopify/toxiproxy/v2 v2.5.0
go: downloading github.com/xdg-go/scram v1.1.1
go: downloading github.com/xdg-go/stringprep v1.0.3
go: upgraded github.com/Shopify/sarama v1.30.0 => v1.37.2
go: upgraded github.com/eapache/go-resiliency v1.2.0 => v1.3.0
go: upgraded github.com/hashicorp/go-uuid v1.0.2 => v1.0.3
go: upgraded github.com/jcmturner/gofork v1.0.0 => v1.7.6
go: upgraded github.com/jcmturner/gokrb5/v8 v8.4.2 => v8.4.3
go: added github.com/pierrec/lz4/v4 v4.1.17
go: upgraded github.com/xdg-go/scram v1.0.2 => v1.1.1
go: upgraded github.com/xdg-go/stringprep v1.0.2 => v1.0.3
go: upgraded golang.org/x/net v0.0.0-20220630215102-69896b714898 => v0.0.0-20220927171203-f486391704dc
go: upgraded golang.org/x/sync v0.0.0-20220722155255-886fb9371eb4 => v0.0.0-20220923202941-7f9b1623fab7

go get github.com/jackc/pgx/v4@v4.17.2
go: downloading github.com/jackc/pgx/v4 v4.17.2
go: downloading github.com/jackc/puddle v1.3.0
go: upgraded github.com/jackc/pgx/v4 v4.17.0 => v4.17.2
go: upgraded github.com/jackc/puddle v1.2.1 => v1.3.0

go get github.com/jackc/pgx/v5@v5.0.2
go: downloading github.com/jackc/pgx/v5 v5.0.2
go: upgraded github.com/jackc/pgx/v5 v5.0.0 => v5.0.2

go get github.com/eclipse/paho.mqtt.golang@v1.4.1
go: downloading golang.org/x/sync v0.0.0-20220923202941-7f9b1623fab7
go: upgraded github.com/eclipse/paho.mqtt.golang v1.3.5 => v1.4.1

go get github.com/gocql/gocql@v1.2.1
go: downloading github.com/gocql/gocql v1.2.1
go: upgraded github.com/gocql/gocql v0.0.0-20210515062232-b7ef815b4556 => v1.2.1

go get go.mongodb.org/mongo-driver@v1.10.3
go: downloading go.mongodb.org/mongo-driver v1.10.3
go: upgraded go.mongodb.org/mongo-driver v1.5.1 => v1.10.3

go get github.com/denisenkom/go-mssqldb@v0.12.2
go: downloading github.com/denisenkom/go-mssqldb v0.12.2
go: downloading github.com/golang-sql/sqlexp v0.1.0
go: upgraded github.com/denisenkom/go-mssqldb v0.0.0-20210411162248-d9abbec934ba => v0.12.2
go: added github.com/golang-sql/sqlexp v0.1.0

```

**Comment by ItalyPaleAle** [comment]
> github.com/jackc/pgx/v4

@berndverst  we should upgrade to v5

**Comment by berndverst** [comment]
> > github.com/jackc/pgx/v4
> 
> @berndverst we should upgrade to v5

Yes I know, but in my next PR I will do that. I want to separate those things out :)

**Review by ItalyPaleAle — APPROVED** [review]

**Review by ItalyPaleAle — APPROVED** [review]

**Pull request merged**
