### PR TITLE
conformance tests for AWS pubsub SQS SNS

### PR DESCRIPTION
**Pull request by amimimor**
Signed-off-by: Amit Mor <amit.mor@hotmail.com>

# Description

Conformance tests.
Note that ordering of messages is disabled in test setup yaml, as localstack SQS FIFO (that is needed for message ordering) support is broken (not documented but tested). 
My tries to use a custom image of localstack with Elasticmq (SQS API but with fifo support) failed as the localstack SNS seems to be dropping a mandatory param (`MessageGroupId`) as it publishes to SQS. I've verified that when the component is configured with `fifo` set to true that param is indeed sent off. 
localstack in that situation doesn't "complain", but as stated, it doesn't support FIFO.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1393 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by mukundansundar — CHANGES_REQUESTED** [review]
@amimimor Based on the README https://github.com/dapr/components-contrib/blob/master/tests/conformance/README.md#conformance-test-workflow 
Modify the workflow to add PR components for SQS and SNS since it is a local docker compose setup.

**Review by mukundansundar — APPROVED** [review]
lgtm
@artursouza @yaron2  Please take a look.

**Review by artursouza — APPROVED** [review]

**Comment by mukundansundar** [comment]
@amimimor can you create a docs PR for the same ?

**Comment by amimimor** [comment]
> @amimimor can you create a docs PR for the same ?

Detailing the component to now be "beta"?

**Comment by yaron2** [comment]
> > @amimimor can you create a docs PR for the same ?
> 
> Detailing the component to now be "beta"?

Yes, the component can advance to beta.

**Comment by amimimor** [comment]
> > > @amimimor can you create a docs PR for the same ?
> 
> > 
> 
> > Detailing the component to now be "beta"?
> 
> 
> 
> Yes, the component can advance to beta.

Just did. It waits a review. Also another doc pr is in waiting to meet v1.6

**Pull request merged**
