### PR TITLE
kafka aws iam auth profile

### PR DESCRIPTION
**Pull request by famarting**
# Description

Adds support for the authType `awsIAM` to the kafka components

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3239

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by yaron2** [comment]
@amimimor can you please help review this PR?

**Comment by amimimor** [comment]
Regarding this issue and associated pull request, @yaron2 and I are currently discussing the proposed implementation, which depends on the AWS Go SDK version 2 library directly and indirectly. AFAIK, the Components ecosystem for this project has not yet migrated to using version 2 of the AWS Go SDK.

We need to evaluate whether now is the appropriate time to introduce a dependency on v2, or if we should consider alternative implementations that are compatible with the v1 SDK that is currently used across components.

**Review by amimimor — APPROVED** [review]
LGTM. 
Note, for future reference that this is the first time the project uses AWS Go SDK v2 module (while the rest of the project uses v1)

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
@famarting please follow up with docs.

**Review by amimimor — APPROVED** [review]

**Pull request merged**
