### PR TITLE
Fixing #1845

### PR DESCRIPTION
**Pull request by cmendible**
Signed-off-by: cmendible <cmendible@gmail.com>

# Description

Fixing #1845 by rewriting the `parseMetadata` method.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1845

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]
Thanks!!

**Comment by ItalyPaleAle** [comment]
@cmendible Could you please rebase this against the branch “release-1.8”? I tried doing it through the GitHub UI but I made it worse :(

**Comment by cmendible** [comment]
> @cmendible Could you please rebase this against the branch “release-1.8”? I tried doing it through the GitHub UI but I made it worse :(

let me try

**Comment by cmendible** [comment]
@ItalyPaleAle will you cherry pick into master later? By the way DCO did not pass cause of some previous commits....

**Comment by ItalyPaleAle** [comment]
Yeah sorry I messed it up trying to change the base. I'll cherry-pick your commit tomorrow (will make sure you're marked as author :) )

**Comment by ItalyPaleAle** [comment]
@cmendible I cherry-picked your commit here: https://github.com/dapr/components-contrib/pull/1850 and targeting release-1.8. 

I maintained your original commit and credits (fun fact if you didn't know it: you can append `.patch` to many GitHub URLs to get an email-formatted patch that can be applied with `git am`, so preserves everything).

Will close this :)

**Pull request closed without merging**
