### PR TITLE
fix binding list test

### PR DESCRIPTION
**Pull request by rainfd**
# Description

The conformance binding test list operation used the wrong operation

## Issue reference

n/a

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by daixiang0 — APPROVED** [review]

**Review by beiwei30 — APPROVED** [review]
LGTM too. Let's wait for CI status.

**Comment by CodeMonkeyLeet** [comment]
Conformance tests for PR do NOT run the Azure blob storage test by default, so it does not indicate that the underlying issue in the blob storage binding noted in #1051 has been fixed.

@artursouza #1273 should be merged and then the `/ok-to-test` initiated on this PR to validate the Azure conformance tests on this PR.

**Comment by yaron2** [comment]
@CodeMonkeyLeet it would be good to follow up on https://github.com/dapr/components-contrib/pull/1273 with a Dapr-Bot comment giving feeback about execution status and perhaps even a link.

**Comment by CodeMonkeyLeet** [comment]
@yaron2 it looks like the test ran and showed that the blob storage test will fail the list operation test, see https://github.com/dapr/components-contrib/actions/runs/1505608130, and it pulled the e0267bf commit hash that was current at the time you ran the command.

It's a good suggestion to have the bot commands respond in comments with the run info, but I was just fixing up the existing implementation that didn't work. @tanvigour to note the suggestion, if you still own the automation piece here.

**Pull request merged**
