### PR TITLE
Backport #1957 into release-1.8

### PR DESCRIPTION
**Pull request by ItalyPaleAle**

### CODE REVIEW

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
Conf: https://github.com/dapr/components-contrib/actions/runs/2836055082
Cert: https://github.com/dapr/components-contrib/actions/runs/2836055078

**Comment by ItalyPaleAle** [comment]
Had to pull in https://github.com/dapr/components-contrib/commit/5afb1c9b8f343553465bbe5e2cab0c33a77dd17a because of a merge issue

**Review by berndverst — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
Bot merged this. The failing certification tests are because they do not exist in the release-1.8 branch (were added in the master branch only). All good

**Pull request merged**
