### PR TITLE
Fix Azure Service Bus cert/conf tests

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
After merging #2211 , some tests are now failing in master (that we couldn't check before because they required a pipeline merged into master). This fixes the issues introduced by that PR.

### CODE REVIEW

**Review by berndverst — DISMISSED** [review]

**Review by berndverst — APPROVED** [review]

**Review by 1046102779 — COMMENTED** [review]
`test.log`  is  a ignore file?

**Comment by berndverst** [comment]
> `test.log`  is  a ignore file?

It was accidentally committed, but will not be ignored.

**Comment by ItalyPaleAle** [comment]
It's been deleted now

**Pull request merged**
