### PR TITLE
Upgrade all Azure Track 2 components to their latest minor / patch SDK versions

### PR DESCRIPTION
**Pull request by berndverst**
# Description

1.) Upgrade all Azure Track 2 components to their latest minor / patch SDK versions

2.) This PR also removes an unused integration test which is already covered by certification tests. This removes an unnecessary old SDK import.

The key change of this PR is this:
image

Note that this required minor changes in the Azure Keyvault Secrets method signatures.

### CODE REVIEW

**Comment by berndverst** [comment]
Merge this after #2110.

**Comment by berndverst** [comment]
Certification: https://github.com/dapr/components-contrib/actions/runs/3101885440
Conformance: https://github.com/dapr/components-contrib/actions/runs/3101885458

**Comment by berndverst** [comment]
cc @artursouza for approval :)

**Review by mukundansundar — APPROVED** [review]
lgtm

**Pull request merged**
