### PR TITLE
AWS SNS/SQS PubSub Certification Tests - Part 1

### PR DESCRIPTION
**Pull request by robertojrojas**
# Description
Provides the AWS SNS/SQS PubSub Certification Test Plan and Test Code.
It depends on issue #2282 

## Issue reference
This PR makes progress towards #1339 and #1971 but does not complete these. More component metadata tests will need to be added.

### CODE REVIEW

**Comment by berndverst** [comment]
The AWS test infrastructure has now been merged. Similar to the way the SNS/SQS test has been enabled in the conformance workflow, what remains to be done is also add this to the certification test workflow.

Can you take a look at the conformance test workflow and see what needs to be added to the certification test workflow? @addjuarez can probably help.

**Review by berndverst — CHANGES_REQUESTED** [review]
You need to update your component yaml files.

Please explicitly refer to the AWS credentials (this is easier to understand for maintenance reasons).

I believe we also must refer to the specific region -- it is unclear to me whether we are running in US-EAST-1 or US-WEST-1. @RyanLettieri to clarify this (there were a mix of files checked in with conflicting locations)

Additionally, you may need to specify a particular consumer group that is pre-created. Please refer to the conformance test component configuration

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aws-snssqs
  namespace: default
spec:
  type: pubsub.aws.snssqs
  version: v1
  metadata:
    - name: accessKey
      value: ${{AWS_ACCESS_KEY_ID}}
    - name: secretKey
      value: ${{AWS_SECRET_ACCESS_KEY}}
    - name: region
      value: "us-east-1"
    - name: consumerID
      value: ${{PUBSUB_AWS_SNSSQS_QUEUE}}
    - name: messageVisibilityTimeout
      value: 10
    - name: messageRetryLimit
      value: 10
    - name: messageWaitTimeSeconds
      value: 1
    - name: messageMaxNumber
      value: 10
    - name: concurrencyMode
      value: "single"
    - name: disableEntityManagement
      value: "true"
```

@RyanLettieri should advise on how to ensure the certification test can run in parallel with the conformance test etc (make sure different infra is provisioned)

**Comment by robertojrojas** [comment]
> You need to update your component yaml files.
> 
> Please explicitly refer to the AWS credentials (this is easier to understand for maintenance reasons).
> 
> I believe we also must refer to the specific region -- it is unclear to me whether we are running in US-EAST-1 or US-WEST-1. @addjuarez to clarify this (there were a mix of files checked in with conflicting locations)
> 
> Additionally, you should probably define the various consumer groups you wish to use in the workflow so you can generate unique names - or unique suffixes, this will allow this test to be run multiple times in parallel.
> 
> Please see the conformance test yaml file for the steps to do this. But this also means you must refer to the dynamic value within your component yaml files.
> 
> ```yaml
> apiVersion: dapr.io/v1alpha1
> kind: Component
> metadata:
>   name: aws-snssqs
>   namespace: default
> spec:
>   type: pubsub.aws.snssqs
>   version: v1
>   metadata:
>     - name: accessKey
>       value: ${{AWS_ACCESS_KEY_ID}}
>     - name: secretKey
>       value: ${{AWS_SECRET_ACCESS_KEY}}
>     - name: region
>       value: "us-east-1"
>     - name: consumerID
>       value: ${{PUBSUB_AWS_SNSSQS_QUEUE}}
>     - name: messageVisibilityTimeout
>       value: 10
>     - name: messageRetryLimit
>       value: 10
>     - name: messageWaitTimeSeconds
>       value: 1
>     - name: messageMaxNumber
>       value: 10
>     - name: concurrencyMode
>       value: "single"
>     - name: disableEntityManagement
>       value: "true"
> ```
> 
> @addjuarez should advise on how to ensure the certification test can run in parallel with the conformance test etc (make sure different infra is provisioned)
> 
> EDIT: Sorry meant to write @addjuarez not @RyanLettieri

@berndverst great points! I'll take care of that soon.

**Comment by addjuarez** [comment]
To clear up the zone confusion. The sns/sqs conformance tests use the zone us-east-1 as you see in the yaml above. Be default the terraform will use us-west-1. 
https://github.com/dapr/components-contrib/blob/2f796baa5ac7c406ba30ed34e3cfb2c30be81041/.github/workflows/conformance.yml#L292 

You however can override it in your terraform file like I did here 
https://github.com/dapr/components-contrib/blob/2f796baa5ac7c406ba30ed34e3cfb2c30be81041/.github/infrastructure/terraform/conformance/pubsub/aws/snssqs/snssqs.tf#L23

**Review by berndverst — CHANGES_REQUESTED** [review]
In the certification test workflow you are missing a SNS/SQS specific step which does the following:

- Set `AWS_REGION` to `us-east-1` (but only for SNS/SQS -- as an override from the global `us-west-1` setting.
- Generate a RANDOM value for `PUBSUB_AWS_SNSSQS_QUEUE_1` and `PUBSUB_AWS_SNSSQS_QUEUE_2` -- make sure to actually set those environment variables with this random value.

**Review by berndverst — COMMENTED** [review]
All certification tests should test / verify all of the component metadata options present in every component.

There are many options not covered by this test.

See https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-aws-snssqs/

I will rename this PR to indicate that it only partially completes the certification test.

**Review by berndverst — APPROVED** [review]

**Pull request merged**
