### PR TITLE
chore(deps): bump sarama to v1.41.0

### LINKED ISSUE #3104: Update Kafka sarama package to 1.41
## Expected Behavior

When consumer pods scale out, pods should automatically be included in the consumer groups and immediately begin consuming once all health checks have passed and the sidecar states that it has joined the consumer group.

## Actual Behavior

Often times pods do not ever join the consumer group. These pods reflect as healthy and log that they have joined the consumer group, but actually do not pick up any work. They do not reflect on Kafka as part of the consumer group. This appears to be related to various bugs in the shopify/sarama Go library for Kafka and by all accounts is fixed in version 1.41.0 which was released last week.

Related issues:
https://github.com/IBM/sarama/issues/1516
https://github.com/IBM/sarama/issues/2621

Fix version:
https://github.com/IBM/sarama/releases/tag/v1.41.0

## Steps to Reproduce the Problem

1. Create a topic in Kafka with a high number of partitions (30 or more)
2. Define a consumer pod that is subscribed to the topic with a low number of pods by default with a flexible HPA config
3. Use some kind of publisher to generate a high volume of traffic (at least 1000 events per second)
4. Observe in K8s that pods have scaled out while consumer count in the consumer group does not match the number of pods.

Likely side effect is consumer lag grows dramatically and consumption remains fixed to only a handful of pods. In my case, I am running a topic with 50 partitions, 50 pods, but only have 29 consumers in the consumer group.

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by dnwe**
# Description

Bump sarama to v1.41.0

Also remove old module replace pin to v1.37.2 as that shouldn't be necessary since https://github.com/dapr/docs/pull/3474 added documentation to add a config version pin for Azure EventHubs users instead.

Note: the module path has changed to github.com/IBM/sarama since ownership transitioned away from Shopify

## Issue reference

Fixes #3104

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by berndverst** [comment]
Please do not upgrade any deps at this time. I upgraded everything there was to upgrade safely yesterday and merged that this morning. We cannot safely upgrade sarama at this time.

See https://github.com/dapr/components-contrib/pull/3106

**Comment by berndverst** [comment]
The original issue with `sarama` were these:
https://github.com/dapr/components-contrib/issues/2755
https://github.com/dapr/components-contrib/issues/2874

After upgrading sarama we encountered several issues. For this reason we will not take the risk to upgrade sarama at this time (just ahead of the 1.12 release).

To upgrade this library we will need to perform further manual testing and we do not have the bandwidth at this time.

**Comment by berndverst** [comment]
@dnwe I'll see if we can run some additional tests - if we can get EventHubs to work with this version we can reopen this PR. That being said, I'm not sure anyone has time ahead of the 1.12 release unfortunately.

**Comment by dnwe** [comment]
@berndverst yes no problem, I expect https://github.com/IBM/sarama/issues/2470 was the underlying issue
 
The problem with supporting Azure Event Hubs is that it isn't Apache Kafka under the covers, it's an intermediate proxy that supports a subset of the Kafka APIs at various versions and then maps them onto Event Hubs protocol(s) at the backend. As as result Sarama's current mechanism of specifying the KAFKA_VERSION to determine what protocol versions to support and use doesn't really work properly with Event Hubs because it supports an unusual set of protocols and even defines minimum versions for ProduceRequest (v3) and FetchRequest (v4). For some reason EventHubs is very behind on FetchRequest and MetadataRequest so the max configuration you can use in Sarama is V1_0_0_0.

Here are the equivalent max versions for Kafka 1.0 and EventHubs:

```
    APIs                                 1.0  EventHubs
0   ProduceRequest                       v5   v7
1   FetchRequest                         v6   v6
2   ListOffsetsRequest                   v2   v7
3   MetadataRequest                      v5   v5
8   OffsetCommitRequest                  v3   v8
9   OffsetFetchRequest                   v3   v8
10  FindCoordinatorRequest               v1   v1
11  JoinGroupRequest                     v2   v7
12  HeartbeatRequest                     v1   v4
13  LeaveGroupRequest                    v1   v4
14  SyncGroupRequest                     v1   v5
15  DescribeGroupsRequest                v1   v5
16  ListGroupsRequest                    v1   v4
17  SaslHandshakeRequest                 v1   v1
18  ApiVersionsRequest                   v1   v3
19  CreateTopicsRequest                  v2   v6
20  DeleteTopicsRequest                  v1   v2
22  InitProducerIdRequest                v0   v1
23  OffsetForLeaderEpochRequest          v0   v0
32  DescribeConfigsRequest               v0   v2
36  SaslAuthenticateRequest              v0   v1
37  CreatePartitionsRequest              v0   v1
42  DeleteGroupsRequest                       v0
47  OffsetDeleteRequest                       v0
```

**Review by berndverst — APPROVED** [review]

**Comment by dnwe** [comment]
@berndverst ah thanks, I didn't realise you were going to re-open and merge this.

I followed up with https://github.com/dapr/components-contrib/pull/3109 to put an additional safety blanket in-place that should prevent you from getting issues raised by Event Hubs users

**Pull request merged**
