### PR TITLE
Add context in bindings interface

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

# Description

add context.Context in bindings interface.

## Issue reference
https://github.com/dapr/dapr/issues/2716
https://github.com/dapr/components-contrib/issues/1601

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by berndverst — CHANGES_REQUESTED** [review]
@pigletfly Can you please undo the reordering of the imports? The existing order was much easier to read and understand.

A few things to note:
You also need to open a PR against `dapr/dapr` to actually provide the context to these binding methods.

It needs to be added to `binding.Read` and `binding.Invoke`

https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L844
https://github.com/dapr/dapr/blob/master/pkg/runtime/runtime.go#L1019

**Comment by berndverst** [comment]
This PR looks good, but we shouldn't reorder the imports like this :)

**Comment by berndverst** [comment]
Also as you can see the stable components certification tests for bindings will fail because of this PR. You will need to update the runtime to set the context, and then you will need to update those tests as I mentioned before.

**Comment by pigletfly** [comment]
ok, I will update this PR step by step

**Comment by pigletfly** [comment]
@daixiang0 could you help to review this PR and trigger the CI workflow ?

**Comment by berndverst** [comment]
@pigletfly the CI workflow already ran when you pushed to it. There is still a linter failure -- you need to `gofumpt` the files you modified.

There is no need to also get a review from @daixiang0 since I am a maintainer, but feel free. Once you fix the linter issues (by making `components-contrib / Build linux_amd64` pass) I can approve and merge this.

In the meantime, could you please start making the `dapr/dapr` PR? You can later update that PR by adding a commit with the `go.mod` and `go.sum` update to import the latest contrib via `go get github.com/dapr/components-contrib@master`, we really want to be quick about merging all of these things so that our tests will not be failing for a longer period of time.

**Comment by berndverst** [comment]
Thanks for already updating the certification tests @pigletfly. By the way it is expected that these will fail at this time.

That's why it is important we get the `dapr/dapr` created and merged soon, and then another PR for contrib for the submodule `test/certification` to pin the latest `dapr/dapr` there.

**Comment by pigletfly** [comment]
@berndverst I pinged @daixiang0 because we are in the same time zone. PR in `dapr/dapr` https://github.com/dapr/dapr/pull/4550

**Review by berndverst — APPROVED** [review]

**Comment by berndverst** [comment]
@pigletfly unfortunately even as a maintainer I cannot merge this because of the breaking certification tests -- I will need to work with a steering committee member to force merge this. Maintainers do not have this power unfortunately.

Maybe @yaron2 or @artursouza can help out here.

Certification test failures are expected as discussed. To resolve those failures we must merge https://github.com/dapr/dapr/pull/4550 (and bring in the latest contrib with this very PR here), then we need to update the certification tests to pin the latest dapr/dapr.

**Comment by pigletfly** [comment]
sounds like there is a circular dependency between dapr/dapr and dapr/components-contrib ?

**Comment by berndverst** [comment]
@pigletfly sort of -- the main issue is that the stable certification tests are a submodule within contrib. That has some advantages (e.g. you can immediately run certification tests when you modify a component due to the local replace directive) but it also has the disadvantage of this complicated process whenever you change the Dapr runtime.

**Comment by pigletfly** [comment]
thanks for your detailed explanations. @berndverst

**Review by artursouza — APPROVED** [review]

**Pull request merged**
