### PR TITLE
Fix redefine flag

### PR DESCRIPTION
**Pull request by filintod**
# Description

This PR add something similar to https://github.com/kubernetes-sigs/controller-runtime/pull/1999 to avoid redefined kubeconfig flag issues when using this library plus others that might already have kubeconfig as a flag.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #2993 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — COMMENTED** [review]
Although this PR LGTM, I was not aware of this code and this behavior. It does seem odd that we're defining CLI flags in components-contrib. This seems anti-pattern?

**Comment by filintod** [comment]
It does seem strange maybe to ease tests but don't know the original use case

**Comment by daixiang0** [comment]
> It does seem strange maybe to ease tests but don't know the original use case

Do we really register it in the CLI?

**Comment by ItalyPaleAle** [comment]
Looks like it is getting registered. Running `daprd --help`:

```
  -kubeconfig string
    	(optional) absolute path to the kubeconfig file (default "/Users/alessandro/.kube/config")
```

I think this needs to change. We should allow setting the kubeconfig file using the metadata for each component.

@filintod can you change that please?

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
Let's refactor this to avoid adding CLI flags to daprd

**Comment by filintod** [comment]
I can follow as how it is done in dapr https://github.com/dapr/dapr/blob/master/utils/utils.go#L50

with a custom kubeconfig env var `KUBE_CONFIG`

wdty?

**Comment by ItalyPaleAle** [comment]
@filintod that method looks like is being used by Dapr control plane services only (operator, injector, sentry), and not by daprd.

I would prefer the Kubeconfig path to be a metadata option in all Kubernetes components. This is the pattern we use to configure all components.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by filintod** [comment]
thanks, sorry I forgot about this.

**Comment by ItalyPaleAle** [comment]
> thanks, sorry I forgot about this.

No worries! It became a bit more of a pressure because of dapr/dapr#6766

Do the changes look good to you? Mind doing a quick review?

I plan on doing the 2nd part, which is allowing setting kubeconfig path in components' metadata, in a separate PR.

**Comment by ItalyPaleAle** [comment]
See #3060 for part 2

**Pull request merged**
