### PR TITLE
Add metadata to SubscribeRequest

### PR DESCRIPTION
**Pull request by jjcollinge**
# Description

Added a metadata field to a SubscribeRequest to allow additional data to be provided to the pubsub component.

## Issue reference

Please reference the issue this PR will close: #[Dapr/2379](https://github.com/dapr/dapr/issues/2379)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by jjcollinge** [comment]
Little unsure why the tests passed on Linux but not on Darwin - @yaron2 could you rerun the failed checks please or should I submit an empty commit?

**Comment by yaron2** [comment]
@jjcollinge tests are passing.

**Comment by yaron2** [comment]
Is this still under Draft?

**Comment by jjcollinge** [comment]
@yaron2 should be good to go.

**Review by yaron2 — APPROVED** [review]
lgtm

**Pull request merged**
