### PR TITLE
Hazelcast state store implementation

### PR DESCRIPTION
**Pull request by abhirockzz**
# Description

State store implementation for [Hazelcast](https://hazelcast.org/) using its `Map` data structure

## Issue reference

Issue #119 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
WOOT!

Will review tomorrow

**Comment by abhirockzz** [comment]
@yaron2 can you please help resolve the `check-diff` issues?

**Comment by yaron2** [comment]
yep

**Comment by abhirockzz** [comment]
Thanks. I did try pulling in the changes - didn't work as expected.

**Comment by yaron2** [comment]
@abhirockzz can you try to run `go mod tidy` locally and push any changes?
Also, are you sure you don't have any stashed or uncommitted changes?

**Comment by yaron2** [comment]
@abhirockzz can you pull latest, run `go mod tidy` and again push any changes?

**Comment by abhirockzz** [comment]
> @abhirockzz can you pull latest, run `go mod tidy` and again push any changes?

That's what I did. Opened a new PR #145 . Forked latest from `dapr` master, based these changes on top of it, `go mod tidy` and pushed changes

**Comment by yaron2** [comment]
Closing for #145

**Pull request closed without merging**
