### PR TITLE
Add more JetStream options

### LINKED ISSUE #2179: Add missing config for JetStream Consumer
## Describe the feature
JetStream pub sub component does not include all and recent configuration options:
```
	ackWait        time.Duration
	maxDeliver     int
	backOff        []time.Duration
	maxAckPending  int
	replicas       int
	memoryStorage  bool
	rateLimit      uint64
	hearbeat       time.Duration
```

## Release Note

RELEASE NOTE:
Add missing config fields for NATS JetStream pub sub component

### PR DESCRIPTION
**Pull request by Jarema**
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

# Description

This PR adds missing fields in JetStream Consumer configuration.

## Issue reference

close #2179 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by Jarema** [comment]
Will update the docs when this passes the review.

**Review by berndverst — APPROVED** [review]
Please open a docs PR against the 1.10 branch of the docs.

**Comment by berndverst** [comment]
Thanks for the contribution Tomasz. Please open a docs PR when the 1.10 branch has been created (should be very soon). Without the docs PR of course nobody will be able to discover these new options.

https://github.com/dapr/docs/issues/2884

**Comment by Jarema** [comment]
Docs updated!
https://github.com/dapr/docs/pull/2893

**Pull request merged**
