### PR TITLE
refactored aws sqs policy inserting

### LINKED ISSUE #1780: AWS SQS/SNS submit more than 20 statement in access policy
## Expected Behavior

A service should be able to subscribe to more than 20 topic without submitting more than statement in access policy to sqs.
The maximum limit for attaching a managed policy to an IAM role or user is 20 in AWS.

## Actual Behavior
When a service is subscribed to more than 20 topics, the following error is shown, saying that more than 20 statement were found in the submitted policy, which over the limit of aws.
```

time="2022-06-08T13:40:54.607042655Z" level=error msg="error setting sns-sqs subscription policy: error setting queue subscription policy: OverLimit: 21 statements were found in the submitted policy, max allowed is 20\n\tstatus code: 403, request id: 17f49068-d8e9-5e78-8bd6-cb7271cf4bda" app_id=xxxxx instance=xxxxx scope=dapr.contrib type=log ver=1.6.0
time="2022-06-08T13:40:54.607155617Z" level=error msg="failed to subscribe to topic xxx-topic: error setting sns-sqs subscription policy: error setting queue subscription policy: OverLimit: 21 statements were found in the submitted policy, max allowed is 20\n\tstatus code: 403, request id: 17f49068-d8e9-5e78-8bd6-cb7271cf4bda" app_id=xxxxx instance=xxxx scope=dapr.runtime type=log ver=1.6.0
```

## Steps to Reproduce the Problem

Create a test app that subscribes to more than 20 topics. Run the app with AWS SQS/SNS component configured for pubsub. check that if every sns topic has its access policy created

## Possible solution
instead of adding a access policy for each sns topic, we can use [condition set operator  ](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_multi-value-conditions.html) and add sns arns to a single  `aws:SourceArn` array like the following
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sns.amazonaws.com"
      },
      "Action": "sqs:SendMessage",
      "Resource": "<SQS>",
      "Condition": {
        "ForAnyValue:ArnEquals": {
          "aws:SourceArn": [
....
          ]
        }
      }
    }
  ]
}`
## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by xingrux**
Signed-off-by: Xingru <x.xingruxu@student.maastrichtuniversity.nl>

# Description
For aws sqs pubsub component, when adding a new statement, add it to an array of sns arns instead of add a new statement to avoid over limit 20, which is the maximum number of access policy statement

## Issue reference

This pr fixes #1780 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Looks good to me, my only question is what happens to existing statements (i.e. during an upgrade). Will this cause any issue?

**Comment by berndverst** [comment]
FYI - this will not be part of release 1.8

**Review by amimimor — APPROVED** [review]
LGTM

**Comment by xingrux** [comment]
> 



> Looks good to me, my only question is what happens to existing statements (i.e. during an upgrade). Will this cause any issue?

Thanks for reviewing! From my understanding, the statements will be overwritten by `SetQueueAttributesWithContext`. And in practice, I have a custom access policy document and every time I deploy, it is overwritten by dapr, and I replace it with my custom one.

**Comment by xingrux** [comment]
> FYI - this will not be part of release 1.8

Thanks for the information. Is there any way to build this branch and use it?

**Comment by berndverst** [comment]
> > FYI - this will not be part of release 1.8
> 
> Thanks for the information. Is there any way to build this branch myself and use it?

Absolutely.

First you need to clone github.com/dapr/dapr, then you need to import your branch of components-contrib instead of what is there.

You can do this via:
`go get https://github.com/xingrux/components-contrib@master`

Next you will want to make sure you run `go mod tidy` - for convenience I recommend running this via `make modtidy-all`.

Now you are ready to build your own version of Dapr:
Take a look at the step by step option documented here https://github.com/dapr/dapr/blob/master/tests/docs/running-e2e-test.md#option-2-step-by-step-guide

You can skip the step for running the E2E test apps. Instead you can just deploy your applications however you want.

Oh and if you don't use Kubernetes it is event easier, just simply run `make build`.

**Comment by xingrux** [comment]
> First you need to clone `github.com/dapr/dapr`, then you need to import your branch of components-contrib instead of what is there.
> 
> You can do this via: `go get https://github.com/xingrux/components-contrib@master`
> 
> Next you will want to make sure you run `go mod tidy` - for convenience I recommend running this via `make modtidy-all`.
> 
> Now you are ready to build your own version of Dapr:

Thank you very much. I’ve test the build in practical environment and found some bugs. I’ve fixed them this week and will push the changes this weekend.

**Review by yaron2 — APPROVED** [review]

**Comment by yaron2** [comment]
@xingrux please fix the linter issues and we'll merge this PR:

```
Error: File is not `gofumpt`-ed (gofumpt)
Error: File is not `gofumpt`-ed (gofumpt)
Error: File is not `goimports`-ed with -local github.com/dapr/ (goimports)
```

**Comment by yaron2** [comment]
@xingrux fix linter errors and we can merge: https://github.com/dapr/components-contrib/runs/7729233136?check_suite_focus=true.

**Comment by yaron2** [comment]
See current errors:

```
  Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout 15m] in [] ...
  Error: expected '(', found Test_buildARN_DefaultPartition (typecheck)
  Error: expected '(', found Test_buildARN_StandardPartition (typecheck)
  Error: expected '(', found Test_buildARN_NonStandardPartition (typecheck)
  Error: expected '}', found 'EOF' (typecheck)
```

**Comment by yaron2** [comment]
Ping @xingrux

**Comment by yaron2** [comment]
ping @xingrux

**Comment by xingrux** [comment]
@yaron2 Thanks! I've fixed the error.

**Review by yaron2 — APPROVED** [review]

**Review by berndverst — APPROVED** [review]

**Pull request merged**
