### PR TITLE
Update github.com/a8m/documentdb to latest commit to fix consistency …

### PR DESCRIPTION
**Pull request by artursouza**
…level options.

# Description

Update github.com/a8m/documentdb to latest commit to fix consistency levels enum.

Validated locally by reproducing the error before the fix and then confirming this version fixes it.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #465 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by youngbupark — DISMISSED** [review]
simple fix :)

**Review by mukundansundar — CHANGES_REQUESTED** [review]
run `go mod tidy`

**Review by yaron2 — APPROVED** [review]
thx for picking this up

**Comment by artursouza** [comment]
DId run go mod tidy. Please, re-approve.

**Review by mukundansundar — APPROVED** [review]

**Pull request merged**
