### PR TITLE
check ETag for etcd state store update and delete ops

### PR DESCRIPTION
**Pull request by abhirockzz**
# Description

Updates etcd state store implementation to check ETags on updates and deletes as per https://github.com/dapr/docs/blob/master/concepts/state-management/state-management.md

## Issue reference

Issue #169 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by yaron2** [comment]
Thanks.

/cc @Haishi2016

**Comment by yaron2** [comment]
There's a bunch of unrelated files here, no?

**Comment by abhirockzz** [comment]
> There's a bunch of unrelated files here, no?

Yes. Not sure what's going on. This has happened in other PRs as well - see [this](https://github.com/dapr/components-contrib/pull/145/files) and [this](https://github.com/dapr/components-contrib/pull/173/files)

Here is what I did:

- clone my fork
- synced it - `git fetch upstream`, `git merge upstream/master`, `git push origin master`
- made changes and then `make lint`, `make test`, `make go.mod check-diff`
- `git status` showed a bunch of other files (extra ones)
- `git commit` only `etcd.go`
- pushed changes to my fork

I may be missing something - pls let me know and I'll fix them

**Comment by yaron2** [comment]
I recommend to close this PR and open a new one, just make sure you save the relevant changes!! :)

1. Fork
2. Git clone your fork
3. git remote add upstream https://github.com/dapr/components-contrib.git
4. git merge upstream/master
5. git checkout -b [name of branch]
6. Make changes
7. Add, commit, push

**Comment by abhirockzz** [comment]
> I recommend to close this PR and open a new one, just make sure you save the relevant changes!! :)
> 
> 1. Fork
> 2. Git clone your fork
> 3. git remote add upstream https://github.com/dapr/components-contrib.git
> 4. git merge upstream/master
> 5. git checkout -b [name of branch]
> 6. Make changes
> 7. Add, commit, push (git push origin [name of branch])

Ok I followed these. `git status` only reflected `etcd.go` until step 6. After step 6, all I did was `git add state/etcd/etcd.go` and then `make lint`. `git status` now shows a bunch of other files as well 

```
	modified:   bindings/aws/s3/s3.go
	modified:   bindings/aws/sqs/sqs.go
	modified:   bindings/azure/eventhubs/eventhubs.go
	modified:   bindings/azure/storagequeues/storagequeues.go
	modified:   bindings/azure/storagequeues/storagequeues_test.go
	modified:   bindings/kafka/kafka.go
	modified:   middleware/http/oauth2/oauth2_middleware.go
	modified:   pubsub/azure/servicebus/servicebus.go
	modified:   pubsub/nats/nats.go
	modified:   pubsub/rabbitmq/rabbitmq.go
	modified:   secretstores/gcp/cloudkms/cloudkms.go
```

**Comment by yaron2** [comment]
Ok, it's the linter making those changes. It should be ok. I'll review tomorrow and make sure it's not blowing anything up.

**Comment by abhirockzz** [comment]
> Ok, it's the linter making those changes. It should be ok. I'll review tomorrow and make sure it's not blowing anything up.

Thanks. So should I leave this PR open then?

**Comment by yaron2** [comment]
Yeah leave it

**Comment by yaron2** [comment]
Also, just looked at it. LGTM.

Waiting for @Haishi2016

**Pull request merged**
