### PR TITLE
Update more libraries

### PR DESCRIPTION
**Pull request by berndverst**
# Description

Update more libraries and clean up the `go.mod` files.

Came up with this handy command:
```bash
go list -mod=mod -f '{{if not .Indirect}}{{.}}{{end}}' -u -m all | grep "\[.*\]" | awk '{gsub("\\[|\\]","",$3); print $1 "@" $3}' | xargs go get
```

Now all `go.mod` files have exactly one `require` block for direct dependencies and one `require` block for indirect dependencies.

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]
No idea what your command does (that's a lot of bash-fu there), but the go.mod LGTM :)

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by berndverst** [comment]
> No idea what your command does (that's a lot of bash-fu there), but the go.mod LGTM :)

It finds all upgradeable direct dependencies and their latest minor version. Then one by one runs `go get` to upgrade that dependency.

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by berndverst** [comment]
Not sure why postgresql is failing here but it seems consistent. At first I thought it was due to `github.com/jackc/pgx/v5/stdlib` but it doesn't seem to be occurring elsewhere.

**Comment by berndverst** [comment]
The Postgresql State Certification Etag test was wrong. I fixed it. Not sure how this even worked up to this point. Maybe the underlying Etag behavior where subsequent etags were incremental changed. The test was erroneously making the assumption subsequent etags are sequential. (FYI @yaron2 :) )

Instead I added a step to fetch the the written key to get the latest Etag value.

**Review by ItalyPaleAle — APPROVED** [review]

**Review by ItalyPaleAle — APPROVED** [review]

**Review by ItalyPaleAle — APPROVED** [review]

**Pull request merged**
