### PR TITLE
Update License to Apache 2.0

### PR DESCRIPTION
**Pull request by greenie-msft**
# Description
Update LICENSE to Apache 2.0 as part of CNCF requirements

Issue: [#3911
](https://github.com/dapr/dapr/issues/3911)

### CODE REVIEW

**Review by CodeMonkeyLeet — COMMENTED** [review]
@greenie-msft LGTM ... is there a need to update the source code headers as well? The new license asserts copyright belongs to Dapr Authors and the old code still has Microsoft & Dapr Contributors in all the headers (and probably new files too if folks are just copy-pasting)

**Comment by yaron2** [comment]
> @greenie-msft LGTM ... is there a need to update the source code headers as well? The new license asserts copyright belongs to Dapr Authors and the old code still has Microsoft & Dapr Contributors in all the headers (and probably new files too if folks are just copy-pasting)

Changing the headers in source is recommended.

**Comment by Taction** [comment]
@greenie-msft please resolve conflicts.

**Comment by artursouza** [comment]
Changes already done. Closing.

**Pull request closed without merging**
