### PR TITLE
wasm: fixes test flake on Windows and strict mode

### PR DESCRIPTION
**Pull request by codefromthecrypt**
# Description

Windows clocks often don't give microsecond scope reading reliably. Our "strict mode" test was accidentally verifying a lower bound of time spent sleeping, when the important part is the upper bound. This removes the lower bound, so that tests pass on both unix and windows.

## Issue reference

See https://github.com/dapr/components-contrib/pull/2884#issuecomment-1664498860

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [n/a] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
I’m only interested In the windows tests so I’ll stop all other tests

**Review by ItalyPaleAle — CHANGES_REQUESTED** [review]
This doesn't seem to be working yet. It still fails because the delay is exactly 0 so it's never "greater than".

I can't leave a comment there, but you'll need to change L219 to:

```go
assert.GreaterOrEqual(t, duration, tc.minDuration)
assert.LessOrEqual(t, duration, tc.maxDuration)
```

**Comment by codefromthecrypt** [comment]
ah thanks for the keen eye, you are right this expression is wrong.

**Review by ItalyPaleAle — APPROVED** [review]

**Pull request merged**
