### PR TITLE
Support tracestate can be propagated in PubSub

### PR DESCRIPTION
**Pull request by CrazyHZM**
# Description

## Issue reference

Related https://github.com/dapr/dapr/issues/3470

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by beiwei30 — CHANGES_REQUESTED** [review]
@CrazyHZM would you mind to fix lint issue?

```
 Running [/home/runner/golangci-lint-1.31.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: bodyclose: failed prerequisites: [buildssa@github.com/dapr/components-contrib/pubsub/rocketmq [github.com/dapr/components-contrib/pubsub/rocketmq.test]: analysis skipped: errors in package: [/home/runner/work/components-contrib/components-contrib/pubsub/rocketmq/rocketmq.go:253:95: too few arguments in call to pubsub.NewCloudEventsEnvelope]]"
  level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/home/runner/work/components-contrib/components-contrib/pubsub/rocketmq/rocketmq.go:253:95: too few arguments in call to pubsub.NewCloudEventsEnvelope]"
  level=error msg="Running error: buildir: analysis skipped: errors in package: [/home/runner/work/components-contrib/components-contrib/pubsub/rocketmq/rocketmq.go:253:95: too few arguments in call to pubsub.NewCloudEventsEnvelope]"
```

**Review by beiwei30 — APPROVED** [review]
LGTM. Not sure why certification tests keep failing but it looks like this change is irrelevant to the failure. I will re-run the tests.

**Comment by beiwei30** [comment]
There are two pubsub certification tests failed due to the broken method signature. In order to conquer the cyclic dependency, I suggest to comment tests/certification/pubsub/kafka/kafka_test.go and tests/certification/pubsub/rabbitmq/rabbitmq_test.go temporarily, and file one separated issue to track it. These two tests need to re-enabled once the works on component-contrib and dapr are done.

```
Running certification tests for pubsub.kafka ... 
# github.com/dapr/dapr/pkg/runtime/pubsub
Error: /home/runner/go/pkg/mod/github.com/dapr/dapr@v1.4.4-0.20211104200044-e40edbd52063/pkg/runtime/pubsub/cloudevents.go:28:39: not enough arguments in call to pubsub.FromCloudEvent
	have ([]byte, string, string, string)
	want ([]byte, string, string, string, string)
Error: /home/runner/go/pkg/mod/github.com/dapr/dapr@v1.4.4-0.20211104200044-e40edbd52063/pkg/runtime/pubsub/cloudevents.go:30:46: not enough arguments in call to pubsub.NewCloudEventsEnvelope
	have (string, string, string, string, string, string, string, []byte, string)
	want (string, string, string, string, string, string, string, []byte, string, string)
WARN invalid TestEvent: FAIL	github.com/dapr/components-contrib/tests/certification/pubsub/kafka [build failed]
bad output from test2json: FAIL	github.com/dapr/components-contrib/tests/certification/pubsub/kafka [build failed]
```

**Review by beiwei30 — DISMISSED** [review]
Need to disable the two failed tests temporarily.

**Comment by yaron2** [comment]
> Need to disable the two failed tests temporarily.

@berndverst @pkedy

**Comment by CodeMonkeyLeet** [comment]
@beiwei30 It looks like a regression introduced by this PR, which changes the function signature of `pubsub.NewCloudEventsEnvelope`. This PR needs to update all pubsub components that take a dependency on the pubsub/envelope.go.

For comparison, the cron job running on the kafka certification test is [not failing in master](https://github.com/dapr/components-contrib/runs/4156310269?check_suite_focus=true).

**Comment by beiwei30** [comment]
> @beiwei30 It looks like a regression introduced by this PR, which changes the function signature of `pubsub.NewCloudEventsEnvelope`. This PR needs to update all pubsub components that take a dependency on the pubsub/envelope.go.
> 
> For comparison, the cron job running on the kafka certification test is [not failing in master](https://github.com/dapr/components-contrib/runs/4156310269?check_suite_focus=true).

@CodeMonkeyLeet The regression is expected, since tests/certification/go.mod relies on "github.com/dapr/dapr v1.4.4-0.20211104200044-e40edbd52063" but the author @CrazyHZM has not had chance to make the corresponding modification on dapr side to reflect the new method signature introduced by this issue. This is the major reason why the following compilation error observed:

```
Error: /home/runner/go/pkg/mod/github.com/dapr/dapr@v1.4.4-0.20211104200044-e40edbd52063/pkg/runtime/pubsub/cloudevents.go:28:39: not enough arguments in call to pubsub.FromCloudEvent
	have ([]byte, string, string, string)
	want ([]byte, string, string, string, string)
```

Under this circumstance, it looks like the following three steps are necessary in order to conquer the cyclic dependency:

1. Disable certification test for kafka and rabbitmq to make test pass in order to check in this change.
2. Make corresponding change on Dapr side to use the new method signature
3. Update go.mod for certification test and re-enable the tests.

Your opinion on this?

**Comment by CrazyHZM** [comment]
The suggestion of @beiwei30  can solve the problem, but I think the subsequent changes to the interface still have the same problem.
We can start from the original intention of Stable Components Certification Tests. My understanding is that this certification test is to verify the stability of these components. If this is the case, once the interface between `components-contrib` and `dapr` is changed, the verification will fail. So what we need to solve is how to make Certification tests not affect the common scenario of interface adjustment.

My suggestion is:
we can use Stable Components Certification Tests as a verification process of RC instead of performing every PR.

The advantage of this is that it can remind the publisher to consider that another component should also be released simultaneously every time it is released. 
such as dapr 1.5.0 needs to be released, and this version needs to be compatible with components-contrib version 1.4.0 and above are used together. At this time,  when dapr version 1.5.0 needs to be released, components-contrib 1.4.0 need to be released synchronously , the version correspondence can also be indicated on the official website.
cc  @berndverst @pkedy @CodeMonkeyLeet  @beiwei30 @yaron2

**Comment by CodeMonkeyLeet** [comment]
I think there might be a misconception here that a failed PR check such as the certification test failing prevents the PR from being merged into master and that is not the case; a maintainer can choose to merge a PR with failing checks into master. The sequence of steps for handling the dependencies laid out by @beiwei30 is how this can and should be handled, you don't need to disable the tests to do that.

That said, once an interface breaking change is merged into master, it will prevent other PRs from being merged using the `automerge` label by maintainers. While it is a convenience feature, it should be a priority to minimize the window in which the certification tests remain broken in case those failures mask other failures introduced by other PRs in the interim. To that end, I would propose that PRs with intended dapr-component interface changes should:
- Clearly state the intended interface change and which tests failures are expected given the change, so that approvers understand impact and coordination required when reviewing the PR.
- Have both the components-contrib and dapr PRs be submitted so they can be reviewed and approved ahead of time.
   - The PRs should link to each other.
   - The dapr PR can be developed using the [local validation instructions](https://github.com/dapr/components-contrib/blob/master/docs/developing-component.md#validating-with-dapr-core) so that main.go changes can be reviewed and approved.
 - After the components-contrib PR is merged, the dapr PR will need to be updated with a `go mod tidy` against components-contrib master, and then merged.
 - After the dapr PR is merged, the final `go mod tidy` on the certification tests can be submitted as a PR and then merged.

Assuming no other improvements, that's the bare minimum 3 PRs needed, as opposed to requiring an extra 2 PRs to disable and then re-enable specific tests.

I'll also point out that having the tests be continuously failing in that case is desirable, because the system is legitimately broken until at least the first 2 PRs are merged. It provides a signal on the turnaround times for handling these kinds of issues, and avoids the extra complexity of having to keep track of which tests were disabled, for what reasons, and who is responsible for remembering to re-enable them. 

The proposal that both components-contrib and dapr PRs be ready for review at the same time is to provide an opportunity for automation: if you can front-load the required manual portions of the process (code review and approvals, maintainer merge of the first components-contrib PR), everything that follows is purely mechanical (go mod tidy dapr PR and merge, go mod tidy all cert tests, submit PR and merge) and should be something we can automate in workflows kicked off by that first components-contrib merge.

**Comment by beiwei30** [comment]
I agree with @CodeMonkeyLeet 's suggestion. @CrazyHZM would you mind to follow his instructions and continue to make change ready on Dapr side?

**Comment by CrazyHZM** [comment]
@beiwei30 Yes, I will continue this in dapr later.

**Comment by CrazyHZM** [comment]
The changes on the dapr side have been modified, please review it：
https://github.com/dapr/dapr/pull/3883
@beiwei30

**Review by artursouza — APPROVED** [review]

**Comment by beiwei30** [comment]
> The changes on the dapr side have been modified, please review it： [dapr/dapr#3883](https://github.com/dapr/dapr/pull/3883) @beiwei30

@artursouza @CrazyHZM I approved dapr#3883

**Pull request merged**
