### PR TITLE
feature(middleware/routerchecker): avoid sending dirty data to opentelemetry system and logic servers.

### PR DESCRIPTION
**Pull request by 1046102779**
wecom-temp-4c72c50205064b4e3bcb25f0b85e4b37

wecom-temp-e0084be992abad96afed155e9a9a17e8

### CODE REVIEW

**Comment by 1046102779** [comment]
@CodeMonkeyLeet please review this pr

**Comment by CodeMonkeyLeet** [comment]
@1046102779 Can you submit a proposal issue for this PR that describes the behavior you want for the middleware checker? I'm not sure I understand the problem you're trying to solve based on the screenshots, or why the PR contains changes for both the pulsar pubsub component and a new route checker middleware.

**Comment by 1046102779** [comment]
When a bad request for NORTH-SOURTH-TRAFFIC enters a dapr cluster, it won't be intercepted and it will be sended to   opentelemetry system and logic server.

the PR supported custom router rule to intercept invalid requests, and it won't  send dirty data  to opentelemetry system and logic server.

image

image

**Comment by daixiang0** [comment]
Can I consider it as a route filter? If so, it may implement more than metrics. We need more discussion about it.

/cc @yaron2 @artursouza

**Comment by yaron2** [comment]
@1046102779 can you please fix the failing build?

**Review by artursouza — CHANGES_REQUESTED** [review]
If the intent is to filter out "bad requests", please change this to filter in good requests instead. It is much easier to predict the pattern of valid requests than it is to predict all the possible bad requests or attacks.

**Comment by 1046102779** [comment]
@artursouza please merge the pr. thks

**Comment by artursouza** [comment]
I need a docs issue for this before merging.

**Comment by 1046102779** [comment]
> I need a docs issue for this before merging.

issue: https://github.com/dapr/docs/issues/1894

**Comment by 1046102779** [comment]
@artursouza +1

**Comment by daixiang0** [comment]
Need an issue to track enablement in dapr runtime.

**Review by daixiang0 — APPROVED** [review]

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
Adding automerge and tagging for 1.6

**Pull request merged**
