### PR TITLE
Kafka: Add support to configure heartbeat interval and session timeout to kafka's consumer

### PR DESCRIPTION
**Pull request by denisbchrsk**
# Description

Added the option to configure heartbeat interval and session timeout in Kafka Pubsub and Kafka Binding - relevant for certain use cases where the sidecar might not be able to consistently send heartbeats to the Kafka brokers, or real time cases where you need the sidecar to send heartbeats more frequently than sarama's default values.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#4074

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
Thanks for this PR :)

It looks similar to #3371, can you confirm? CC: @sicoyle

**Comment by sicoyle** [comment]
Yes, I think we will want the network-level connection with the broker in my PR you've linked. My PR gets at keeping the sidecar with a constant network connection to the broker which is what you want in the event a sidecar becomes idle in the eyes of the broker.

**Comment by denisbchrsk** [comment]
Thanks @sicoyle for the confirmation, to summarize the differences in (hopefully) simpler terms from my previous comment:
- The PR in #3371 helps with the network-level connection from the sidecar to the broker, and keeping it alive (dealing with sidecar inactivity).
- This PR helps with defining the SLA from the sidecar to the broker specifically when consuming from the topic; if the broker is not accessible consistently within the default values that sarama has for the consumer / the sidecar dies, then this PR allows the user to configure the relevant values (heartbeatInterval / sessionTimeout) for the aforementioned consumer instance SLA (this is a known Kafka-specific configuration). With these changes, the user may be able to control this SLA, and may reduce unwarranted rebalances or increase warranted rebalances in the consumer group.

Both of these PRs are relevant in their own domain and are different.

**Comment by denisbchrsk** [comment]
Hey @ItalyPaleAle, is it possible to take a look at this again? I've explained in the previous comment why it's completely different from #3371

**Comment by ItalyPaleAle** [comment]
> Hey @ItalyPaleAle, is it possible to take a look at this again? I've explained in the previous comment why it's completely different from #3371

Yes, I think this is helpful. I've just merged #3371 and now there are some merge conflicts. Could you please take a look? I'll review after this is ready

**Comment by denisbchrsk** [comment]
Fixed the merge conflicts, it's ready for review @ItalyPaleAle

**Review by ItalyPaleAle — APPROVED** [review]
LGTM thanks!

Please don't forget to open a PR (or at least an issue) in dapr/docs to have the new options documented!

**Pull request merged**
