### PR TITLE
Support AWS secret manager as secret store

### PR DESCRIPTION
**Pull request by sayboras**
# Description

Addressed https://github.com/dapr/components-contrib/issues/112

## Issue reference

Please reference the issue this PR will close: https://github.com/dapr/components-contrib/issues/112

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests (coverage is 88.9% statements)
* [x] Extended the documentation

### CODE REVIEW

**Comment by sayboras** [comment]
@yaron2 your input is highly appreciated.

**Comment by yaron2** [comment]
Thanks for this!

Did you test the implementation with an actual aes secrets manager instance?

**Comment by sayboras** [comment]
> Thanks for this!
> 
> Did you test the implementation with an actual aes secrets manager instance?

@yaron2 Nope, I didn't. As want to check on this node, I need to point `dapr` to this branch, compile and start testing right? Wonder if there is any easier way to do so :cry:

**Comment by yaron2** [comment]
You can test the implementation from contrib without Dapr.

Init with the metadata and test the interface for getting and setting secrets.

Think of it as an integration test for the secret store interface where the implementation is the secret manager.

**Comment by sayboras** [comment]
@yaron2 I have written simple golang program to verify the changes. The result seems satisfactory.

```golang
func main() {
	secretName := "/aws/secret/testing"
	//Create a Secrets Manager client
	sm := secretmanager.NewSecretManager()
	err := sm.Init(secretstores.Metadata{
		Properties: map[string]string{
			"AccessKey":    "<my access key>",
			"Region":       "ap-southeast-2",
			"SecretKey":    "<my secret key>",
			"SessionToken": "<my session token>",
		},
	})
	if err != nil {
		fmt.Printf("unable to init secret manager : %+v", err)
		return
	}
	response, err := sm.GetSecret(secretstores.GetSecretRequest{
		Name: secretName,
		Metadata: map[string]string{
		},
	})

	if err != nil {
		fmt.Printf("unable to retrieve secret %+v", err)
		return
	}

	fmt.Printf("%+v", response.Data)
}
```

Output for go integration test and aws cli
```
$ go run main.go  
map[/aws/secret/testing:{"/aws/secret/testing":"testing"}]

$ aws secretsmanager get-secret-value --secret-id /aws/secret/testing
{
    "ARN": "arn:aws:secretsmanager:ap-southeast-2:XXXXXXX:secret:/aws/secret/testing-FrHt6d",
    "Name": "/aws/secret/testing",
    "VersionId": "ebf4cd4b-d454-421e-945d-5a3cc3bf9b6d",
    "SecretString": "{\"/aws/secret/testing\":\"testing\"}",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": 1574677861.479
}
```

**Comment by youngbupark** [comment]
> @yaron2 I have written simple golang program to verify the changes. The result seems satisfactory.
> FYI all tokens and aws related details are masked.
> 
> Need your help to take another look.
> 
> ```go
> func main() {
> 	secretName := "/aws/secret/testing"
> 	sm := secretmanager.NewSecretManager()
> 	err := sm.Init(secretstores.Metadata{
> 		Properties: map[string]string{
> 			"AccessKey":    "<my access key>",
> 			"Region":       "ap-southeast-2",
> 			"SecretKey":    "<my secret key>",
> 			"SessionToken": "<my session token>",
> 		},
> 	})
> 	if err != nil {
> 		fmt.Printf("unable to init secret manager : %+v", err)
> 		return
> 	}
> 	response, err := sm.GetSecret(secretstores.GetSecretRequest{
> 		Name: secretName,
> 		Metadata: map[string]string{
> 		},
> 	})
> 
> 	if err != nil {
> 		fmt.Printf("unable to retrieve secret %+v", err)
> 		return
> 	}
> 
> 	fmt.Printf("%+v", response.Data)
> }
> ```
> 
> Output for go integration test and aws cli
> 
> ```
> $ go run main.go  
> map[/aws/secret/testing:{"/aws/secret/testing":"testing"}]
> 
> $ aws secretsmanager get-secret-value --secret-id /aws/secret/testing
> {
>     "ARN": "arn:aws:secretsmanager:ap-southeast-2:XXXXXXX:secret:/aws/secret/testing-FrHt6d",
>     "Name": "/aws/secret/testing",
>     "VersionId": "ebf4cd4b-d454-421e-945d-5a3cc3bf9b6d",
>     "SecretString": "{\"/aws/secret/testing\":\"testing\"}",
>     "VersionStages": [
>         "AWSCURRENT"
>     ],
>     "CreatedDate": 1574677861.479
> }
> ```

Can you add this integration to this PR ? but please use go test and `integration` build tag. then we can run your integration test by using build tag.

```
go test -tag integration ...
```

For example,
```
// +build integration

package secretmanager

func TestGetSecret(t *testing.T) {
   // the code in your main entry
}
```

**Comment by sayboras** [comment]
@youngbupark awesome, good to know that we can do this way. Normally, I ran the integration in docker image only.

I have made the changes, please let me know if you have other comments.

```
$ go test -tags=integration .
ok  	github.com/dapr/components-contrib/secretstores/aws/secretmanager	0.498s
```

**Comment by yaron2** [comment]
Thanks, excited to see this merged!

**Pull request merged**
