### PR TITLE
Update AWS SDK versions

### PR DESCRIPTION
**Pull request by Jossec101**
# Description

Bump AWS SDK (both V1 & V2) version to latest to support AWS JSON Protocol in SQS

## Issue reference

#3354 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [N/A] Created/updated tests
* [N/A] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Review by berndverst — CHANGES_REQUESTED** [review]
You need to run `make modtidy-all` and commit all the `go.sum` and `go.mod` files that were changed.

**Comment by Jossec101** [comment]
> You need to run `make modtidy-all` and commit all the `go.sum` and `go.mod` files that were changed.

Done 🏁

**Review by ItalyPaleAle — APPROVED** [review]

**Pull request merged**
