### PR TITLE
[Security] Remove orphaned unmaintained Temporal component

### PR DESCRIPTION
**Pull request by berndverst**
# Description

The only 4 currently open high and medium priority security issues are in our Temporal test infrastructure code. The temporal component is not registered in Dapr runtime and no development has gone into this.

Since this component was never used in any Dapr release I am electing to remove this component from contrib for maintenance reasons. Recall that we were not able to add it to runtime because it increased the memory consumption of Dapr more than the allowable threshold.

### CODE REVIEW

**Review by artursouza — APPROVED** [review]

**Comment by artursouza** [comment]
Please, collect feedback from other maintainers too.

**Review by yaron2 — APPROVED** [review]

**Comment by berndverst** [comment]
@ItalyPaleAle told me via chat he's ok with it!

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
LGTM. Can we get a +1  (or at least a "not -1") from @mukundansundar  and @daixiang0 too as runtime maintainers too?

**Comment by berndverst** [comment]
> LGTM. Can we get a +1 (or at least a "not -1") from @mukundansundar and @daixiang0 too as runtime maintainers too?

This component is not registered in runtime anyway. So it has no impact there. If something comes up (though that's currently impossible) we can always revert this very self contained PR :)

**Pull request merged**
