### PR TITLE
Upgrade pulsar client to 0.8.0

### PR DESCRIPTION
**Pull request by Shoothzj**
# Description

Upgrade pulsar client to 0.8.0, it solves https://github.com/apache/pulsar-client-go/releases/tag/v0.8.0

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

### CODE REVIEW

**Comment by daixiang0** [comment]
Please fix DCO first.

**Comment by Shoothzj** [comment]
> Please fix DCO first.

fixed

**Comment by yaron2** [comment]
@Shoothzj please run `go mod tidy -compat=1.17` and push the changes.

**Comment by yaron2** [comment]
@Shoothzj apologies, one more:

```
make modtidy-all
```

**Comment by Shoothzj** [comment]
@yaron2 Thanks, let me try

**Comment by Shoothzj** [comment]
@yaron2 please approve to trigger the ci, thanks

**Comment by Shoothzj** [comment]
@yaron2 @daixiang0 PTAL, all checks have passed

**Review by daixiang0 — APPROVED** [review]

**Comment by daixiang0** [comment]
@Shoothzj thanks for your contribution and welcome to Dapr community!

**Pull request merged**
