### PR TITLE
Backporting #1882 (MQTT fix) into release-1.8

### LINKED ISSUE #1881: MQTT wildcard and shared subscriptions are broken (again)
## Expected Behavior

When I subscribe to a mqtt topic with a wildcard subscription or a shared subscription, I expect to receive messages.

## Actual Behavior

No messages are received and the error `no handler defined for topic` is printed in the daprd log.

## Steps to Reproduce the Problem

- Add a `pubsub.mqtt` component
- Subscribe with a shared subscription (`$share/group-id/topic`) or with a wildcard subscription (`topic/#`)

## Release Note

RELEASE NOTE:

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
# Description

This PR backports #1882 into release-1.8 and fixes #1881 for the release branch.

Because of the very large number of changes in master, this is a separate PR and should not be cherry-picked back into master. For master, please merge #1882.

### CODE REVIEW

**Comment by berndverst** [comment]
MQTT Vernemq test run failed - which obviously is important for this PR. Rerunning.. hopefully it was just flaky.

**Comment by ItalyPaleAle** [comment]
@berndverst  debugging now locally. This change works in #1882 against master. For some reason it doesn't work with vernemq (but works with others) against release-1.8. Looking into it

**Review by berndverst — CHANGES_REQUESTED** [review]
Please investigate vermemq errors as discussed. (Leaving this review only so that nobody accidentally merges this)

**Comment by ItalyPaleAle** [comment]
@berndverst should be fixed now. This was due to a deadlock that somehow only manifested itself with vernemq. I removed the locks, which are not necessary in 1.8 since we don't subscribe/unsubscribe dynamically, so the risk for consistency while iterating over the handler map is low.

In master, the code was reworked and there shouldn't be a risk of deadlocks even with locks enabled.

**Pull request merged**
