### PR TITLE
Redis State Store query: numeric operators do not work correctly on large numbers

### PR DESCRIPTION
**Pull request by gspadotto**
# Description

Applied changes to the formatting of numeric values.

I have no deep knowledge of why all numeric values in the Unit Tests are considered as float, so I changed the unit tests in order to make them pass. (I know this is **_bad_**)

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #3332

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#3332

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
> I have no deep knowledge of why all numeric values in the Unit Tests are considered as float, so I changed the unit tests in order to make them pass. (I know this is bad)

I _think_ (haven't investigated too much however) that it's because they come from JSON. In order to stay compatible with JS (where all numbers are floats), the JSON parser uses float64 when parsing numbers into `any`. See the note here: https://pkg.go.dev/encoding/json#Unmarshal

**Comment by gspadotto** [comment]
Hi @ItalyPaleAle, I have no knowledge of the process by which a given PR is associated to a specific milestone, 
so do not "roast" me for the following request of mine but... 

could this fix be scheduled for v1.13 or - at least - be included in the nightly builds (like [this](https://hub.docker.com/layers/daprio/dapr/nightly-2024-02-06/images/sha256-5f46b2191e328f7516ca08f57d9ec885d11a1dadc6798c678eae08932113c322?context=explore))?

My use cases rely on this fix to be in place so I would **really** appreciate if I could test it as soon as possible. 
I'm aware though that my requests will have to yeld to the official release strategy. 

Thanks.

**Comment by ItalyPaleAle** [comment]
Sadly we are really past the code freeze date for 1.13, which was many weeks ago. We can, and sometimes do, make exceptions for bugs that are critical - in this case, because state store querying is an alpha feature (with no path to ever become stable), I am afraid it may be too late for 1.13.

We can definitely include it in a nightly build. I can pin an updated version of this repo in dapr/dapr so it can start being published.

**Comment by ItalyPaleAle** [comment]
@gspadotto buona notizia. I spoke with another maintainer, we are ok cherry-picking this into 1.13. It should be included in the next RC :)

**Pull request merged**
